define({
  "gridTabLabel": "ł_Grid__ą",
  "labelTabLabel": "ł_Labels___ą",
  "referenceSystemTabLabel": "ł_Reference System______ą",
  "gridTabDescription": "ł_Set the appearance and behavior of the grid cells________________ą.",
  "cellOutlineColor": "ł_Cell Outine color______ą",
  "cellFillColor": "ł_Cell Fill color______ą",
  "transparency": "ł_Transparency_____ą",
  "cellShapeDropDown": "ł_Cell Shape____ą",
  "default": "ł_Rectangle____ą",
  "hexagon": "ł_Hexagon___ą",
  "cellUnitsDropDown": "ł_Cell Units____ą",
  "miles": "ł_Miles___ą",
  "kilometers": "ł_Kilometers____ą",
  "feet": "ł_Feet__ą",
  "meters": "ł_Meters___ą",
  "yards": "ł_Yards___ą",
  "nautical-miles": "ł_Nautical Miles_____ą",
  "gridOriginDropDown": "ł_Grid Origin____ą",
  "lowerLeft": "ł_Lower-Left____ą",
  "lowerRight": "ł_Lower-Right____ą",
  "upperLeft": "ł_Upper-Left____ą",
  "upperRight": "ł_Upper-Right____ą",
  "center": "ł_Center___ą",
  "labelTabDescription": "ł_Set the appearance and behavior of the grid labels________________ą.",
  "labelSettings": "ł_Label Style____ą",
  "font": "ł_Font__ą",
  "textSize": "ł_Text Size____ą",
  "textColor": "ł_Text Color____ą",
  "halo": "ł_Halo__ą",
  "show": "ł_Show__ą",
  "labelTypeDropDown": "ł_Label Type____ą",
  "alphaNumeric": "ł_Alpha-Numeric_____ą",
  "alphaAlpha": "ł_Alpha-Alpha____ą",
  "numeric": "ł_Numeric___ą",
  "labelDirectionDropDown": "ł_Label Direction______ą",
  "horizontal": "ł_Horizontal____ą",
  "vertical": "ł_Vertical___ą",
  "labelOriginDropDown": "ł_Label Origin_____ą",
  "referenceSystemlTabDescription": "ł_Set the default reference system___________ą.",
  "MGRS": "ł_MGRS__ą",
  "USNG": "ł_USNG__ą",
  "lockSettings": "ł_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________ą"
});