define({
  "_widgetLabel": "Ж_Gridded Reference Graphic_________Я",
  "newGRGFromAreaButtonLabel": "Ж_Define a Grid from an Area_________Я",
  "newGRGFromPointButtonLabel": "Ж_Define a Grid from a Point_________Я",
  "newGRGFromAreaTitle": "Ж_Define a Grid from an Area_________Я",
  "newGRGFromPointTitle": "Ж_Define a Grid from a Point_________Я",
  "newGRGBySizeButtonLabel": "Ж_By Dimension_____Я",
  "newGRGFromRefSystemButtonLabel": "Ж_By Reference System_______Я",
  "newGRGByTimeLabel": "Ж_By Time and Speed______Я",
  "newGRGFromNonStandardButtonLabel": "Ж_Define Non-Standard Grid________Я",
  "newGRGAreaBySizeTitle": "Ж_GRG from an Area by Dimension__________Я",
  "newGRGAreaBySizeDefineAreaLabel": "Ж_GRG Area___Я",
  "addGRGAreaPolygonToolTip": "Ж_Draw GRG Area using polygon_________Я",
  "addGRGAreaExtentToolTip": "Ж_Draw GRG Area using extent_________Я",
  "rotation": "Ж_Grid Rotation_____Я",
  "numberRowsColumnsLabel": "Ж_Define number of rows and columns___________Я",
  "newGRGAreaByRefSystemTitle": "Ж_GRG from an Area by Reference System____________Я",
  "gridSize": "Ж_Grid Size____Я",
  "UTMZoneandBand": "Ж_Grid Zone____Я",
  "100000m": "Ж_100000 meter_____Я",
  "10000m": "Ж_10000 meter____Я",
  "1000m": "Ж_1000 meter____Я",
  "100m": "Ж_100 meter____Я",
  "10m": "Ж_10 meter___Я",
  "clipGrid": "Ж_Clip Grid to GRG Area_______Я",
  "newGRGAreaFromNonStandardTitle": "Ж_New NRG___Я",
  "newGRGPointBySizeTitle": "Ж_GRG from Point by Dimension_________Я",
  "newGRGPointByRefSystemTitle": "Ж_GRG from Point by Reference System___________Я",
  "newGRGPointByTimeTitle": "Ж_GRG from Point using Time and Speed____________Я",
  "time": "Ж_Time__Я",
  "rate": "Ж_Speed___Я",
  "hours": "Ж_Hours___Я",
  "minutes": "Ж_Minutes___Я",
  "seconds": "Ж_Seconds___Я",
  "ftPerSec": "Ж_Feet / second_____Я",
  "ftPerHour": "Ж_Feet / hour____Я",
  "kmPerSec": "Ж_Kilometers / second_______Я",
  "kmPerHour": "Ж_Kilometers / hour______Я",
  "mPerSec": "Ж_Meters / second______Я",
  "mPerHour": "Ж_Meters / hour_____Я",
  "miPerSec": "Ж_Miles / second_____Я",
  "miPerHour": "Ж_Miles / hour_____Я",
  "nMPerSec": "Ж_Nautical Miles / second________Я",
  "nMPerHour": "Ж_Nautical Miles / hour_______Я",
  "settingsTitle": "Ж_Settings___Я",
  "labelSettingsLabel": "Ж_Label Settings_____Я",
  "labelSettingsButtonLabel": "Ж_Configure Label Settings________Я",
  "gridSettingsLabel": "Ж_Grid Settings_____Я",
  "gridSettingsButtonLabel": "Ж_Configure Grid Settings________Я",
  "transparency": "Ж_Transparency_____Я",
  "labelStyle": "Ж_Label Style____Я",
  "font": "Ж_Font__Я",
  "textSize": "Ж_Text Size____Я",
  "textColor": "Ж_Text Color____Я",
  "halo": "Ж_Halo__Я",
  "show": "Ж_Show__Я",
  "lockSettings": "Ж_Settings have been locked by the application owner________________Я",
  "gridSettings": {
    "cellShape": "Ж_Cell Shape____Я",
    "cellUnits": "Ж_Cell Units____Я",
    "cellOutline": "Ж_Cell Outline Settings_______Я",
    "cellFill": "Ж_Cell Fill Settings______Я",
    "gridReferenceSystem": "Ж_Reference System______Я",
    "gridDatum": "Ж_Datum: WGS84_____Я",
    "labelStartPosition": "Ж_Label Origin_____Я",
    "labelType": "Ж_Label Type____Я",
    "labelDirection": "Ж_Label Direction______Я",
    "gridOrigin": "Ж_Grid Origin____Я",
    "default": "Ж_Rectangle____Я",
    "hexagon": "Ж_Hexagon___Я",
    "miles": "Ж_Miles___Я",
    "kilometers": "Ж_Kilometers____Я",
    "feet": "Ж_Feet__Я",
    "meters": "Ж_Meters___Я",
    "yards": "Ж_Yards___Я",
    "nautical-miles": "Ж_Nautical Miles_____Я",
    "lowerLeft": "Ж_Lower-Left____Я",
    "lowerRight": "Ж_Lower-Right____Я",
    "upperLeft": "Ж_Upper-Left____Я",
    "upperRight": "Ж_Upper-Right____Я",
    "center": "Ж_Center___Я",
    "alphaNumeric": "Ж_Alpha-Numeric_____Я",
    "alphaAlpha": "Ж_Alpha-Alpha____Я",
    "numeric": "Ж_Numeric___Я",
    "horizontal": "Ж_Horizontal____Я",
    "vertical": "Ж_Vertical___Я",
    "MGRS": "Ж_MGRS__Я",
    "USNG": "Ж_USNG__Я",
    "showLabels": "Ж_Show Labels____Я"
  },
  "publishTitle": "Ж_Publish GRG to Portal_______Я",
  "publishGRGBtn": "Ж_Publish___Я",
  "GRGLayerName": "Ж_Published GRG Layer Name________Я",
  "invalidGRGLayerName": "Ж_Layer name must only contain alpha-numeric characters and underscores______________________Я",
  "missingGRGLayerName": "Ж_You must enter a name for the GRG___________Я",
  "publishingFailedLayerExists": "Ж_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________Я.",
  "checkService": "Ж_Check Service: {0}______Я",
  "createService": "Ж_Create Service: {0}_______Я",
  "unableToCreate": "Ж_Unable to create: {0}_______Я",
  "addToDefinition": "Ж_Add to definition: {0}________Я",
  "successfullyPublished": "Ж_Successfully published web layer{0}Manage the web layer__________________Я",
  "userRole": "Ж_Unable to create service because user does not have permissions____________________Я",
  "createGRGBtn": "Ж_Create GRG____Я",
  "clearGRGBtn": "Ж_Clear___Я",
  "labelFormat": "Ж_Label Format_____Я",
  "helpIconTooltip": "Ж_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________Я",
  "addPointToolTip": "Ж_Add GRG Origin_____Я",
  "cellWidth": "Ж_Cell Width (x)_____Я",
  "cellHeight": "Ж_Cell Height (y)______Я",
  "invalidNumberMessage": "Ж_The value entered is not valid__________Я",
  "invalidRangeMessage": "Ж_Value must be greater than 0_________Я",
  "gridAngleInvalidRangeMessage": "Ж_Value must be between -89.9 and 89.9____________Я",
  "formatIconTooltip": "Ж_Format Input_____Я",
  "coordInputLabel": "Ж_GRG Origin (DD)______Я",
  "setCoordFormat": "Ж_Set Coordinate Format String_________Я",
  "prefixNumbers": "Ж_Add '+/-' prefix to positive and negative numbers________________Я",
  "cancelBtn": "Ж_Cancel___Я",
  "applyBtn": "Ж_Apply___Я",
  "comfirmInputNotation": "Ж_Confirm Input Notation________Я",
  "notationsMatch": "Ж_notations match your input please confirm which you would like to use______________________Я:",
  "numberOfCellsHorizontal": "Ж_# Horizontal Cells______Я",
  "numberOfCellsVertical": "Ж_# Vertical Cells______Я",
  "gridAngle": "Ж_Grid Rotation_____Я",
  "tooManyCellsErrorMessage": "Ж_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________Я.",
  "missingParametersMessage": "Ж_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________Я",
  "missingOriginParametersMessage": "Ж_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________Я",
  "invalidWidthHeightParametersMessage": "Ж_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________Я",
  "invalidHorizontalVerticalParametersMessage": "Ж_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________Я",
  "drawPointToolTip": "Ж_Click to add GRG origin point__________Я",
  "missingLayerNameMessage": "Ж_You must enter a valid layer name before you can publish__________________Я",
  "parseCoordinatesError": "Ж_Unable to parse coordinates. Please check your input_________________Я.",
  "grgPolarRegionError": "Ж_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________Я.",
  "grgPolarOriginError": "Ж_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________Я.",
  "DD": "Ж_DD__Я",
  "DDM": "Ж_DDM__Я",
  "DMS": "Ж_DMS__Я",
  "DDRev": "Ж_DDRev___Я",
  "DDMRev": "Ж_DDMRev___Я",
  "DMSRev": "Ж_DMSRev___Я",
  "USNG": "Ж_USNG__Я",
  "MGRS": "Ж_MGRS__Я",
  "UTM_H": "Ж_UTM (H)___Я",
  "UTM": "Ж_UTM__Я",
  "GARS": "Ж_GARS__Я",
  "GEOREF": "Ж_GEOREF___Я",
  "DDLatLongNotation": "Ж_Decimal Degrees - Latitude/Longitude____________Я",
  "DDLongLatNotation": "Ж_Decimal Degrees  - Longitude/Latitude____________Я",
  "DDMLatLongNotation": "Ж_Degrees Decimal Minutes - Latitude/Longitude______________Я",
  "DDMLongLatNotation": "Ж_Degrees Decimal Minutes - Longitude/Latitude______________Я",
  "DMSLatLongNotation": "Ж_Degrees Minutes Seconds - Latitude/Longitude______________Я",
  "DMSLongLatNotation": "Ж_Degrees Minutes Seconds - Longitude/Latitude______________Я",
  "GARSNotation": "Ж_GARS__Я",
  "GEOREFNotation": "Ж_GEOREF___Я",
  "MGRSNotation": "Ж_MGRS__Я",
  "USNGNotation": "Ж_USNG__Я",
  "UTMBandNotation": "Ж_UTM - Band Letter______Я",
  "UTMHemNotation": "Ж_UTM - Hemisphere (N/S)________Я"
});