define({
  "_widgetLabel": "Č_Gridded Reference Graphic_________ž",
  "newGRGFromAreaButtonLabel": "Č_Define a Grid from an Area_________ž",
  "newGRGFromPointButtonLabel": "Č_Define a Grid from a Point_________ž",
  "newGRGFromAreaTitle": "Č_Define a Grid from an Area_________ž",
  "newGRGFromPointTitle": "Č_Define a Grid from a Point_________ž",
  "newGRGBySizeButtonLabel": "Č_By Dimension_____ž",
  "newGRGFromRefSystemButtonLabel": "Č_By Reference System_______ž",
  "newGRGByTimeLabel": "Č_By Time and Speed______ž",
  "newGRGFromNonStandardButtonLabel": "Č_Define Non-Standard Grid________ž",
  "newGRGAreaBySizeTitle": "Č_GRG from an Area by Dimension__________ž",
  "newGRGAreaBySizeDefineAreaLabel": "Č_GRG Area___ž",
  "addGRGAreaPolygonToolTip": "Č_Draw GRG Area using polygon_________ž",
  "addGRGAreaExtentToolTip": "Č_Draw GRG Area using extent_________ž",
  "rotation": "Č_Grid Rotation_____ž",
  "numberRowsColumnsLabel": "Č_Define number of rows and columns___________ž",
  "newGRGAreaByRefSystemTitle": "Č_GRG from an Area by Reference System____________ž",
  "gridSize": "Č_Grid Size____ž",
  "UTMZoneandBand": "Č_Grid Zone____ž",
  "100000m": "Č_100000 meter_____ž",
  "10000m": "Č_10000 meter____ž",
  "1000m": "Č_1000 meter____ž",
  "100m": "Č_100 meter____ž",
  "10m": "Č_10 meter___ž",
  "clipGrid": "Č_Clip Grid to GRG Area_______ž",
  "newGRGAreaFromNonStandardTitle": "Č_New NRG___ž",
  "newGRGPointBySizeTitle": "Č_GRG from Point by Dimension_________ž",
  "newGRGPointByRefSystemTitle": "Č_GRG from Point by Reference System___________ž",
  "newGRGPointByTimeTitle": "Č_GRG from Point using Time and Speed____________ž",
  "time": "Č_Time__ž",
  "rate": "Č_Speed___ž",
  "hours": "Č_Hours___ž",
  "minutes": "Č_Minutes___ž",
  "seconds": "Č_Seconds___ž",
  "ftPerSec": "Č_Feet / second_____ž",
  "ftPerHour": "Č_Feet / hour____ž",
  "kmPerSec": "Č_Kilometers / second_______ž",
  "kmPerHour": "Č_Kilometers / hour______ž",
  "mPerSec": "Č_Meters / second______ž",
  "mPerHour": "Č_Meters / hour_____ž",
  "miPerSec": "Č_Miles / second_____ž",
  "miPerHour": "Č_Miles / hour_____ž",
  "nMPerSec": "Č_Nautical Miles / second________ž",
  "nMPerHour": "Č_Nautical Miles / hour_______ž",
  "settingsTitle": "Č_Settings___ž",
  "labelSettingsLabel": "Č_Label Settings_____ž",
  "labelSettingsButtonLabel": "Č_Configure Label Settings________ž",
  "gridSettingsLabel": "Č_Grid Settings_____ž",
  "gridSettingsButtonLabel": "Č_Configure Grid Settings________ž",
  "transparency": "Č_Transparency_____ž",
  "labelStyle": "Č_Label Style____ž",
  "font": "Č_Font__ž",
  "textSize": "Č_Text Size____ž",
  "textColor": "Č_Text Color____ž",
  "halo": "Č_Halo__ž",
  "show": "Č_Show__ž",
  "lockSettings": "Č_Settings have been locked by the application owner________________ž",
  "gridSettings": {
    "cellShape": "Č_Cell Shape____ž",
    "cellUnits": "Č_Cell Units____ž",
    "cellOutline": "Č_Cell Outline Settings_______ž",
    "cellFill": "Č_Cell Fill Settings______ž",
    "gridReferenceSystem": "Č_Reference System______ž",
    "gridDatum": "Č_Datum: WGS84_____ž",
    "labelStartPosition": "Č_Label Origin_____ž",
    "labelType": "Č_Label Type____ž",
    "labelDirection": "Č_Label Direction______ž",
    "gridOrigin": "Č_Grid Origin____ž",
    "default": "Č_Rectangle____ž",
    "hexagon": "Č_Hexagon___ž",
    "miles": "Č_Miles___ž",
    "kilometers": "Č_Kilometers____ž",
    "feet": "Č_Feet__ž",
    "meters": "Č_Meters___ž",
    "yards": "Č_Yards___ž",
    "nautical-miles": "Č_Nautical Miles_____ž",
    "lowerLeft": "Č_Lower-Left____ž",
    "lowerRight": "Č_Lower-Right____ž",
    "upperLeft": "Č_Upper-Left____ž",
    "upperRight": "Č_Upper-Right____ž",
    "center": "Č_Center___ž",
    "alphaNumeric": "Č_Alpha-Numeric_____ž",
    "alphaAlpha": "Č_Alpha-Alpha____ž",
    "numeric": "Č_Numeric___ž",
    "horizontal": "Č_Horizontal____ž",
    "vertical": "Č_Vertical___ž",
    "MGRS": "Č_MGRS__ž",
    "USNG": "Č_USNG__ž",
    "showLabels": "Č_Show Labels____ž"
  },
  "publishTitle": "Č_Publish GRG to Portal_______ž",
  "publishGRGBtn": "Č_Publish___ž",
  "GRGLayerName": "Č_Published GRG Layer Name________ž",
  "invalidGRGLayerName": "Č_Layer name must only contain alpha-numeric characters and underscores______________________ž",
  "missingGRGLayerName": "Č_You must enter a name for the GRG___________ž",
  "publishingFailedLayerExists": "Č_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ž.",
  "checkService": "Č_Check Service: {0}______ž",
  "createService": "Č_Create Service: {0}_______ž",
  "unableToCreate": "Č_Unable to create: {0}_______ž",
  "addToDefinition": "Č_Add to definition: {0}________ž",
  "successfullyPublished": "Č_Successfully published web layer{0}Manage the web layer__________________ž",
  "userRole": "Č_Unable to create service because user does not have permissions____________________ž",
  "createGRGBtn": "Č_Create GRG____ž",
  "clearGRGBtn": "Č_Clear___ž",
  "labelFormat": "Č_Label Format_____ž",
  "helpIconTooltip": "Č_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________ž",
  "addPointToolTip": "Č_Add GRG Origin_____ž",
  "cellWidth": "Č_Cell Width (x)_____ž",
  "cellHeight": "Č_Cell Height (y)______ž",
  "invalidNumberMessage": "Č_The value entered is not valid__________ž",
  "invalidRangeMessage": "Č_Value must be greater than 0_________ž",
  "gridAngleInvalidRangeMessage": "Č_Value must be between -89.9 and 89.9____________ž",
  "formatIconTooltip": "Č_Format Input_____ž",
  "coordInputLabel": "Č_GRG Origin (DD)______ž",
  "setCoordFormat": "Č_Set Coordinate Format String_________ž",
  "prefixNumbers": "Č_Add '+/-' prefix to positive and negative numbers________________ž",
  "cancelBtn": "Č_Cancel___ž",
  "applyBtn": "Č_Apply___ž",
  "comfirmInputNotation": "Č_Confirm Input Notation________ž",
  "notationsMatch": "Č_notations match your input please confirm which you would like to use______________________ž:",
  "numberOfCellsHorizontal": "Č_# Horizontal Cells______ž",
  "numberOfCellsVertical": "Č_# Vertical Cells______ž",
  "gridAngle": "Č_Grid Rotation_____ž",
  "tooManyCellsErrorMessage": "Č_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________ž.",
  "missingParametersMessage": "Č_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________ž",
  "missingOriginParametersMessage": "Č_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________ž",
  "invalidWidthHeightParametersMessage": "Č_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________ž",
  "invalidHorizontalVerticalParametersMessage": "Č_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________ž",
  "drawPointToolTip": "Č_Click to add GRG origin point__________ž",
  "missingLayerNameMessage": "Č_You must enter a valid layer name before you can publish__________________ž",
  "parseCoordinatesError": "Č_Unable to parse coordinates. Please check your input_________________ž.",
  "grgPolarRegionError": "Č_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________ž.",
  "grgPolarOriginError": "Č_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________ž.",
  "DD": "Č_DD__ž",
  "DDM": "Č_DDM__ž",
  "DMS": "Č_DMS__ž",
  "DDRev": "Č_DDRev___ž",
  "DDMRev": "Č_DDMRev___ž",
  "DMSRev": "Č_DMSRev___ž",
  "USNG": "Č_USNG__ž",
  "MGRS": "Č_MGRS__ž",
  "UTM_H": "Č_UTM (H)___ž",
  "UTM": "Č_UTM__ž",
  "GARS": "Č_GARS__ž",
  "GEOREF": "Č_GEOREF___ž",
  "DDLatLongNotation": "Č_Decimal Degrees - Latitude/Longitude____________ž",
  "DDLongLatNotation": "Č_Decimal Degrees  - Longitude/Latitude____________ž",
  "DDMLatLongNotation": "Č_Degrees Decimal Minutes - Latitude/Longitude______________ž",
  "DDMLongLatNotation": "Č_Degrees Decimal Minutes - Longitude/Latitude______________ž",
  "DMSLatLongNotation": "Č_Degrees Minutes Seconds - Latitude/Longitude______________ž",
  "DMSLongLatNotation": "Č_Degrees Minutes Seconds - Longitude/Latitude______________ž",
  "GARSNotation": "Č_GARS__ž",
  "GEOREFNotation": "Č_GEOREF___ž",
  "MGRSNotation": "Č_MGRS__ž",
  "USNGNotation": "Č_USNG__ž",
  "UTMBandNotation": "Č_UTM - Band Letter______ž",
  "UTMHemNotation": "Č_UTM - Hemisphere (N/S)________ž"
});