define({
  "_widgetLabel": "須_Gridded Reference Graphic_________鷗",
  "newGRGFromAreaButtonLabel": "須_Define a Grid from an Area_________鷗",
  "newGRGFromPointButtonLabel": "須_Define a Grid from a Point_________鷗",
  "newGRGFromAreaTitle": "須_Define a Grid from an Area_________鷗",
  "newGRGFromPointTitle": "須_Define a Grid from a Point_________鷗",
  "newGRGBySizeButtonLabel": "須_By Dimension_____鷗",
  "newGRGFromRefSystemButtonLabel": "須_By Reference System_______鷗",
  "newGRGByTimeLabel": "須_By Time and Speed______鷗",
  "newGRGFromNonStandardButtonLabel": "須_Define Non-Standard Grid________鷗",
  "newGRGAreaBySizeTitle": "須_GRG from an Area by Dimension__________鷗",
  "newGRGAreaBySizeDefineAreaLabel": "須_GRG Area___鷗",
  "addGRGAreaPolygonToolTip": "須_Draw GRG Area using polygon_________鷗",
  "addGRGAreaExtentToolTip": "須_Draw GRG Area using extent_________鷗",
  "rotation": "須_Grid Rotation_____鷗",
  "numberRowsColumnsLabel": "須_Define number of rows and columns___________鷗",
  "newGRGAreaByRefSystemTitle": "須_GRG from an Area by Reference System____________鷗",
  "gridSize": "須_Grid Size____鷗",
  "UTMZoneandBand": "須_Grid Zone____鷗",
  "100000m": "須_100000 meter_____鷗",
  "10000m": "須_10000 meter____鷗",
  "1000m": "須_1000 meter____鷗",
  "100m": "須_100 meter____鷗",
  "10m": "須_10 meter___鷗",
  "clipGrid": "須_Clip Grid to GRG Area_______鷗",
  "newGRGAreaFromNonStandardTitle": "須_New NRG___鷗",
  "newGRGPointBySizeTitle": "須_GRG from Point by Dimension_________鷗",
  "newGRGPointByRefSystemTitle": "須_GRG from Point by Reference System___________鷗",
  "newGRGPointByTimeTitle": "須_GRG from Point using Time and Speed____________鷗",
  "time": "須_Time__鷗",
  "rate": "須_Speed___鷗",
  "hours": "須_Hours___鷗",
  "minutes": "須_Minutes___鷗",
  "seconds": "須_Seconds___鷗",
  "ftPerSec": "須_Feet / second_____鷗",
  "ftPerHour": "須_Feet / hour____鷗",
  "kmPerSec": "須_Kilometers / second_______鷗",
  "kmPerHour": "須_Kilometers / hour______鷗",
  "mPerSec": "須_Meters / second______鷗",
  "mPerHour": "須_Meters / hour_____鷗",
  "miPerSec": "須_Miles / second_____鷗",
  "miPerHour": "須_Miles / hour_____鷗",
  "nMPerSec": "須_Nautical Miles / second________鷗",
  "nMPerHour": "須_Nautical Miles / hour_______鷗",
  "settingsTitle": "須_Settings___鷗",
  "labelSettingsLabel": "須_Label Settings_____鷗",
  "labelSettingsButtonLabel": "須_Configure Label Settings________鷗",
  "gridSettingsLabel": "須_Grid Settings_____鷗",
  "gridSettingsButtonLabel": "須_Configure Grid Settings________鷗",
  "transparency": "須_Transparency_____鷗",
  "labelStyle": "須_Label Style____鷗",
  "font": "須_Font__鷗",
  "textSize": "須_Text Size____鷗",
  "textColor": "須_Text Color____鷗",
  "halo": "須_Halo__鷗",
  "show": "須_Show__鷗",
  "lockSettings": "須_Settings have been locked by the application owner________________鷗",
  "gridSettings": {
    "cellShape": "須_Cell Shape____鷗",
    "cellUnits": "須_Cell Units____鷗",
    "cellOutline": "須_Cell Outline Settings_______鷗",
    "cellFill": "須_Cell Fill Settings______鷗",
    "gridReferenceSystem": "須_Reference System______鷗",
    "gridDatum": "須_Datum: WGS84_____鷗",
    "labelStartPosition": "須_Label Origin_____鷗",
    "labelType": "須_Label Type____鷗",
    "labelDirection": "須_Label Direction______鷗",
    "gridOrigin": "須_Grid Origin____鷗",
    "default": "須_Rectangle____鷗",
    "hexagon": "須_Hexagon___鷗",
    "miles": "須_Miles___鷗",
    "kilometers": "須_Kilometers____鷗",
    "feet": "須_Feet__鷗",
    "meters": "須_Meters___鷗",
    "yards": "須_Yards___鷗",
    "nautical-miles": "須_Nautical Miles_____鷗",
    "lowerLeft": "須_Lower-Left____鷗",
    "lowerRight": "須_Lower-Right____鷗",
    "upperLeft": "須_Upper-Left____鷗",
    "upperRight": "須_Upper-Right____鷗",
    "center": "須_Center___鷗",
    "alphaNumeric": "須_Alpha-Numeric_____鷗",
    "alphaAlpha": "須_Alpha-Alpha____鷗",
    "numeric": "須_Numeric___鷗",
    "horizontal": "須_Horizontal____鷗",
    "vertical": "須_Vertical___鷗",
    "MGRS": "須_MGRS__鷗",
    "USNG": "須_USNG__鷗",
    "showLabels": "須_Show Labels____鷗"
  },
  "publishTitle": "須_Publish GRG to Portal_______鷗",
  "publishGRGBtn": "須_Publish___鷗",
  "GRGLayerName": "須_Published GRG Layer Name________鷗",
  "invalidGRGLayerName": "須_Layer name must only contain alpha-numeric characters and underscores______________________鷗",
  "missingGRGLayerName": "須_You must enter a name for the GRG___________鷗",
  "publishingFailedLayerExists": "須_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________鷗.",
  "checkService": "須_Check Service: {0}______鷗",
  "createService": "須_Create Service: {0}_______鷗",
  "unableToCreate": "須_Unable to create: {0}_______鷗",
  "addToDefinition": "須_Add to definition: {0}________鷗",
  "successfullyPublished": "須_Successfully published web layer{0}Manage the web layer__________________鷗",
  "userRole": "須_Unable to create service because user does not have permissions____________________鷗",
  "createGRGBtn": "須_Create GRG____鷗",
  "clearGRGBtn": "須_Clear___鷗",
  "labelFormat": "須_Label Format_____鷗",
  "helpIconTooltip": "須_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________鷗",
  "addPointToolTip": "須_Add GRG Origin_____鷗",
  "cellWidth": "須_Cell Width (x)_____鷗",
  "cellHeight": "須_Cell Height (y)______鷗",
  "invalidNumberMessage": "須_The value entered is not valid__________鷗",
  "invalidRangeMessage": "須_Value must be greater than 0_________鷗",
  "gridAngleInvalidRangeMessage": "須_Value must be between -89.9 and 89.9____________鷗",
  "formatIconTooltip": "須_Format Input_____鷗",
  "coordInputLabel": "須_GRG Origin (DD)______鷗",
  "setCoordFormat": "須_Set Coordinate Format String_________鷗",
  "prefixNumbers": "須_Add '+/-' prefix to positive and negative numbers________________鷗",
  "cancelBtn": "須_Cancel___鷗",
  "applyBtn": "須_Apply___鷗",
  "comfirmInputNotation": "須_Confirm Input Notation________鷗",
  "notationsMatch": "須_notations match your input please confirm which you would like to use______________________鷗:",
  "numberOfCellsHorizontal": "須_# Horizontal Cells______鷗",
  "numberOfCellsVertical": "須_# Vertical Cells______鷗",
  "gridAngle": "須_Grid Rotation_____鷗",
  "tooManyCellsErrorMessage": "須_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________鷗.",
  "missingParametersMessage": "須_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________鷗",
  "missingOriginParametersMessage": "須_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________鷗",
  "invalidWidthHeightParametersMessage": "須_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________鷗",
  "invalidHorizontalVerticalParametersMessage": "須_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________鷗",
  "drawPointToolTip": "須_Click to add GRG origin point__________鷗",
  "missingLayerNameMessage": "須_You must enter a valid layer name before you can publish__________________鷗",
  "parseCoordinatesError": "須_Unable to parse coordinates. Please check your input_________________鷗.",
  "grgPolarRegionError": "須_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________鷗.",
  "grgPolarOriginError": "須_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________鷗.",
  "DD": "須_DD__鷗",
  "DDM": "須_DDM__鷗",
  "DMS": "須_DMS__鷗",
  "DDRev": "須_DDRev___鷗",
  "DDMRev": "須_DDMRev___鷗",
  "DMSRev": "須_DMSRev___鷗",
  "USNG": "須_USNG__鷗",
  "MGRS": "須_MGRS__鷗",
  "UTM_H": "須_UTM (H)___鷗",
  "UTM": "須_UTM__鷗",
  "GARS": "須_GARS__鷗",
  "GEOREF": "須_GEOREF___鷗",
  "DDLatLongNotation": "須_Decimal Degrees - Latitude/Longitude____________鷗",
  "DDLongLatNotation": "須_Decimal Degrees  - Longitude/Latitude____________鷗",
  "DDMLatLongNotation": "須_Degrees Decimal Minutes - Latitude/Longitude______________鷗",
  "DDMLongLatNotation": "須_Degrees Decimal Minutes - Longitude/Latitude______________鷗",
  "DMSLatLongNotation": "須_Degrees Minutes Seconds - Latitude/Longitude______________鷗",
  "DMSLongLatNotation": "須_Degrees Minutes Seconds - Longitude/Latitude______________鷗",
  "GARSNotation": "須_GARS__鷗",
  "GEOREFNotation": "須_GEOREF___鷗",
  "MGRSNotation": "須_MGRS__鷗",
  "USNGNotation": "須_USNG__鷗",
  "UTMBandNotation": "須_UTM - Band Letter______鷗",
  "UTMHemNotation": "須_UTM - Hemisphere (N/S)________鷗"
});