define({
  "gridTabLabel": "須_Grid__鷗",
  "labelTabLabel": "須_Labels___鷗",
  "referenceSystemTabLabel": "須_Reference System______鷗",
  "gridTabDescription": "須_Set the appearance and behavior of the grid cells________________鷗.",
  "cellOutlineColor": "須_Cell Outine color______鷗",
  "cellFillColor": "須_Cell Fill color______鷗",
  "transparency": "須_Transparency_____鷗",
  "cellShapeDropDown": "須_Cell Shape____鷗",
  "default": "須_Rectangle____鷗",
  "hexagon": "須_Hexagon___鷗",
  "cellUnitsDropDown": "須_Cell Units____鷗",
  "miles": "須_Miles___鷗",
  "kilometers": "須_Kilometers____鷗",
  "feet": "須_Feet__鷗",
  "meters": "須_Meters___鷗",
  "yards": "須_Yards___鷗",
  "nautical-miles": "須_Nautical Miles_____鷗",
  "gridOriginDropDown": "須_Grid Origin____鷗",
  "lowerLeft": "須_Lower-Left____鷗",
  "lowerRight": "須_Lower-Right____鷗",
  "upperLeft": "須_Upper-Left____鷗",
  "upperRight": "須_Upper-Right____鷗",
  "center": "須_Center___鷗",
  "labelTabDescription": "須_Set the appearance and behavior of the grid labels________________鷗.",
  "labelSettings": "須_Label Style____鷗",
  "font": "須_Font__鷗",
  "textSize": "須_Text Size____鷗",
  "textColor": "須_Text Color____鷗",
  "halo": "須_Halo__鷗",
  "show": "須_Show__鷗",
  "labelTypeDropDown": "須_Label Type____鷗",
  "alphaNumeric": "須_Alpha-Numeric_____鷗",
  "alphaAlpha": "須_Alpha-Alpha____鷗",
  "numeric": "須_Numeric___鷗",
  "labelDirectionDropDown": "須_Label Direction______鷗",
  "horizontal": "須_Horizontal____鷗",
  "vertical": "須_Vertical___鷗",
  "labelOriginDropDown": "須_Label Origin_____鷗",
  "referenceSystemlTabDescription": "須_Set the default reference system___________鷗.",
  "MGRS": "須_MGRS__鷗",
  "USNG": "須_USNG__鷗",
  "lockSettings": "須_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________鷗"
});