define({
  "_widgetLabel": "Į_Gridded Reference Graphic_________š",
  "newGRGFromAreaButtonLabel": "Į_Define a Grid from an Area_________š",
  "newGRGFromPointButtonLabel": "Į_Define a Grid from a Point_________š",
  "newGRGFromAreaTitle": "Į_Define a Grid from an Area_________š",
  "newGRGFromPointTitle": "Į_Define a Grid from a Point_________š",
  "newGRGBySizeButtonLabel": "Į_By Dimension_____š",
  "newGRGFromRefSystemButtonLabel": "Į_By Reference System_______š",
  "newGRGByTimeLabel": "Į_By Time and Speed______š",
  "newGRGFromNonStandardButtonLabel": "Į_Define Non-Standard Grid________š",
  "newGRGAreaBySizeTitle": "Į_GRG from an Area by Dimension__________š",
  "newGRGAreaBySizeDefineAreaLabel": "Į_GRG Area___š",
  "addGRGAreaPolygonToolTip": "Į_Draw GRG Area using polygon_________š",
  "addGRGAreaExtentToolTip": "Į_Draw GRG Area using extent_________š",
  "rotation": "Į_Grid Rotation_____š",
  "numberRowsColumnsLabel": "Į_Define number of rows and columns___________š",
  "newGRGAreaByRefSystemTitle": "Į_GRG from an Area by Reference System____________š",
  "gridSize": "Į_Grid Size____š",
  "UTMZoneandBand": "Į_Grid Zone____š",
  "100000m": "Į_100000 meter_____š",
  "10000m": "Į_10000 meter____š",
  "1000m": "Į_1000 meter____š",
  "100m": "Į_100 meter____š",
  "10m": "Į_10 meter___š",
  "clipGrid": "Į_Clip Grid to GRG Area_______š",
  "newGRGAreaFromNonStandardTitle": "Į_New NRG___š",
  "newGRGPointBySizeTitle": "Į_GRG from Point by Dimension_________š",
  "newGRGPointByRefSystemTitle": "Į_GRG from Point by Reference System___________š",
  "newGRGPointByTimeTitle": "Į_GRG from Point using Time and Speed____________š",
  "time": "Į_Time__š",
  "rate": "Į_Speed___š",
  "hours": "Į_Hours___š",
  "minutes": "Į_Minutes___š",
  "seconds": "Į_Seconds___š",
  "ftPerSec": "Į_Feet / second_____š",
  "ftPerHour": "Į_Feet / hour____š",
  "kmPerSec": "Į_Kilometers / second_______š",
  "kmPerHour": "Į_Kilometers / hour______š",
  "mPerSec": "Į_Meters / second______š",
  "mPerHour": "Į_Meters / hour_____š",
  "miPerSec": "Į_Miles / second_____š",
  "miPerHour": "Į_Miles / hour_____š",
  "nMPerSec": "Į_Nautical Miles / second________š",
  "nMPerHour": "Į_Nautical Miles / hour_______š",
  "settingsTitle": "Į_Settings___š",
  "labelSettingsLabel": "Į_Label Settings_____š",
  "labelSettingsButtonLabel": "Į_Configure Label Settings________š",
  "gridSettingsLabel": "Į_Grid Settings_____š",
  "gridSettingsButtonLabel": "Į_Configure Grid Settings________š",
  "transparency": "Į_Transparency_____š",
  "labelStyle": "Į_Label Style____š",
  "font": "Į_Font__š",
  "textSize": "Į_Text Size____š",
  "textColor": "Į_Text Color____š",
  "halo": "Į_Halo__š",
  "show": "Į_Show__š",
  "lockSettings": "Į_Settings have been locked by the application owner________________š",
  "gridSettings": {
    "cellShape": "Į_Cell Shape____š",
    "cellUnits": "Į_Cell Units____š",
    "cellOutline": "Į_Cell Outline Settings_______š",
    "cellFill": "Į_Cell Fill Settings______š",
    "gridReferenceSystem": "Į_Reference System______š",
    "gridDatum": "Į_Datum: WGS84_____š",
    "labelStartPosition": "Į_Label Origin_____š",
    "labelType": "Į_Label Type____š",
    "labelDirection": "Į_Label Direction______š",
    "gridOrigin": "Į_Grid Origin____š",
    "default": "Į_Rectangle____š",
    "hexagon": "Į_Hexagon___š",
    "miles": "Į_Miles___š",
    "kilometers": "Į_Kilometers____š",
    "feet": "Į_Feet__š",
    "meters": "Į_Meters___š",
    "yards": "Į_Yards___š",
    "nautical-miles": "Į_Nautical Miles_____š",
    "lowerLeft": "Į_Lower-Left____š",
    "lowerRight": "Į_Lower-Right____š",
    "upperLeft": "Į_Upper-Left____š",
    "upperRight": "Į_Upper-Right____š",
    "center": "Į_Center___š",
    "alphaNumeric": "Į_Alpha-Numeric_____š",
    "alphaAlpha": "Į_Alpha-Alpha____š",
    "numeric": "Į_Numeric___š",
    "horizontal": "Į_Horizontal____š",
    "vertical": "Į_Vertical___š",
    "MGRS": "Į_MGRS__š",
    "USNG": "Į_USNG__š",
    "showLabels": "Į_Show Labels____š"
  },
  "publishTitle": "Į_Publish GRG to Portal_______š",
  "publishGRGBtn": "Į_Publish___š",
  "GRGLayerName": "Į_Published GRG Layer Name________š",
  "invalidGRGLayerName": "Į_Layer name must only contain alpha-numeric characters and underscores______________________š",
  "missingGRGLayerName": "Į_You must enter a name for the GRG___________š",
  "publishingFailedLayerExists": "Į_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________š.",
  "checkService": "Į_Check Service: {0}______š",
  "createService": "Į_Create Service: {0}_______š",
  "unableToCreate": "Į_Unable to create: {0}_______š",
  "addToDefinition": "Į_Add to definition: {0}________š",
  "successfullyPublished": "Į_Successfully published web layer{0}Manage the web layer__________________š",
  "userRole": "Į_Unable to create service because user does not have permissions____________________š",
  "createGRGBtn": "Į_Create GRG____š",
  "clearGRGBtn": "Į_Clear___š",
  "labelFormat": "Į_Label Format_____š",
  "helpIconTooltip": "Į_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________š",
  "addPointToolTip": "Į_Add GRG Origin_____š",
  "cellWidth": "Į_Cell Width (x)_____š",
  "cellHeight": "Į_Cell Height (y)______š",
  "invalidNumberMessage": "Į_The value entered is not valid__________š",
  "invalidRangeMessage": "Į_Value must be greater than 0_________š",
  "gridAngleInvalidRangeMessage": "Į_Value must be between -89.9 and 89.9____________š",
  "formatIconTooltip": "Į_Format Input_____š",
  "coordInputLabel": "Į_GRG Origin (DD)______š",
  "setCoordFormat": "Į_Set Coordinate Format String_________š",
  "prefixNumbers": "Į_Add '+/-' prefix to positive and negative numbers________________š",
  "cancelBtn": "Į_Cancel___š",
  "applyBtn": "Į_Apply___š",
  "comfirmInputNotation": "Į_Confirm Input Notation________š",
  "notationsMatch": "Į_notations match your input please confirm which you would like to use______________________š:",
  "numberOfCellsHorizontal": "Į_# Horizontal Cells______š",
  "numberOfCellsVertical": "Į_# Vertical Cells______š",
  "gridAngle": "Į_Grid Rotation_____š",
  "tooManyCellsErrorMessage": "Į_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________š.",
  "missingParametersMessage": "Į_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________š",
  "missingOriginParametersMessage": "Į_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________š",
  "invalidWidthHeightParametersMessage": "Į_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________š",
  "invalidHorizontalVerticalParametersMessage": "Į_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________š",
  "drawPointToolTip": "Į_Click to add GRG origin point__________š",
  "missingLayerNameMessage": "Į_You must enter a valid layer name before you can publish__________________š",
  "parseCoordinatesError": "Į_Unable to parse coordinates. Please check your input_________________š.",
  "grgPolarRegionError": "Į_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________š.",
  "grgPolarOriginError": "Į_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________š.",
  "DD": "Į_DD__š",
  "DDM": "Į_DDM__š",
  "DMS": "Į_DMS__š",
  "DDRev": "Į_DDRev___š",
  "DDMRev": "Į_DDMRev___š",
  "DMSRev": "Į_DMSRev___š",
  "USNG": "Į_USNG__š",
  "MGRS": "Į_MGRS__š",
  "UTM_H": "Į_UTM (H)___š",
  "UTM": "Į_UTM__š",
  "GARS": "Į_GARS__š",
  "GEOREF": "Į_GEOREF___š",
  "DDLatLongNotation": "Į_Decimal Degrees - Latitude/Longitude____________š",
  "DDLongLatNotation": "Į_Decimal Degrees  - Longitude/Latitude____________š",
  "DDMLatLongNotation": "Į_Degrees Decimal Minutes - Latitude/Longitude______________š",
  "DDMLongLatNotation": "Į_Degrees Decimal Minutes - Longitude/Latitude______________š",
  "DMSLatLongNotation": "Į_Degrees Minutes Seconds - Latitude/Longitude______________š",
  "DMSLongLatNotation": "Į_Degrees Minutes Seconds - Longitude/Latitude______________š",
  "GARSNotation": "Į_GARS__š",
  "GEOREFNotation": "Į_GEOREF___š",
  "MGRSNotation": "Į_MGRS__š",
  "USNGNotation": "Į_USNG__š",
  "UTMBandNotation": "Į_UTM - Band Letter______š",
  "UTMHemNotation": "Į_UTM - Hemisphere (N/S)________š"
});