define({
  "gridTabLabel": "试_Grid__验",
  "labelTabLabel": "试_Labels___验",
  "referenceSystemTabLabel": "试_Reference System______验",
  "gridTabDescription": "试_Set the appearance and behavior of the grid cells________________验.",
  "cellOutlineColor": "试_Cell Outine color______验",
  "cellFillColor": "试_Cell Fill color______验",
  "transparency": "试_Transparency_____验",
  "cellShapeDropDown": "试_Cell Shape____验",
  "default": "试_Rectangle____验",
  "hexagon": "试_Hexagon___验",
  "cellUnitsDropDown": "试_Cell Units____验",
  "miles": "试_Miles___验",
  "kilometers": "试_Kilometers____验",
  "feet": "试_Feet__验",
  "meters": "试_Meters___验",
  "yards": "试_Yards___验",
  "nautical-miles": "试_Nautical Miles_____验",
  "gridOriginDropDown": "试_Grid Origin____验",
  "lowerLeft": "试_Lower-Left____验",
  "lowerRight": "试_Lower-Right____验",
  "upperLeft": "试_Upper-Left____验",
  "upperRight": "试_Upper-Right____验",
  "center": "试_Center___验",
  "labelTabDescription": "试_Set the appearance and behavior of the grid labels________________验.",
  "labelSettings": "试_Label Style____验",
  "font": "试_Font__验",
  "textSize": "试_Text Size____验",
  "textColor": "试_Text Color____验",
  "halo": "试_Halo__验",
  "show": "试_Show__验",
  "labelTypeDropDown": "试_Label Type____验",
  "alphaNumeric": "试_Alpha-Numeric_____验",
  "alphaAlpha": "试_Alpha-Alpha____验",
  "numeric": "试_Numeric___验",
  "labelDirectionDropDown": "试_Label Direction______验",
  "horizontal": "试_Horizontal____验",
  "vertical": "试_Vertical___验",
  "labelOriginDropDown": "试_Label Origin_____验",
  "referenceSystemlTabDescription": "试_Set the default reference system___________验.",
  "MGRS": "试_MGRS__验",
  "USNG": "试_USNG__验",
  "lockSettings": "试_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________验"
});