define({
  "_widgetLabel": "ø_Gridded Reference Graphic_________å",
  "newGRGFromAreaButtonLabel": "ø_Define a Grid from an Area_________å",
  "newGRGFromPointButtonLabel": "ø_Define a Grid from a Point_________å",
  "newGRGFromAreaTitle": "ø_Define a Grid from an Area_________å",
  "newGRGFromPointTitle": "ø_Define a Grid from a Point_________å",
  "newGRGBySizeButtonLabel": "ø_By Dimension_____å",
  "newGRGFromRefSystemButtonLabel": "ø_By Reference System_______å",
  "newGRGByTimeLabel": "ø_By Time and Speed______å",
  "newGRGFromNonStandardButtonLabel": "ø_Define Non-Standard Grid________å",
  "newGRGAreaBySizeTitle": "ø_GRG from an Area by Dimension__________å",
  "newGRGAreaBySizeDefineAreaLabel": "ø_GRG Area___å",
  "addGRGAreaPolygonToolTip": "ø_Draw GRG Area using polygon_________å",
  "addGRGAreaExtentToolTip": "ø_Draw GRG Area using extent_________å",
  "rotation": "ø_Grid Rotation_____å",
  "numberRowsColumnsLabel": "ø_Define number of rows and columns___________å",
  "newGRGAreaByRefSystemTitle": "ø_GRG from an Area by Reference System____________å",
  "gridSize": "ø_Grid Size____å",
  "UTMZoneandBand": "ø_Grid Zone____å",
  "100000m": "ø_100000 meter_____å",
  "10000m": "ø_10000 meter____å",
  "1000m": "ø_1000 meter____å",
  "100m": "ø_100 meter____å",
  "10m": "ø_10 meter___å",
  "clipGrid": "ø_Clip Grid to GRG Area_______å",
  "newGRGAreaFromNonStandardTitle": "ø_New NRG___å",
  "newGRGPointBySizeTitle": "ø_GRG from Point by Dimension_________å",
  "newGRGPointByRefSystemTitle": "ø_GRG from Point by Reference System___________å",
  "newGRGPointByTimeTitle": "ø_GRG from Point using Time and Speed____________å",
  "time": "ø_Time__å",
  "rate": "ø_Speed___å",
  "hours": "ø_Hours___å",
  "minutes": "ø_Minutes___å",
  "seconds": "ø_Seconds___å",
  "ftPerSec": "ø_Feet / second_____å",
  "ftPerHour": "ø_Feet / hour____å",
  "kmPerSec": "ø_Kilometers / second_______å",
  "kmPerHour": "ø_Kilometers / hour______å",
  "mPerSec": "ø_Meters / second______å",
  "mPerHour": "ø_Meters / hour_____å",
  "miPerSec": "ø_Miles / second_____å",
  "miPerHour": "ø_Miles / hour_____å",
  "nMPerSec": "ø_Nautical Miles / second________å",
  "nMPerHour": "ø_Nautical Miles / hour_______å",
  "settingsTitle": "ø_Settings___å",
  "labelSettingsLabel": "ø_Label Settings_____å",
  "labelSettingsButtonLabel": "ø_Configure Label Settings________å",
  "gridSettingsLabel": "ø_Grid Settings_____å",
  "gridSettingsButtonLabel": "ø_Configure Grid Settings________å",
  "transparency": "ø_Transparency_____å",
  "labelStyle": "ø_Label Style____å",
  "font": "ø_Font__å",
  "textSize": "ø_Text Size____å",
  "textColor": "ø_Text Color____å",
  "halo": "ø_Halo__å",
  "show": "ø_Show__å",
  "lockSettings": "ø_Settings have been locked by the application owner________________å",
  "gridSettings": {
    "cellShape": "ø_Cell Shape____å",
    "cellUnits": "ø_Cell Units____å",
    "cellOutline": "ø_Cell Outline Settings_______å",
    "cellFill": "ø_Cell Fill Settings______å",
    "gridReferenceSystem": "ø_Reference System______å",
    "gridDatum": "ø_Datum: WGS84_____å",
    "labelStartPosition": "ø_Label Origin_____å",
    "labelType": "ø_Label Type____å",
    "labelDirection": "ø_Label Direction______å",
    "gridOrigin": "ø_Grid Origin____å",
    "default": "ø_Rectangle____å",
    "hexagon": "ø_Hexagon___å",
    "miles": "ø_Miles___å",
    "kilometers": "ø_Kilometers____å",
    "feet": "ø_Feet__å",
    "meters": "ø_Meters___å",
    "yards": "ø_Yards___å",
    "nautical-miles": "ø_Nautical Miles_____å",
    "lowerLeft": "ø_Lower-Left____å",
    "lowerRight": "ø_Lower-Right____å",
    "upperLeft": "ø_Upper-Left____å",
    "upperRight": "ø_Upper-Right____å",
    "center": "ø_Center___å",
    "alphaNumeric": "ø_Alpha-Numeric_____å",
    "alphaAlpha": "ø_Alpha-Alpha____å",
    "numeric": "ø_Numeric___å",
    "horizontal": "ø_Horizontal____å",
    "vertical": "ø_Vertical___å",
    "MGRS": "ø_MGRS__å",
    "USNG": "ø_USNG__å",
    "showLabels": "ø_Show Labels____å"
  },
  "publishTitle": "ø_Publish GRG to Portal_______å",
  "publishGRGBtn": "ø_Publish___å",
  "GRGLayerName": "ø_Published GRG Layer Name________å",
  "invalidGRGLayerName": "ø_Layer name must only contain alpha-numeric characters and underscores______________________å",
  "missingGRGLayerName": "ø_You must enter a name for the GRG___________å",
  "publishingFailedLayerExists": "ø_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________å.",
  "checkService": "ø_Check Service: {0}______å",
  "createService": "ø_Create Service: {0}_______å",
  "unableToCreate": "ø_Unable to create: {0}_______å",
  "addToDefinition": "ø_Add to definition: {0}________å",
  "successfullyPublished": "ø_Successfully published web layer{0}Manage the web layer__________________å",
  "userRole": "ø_Unable to create service because user does not have permissions____________________å",
  "createGRGBtn": "ø_Create GRG____å",
  "clearGRGBtn": "ø_Clear___å",
  "labelFormat": "ø_Label Format_____å",
  "helpIconTooltip": "ø_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________å",
  "addPointToolTip": "ø_Add GRG Origin_____å",
  "cellWidth": "ø_Cell Width (x)_____å",
  "cellHeight": "ø_Cell Height (y)______å",
  "invalidNumberMessage": "ø_The value entered is not valid__________å",
  "invalidRangeMessage": "ø_Value must be greater than 0_________å",
  "gridAngleInvalidRangeMessage": "ø_Value must be between -89.9 and 89.9____________å",
  "formatIconTooltip": "ø_Format Input_____å",
  "coordInputLabel": "ø_GRG Origin (DD)______å",
  "setCoordFormat": "ø_Set Coordinate Format String_________å",
  "prefixNumbers": "ø_Add '+/-' prefix to positive and negative numbers________________å",
  "cancelBtn": "ø_Cancel___å",
  "applyBtn": "ø_Apply___å",
  "comfirmInputNotation": "ø_Confirm Input Notation________å",
  "notationsMatch": "ø_notations match your input please confirm which you would like to use______________________å:",
  "numberOfCellsHorizontal": "ø_# Horizontal Cells______å",
  "numberOfCellsVertical": "ø_# Vertical Cells______å",
  "gridAngle": "ø_Grid Rotation_____å",
  "tooManyCellsErrorMessage": "ø_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________å.",
  "missingParametersMessage": "ø_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________å",
  "missingOriginParametersMessage": "ø_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________å",
  "invalidWidthHeightParametersMessage": "ø_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________å",
  "invalidHorizontalVerticalParametersMessage": "ø_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________å",
  "drawPointToolTip": "ø_Click to add GRG origin point__________å",
  "missingLayerNameMessage": "ø_You must enter a valid layer name before you can publish__________________å",
  "parseCoordinatesError": "ø_Unable to parse coordinates. Please check your input_________________å.",
  "grgPolarRegionError": "ø_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________å.",
  "grgPolarOriginError": "ø_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________å.",
  "DD": "ø_DD__å",
  "DDM": "ø_DDM__å",
  "DMS": "ø_DMS__å",
  "DDRev": "ø_DDRev___å",
  "DDMRev": "ø_DDMRev___å",
  "DMSRev": "ø_DMSRev___å",
  "USNG": "ø_USNG__å",
  "MGRS": "ø_MGRS__å",
  "UTM_H": "ø_UTM (H)___å",
  "UTM": "ø_UTM__å",
  "GARS": "ø_GARS__å",
  "GEOREF": "ø_GEOREF___å",
  "DDLatLongNotation": "ø_Decimal Degrees - Latitude/Longitude____________å",
  "DDLongLatNotation": "ø_Decimal Degrees  - Longitude/Latitude____________å",
  "DDMLatLongNotation": "ø_Degrees Decimal Minutes - Latitude/Longitude______________å",
  "DDMLongLatNotation": "ø_Degrees Decimal Minutes - Longitude/Latitude______________å",
  "DMSLatLongNotation": "ø_Degrees Minutes Seconds - Latitude/Longitude______________å",
  "DMSLongLatNotation": "ø_Degrees Minutes Seconds - Longitude/Latitude______________å",
  "GARSNotation": "ø_GARS__å",
  "GEOREFNotation": "ø_GEOREF___å",
  "MGRSNotation": "ø_MGRS__å",
  "USNGNotation": "ø_USNG__å",
  "UTMBandNotation": "ø_UTM - Band Letter______å",
  "UTMHemNotation": "ø_UTM - Hemisphere (N/S)________å"
});