define({
  "_widgetLabel": "試_Gridded Reference Graphic_________驗",
  "newGRGFromAreaButtonLabel": "試_Define a Grid from an Area_________驗",
  "newGRGFromPointButtonLabel": "試_Define a Grid from a Point_________驗",
  "newGRGFromAreaTitle": "試_Define a Grid from an Area_________驗",
  "newGRGFromPointTitle": "試_Define a Grid from a Point_________驗",
  "newGRGBySizeButtonLabel": "試_By Dimension_____驗",
  "newGRGFromRefSystemButtonLabel": "試_By Reference System_______驗",
  "newGRGByTimeLabel": "試_By Time and Speed______驗",
  "newGRGFromNonStandardButtonLabel": "試_Define Non-Standard Grid________驗",
  "newGRGAreaBySizeTitle": "試_GRG from an Area by Dimension__________驗",
  "newGRGAreaBySizeDefineAreaLabel": "試_GRG Area___驗",
  "addGRGAreaPolygonToolTip": "試_Draw GRG Area using polygon_________驗",
  "addGRGAreaExtentToolTip": "試_Draw GRG Area using extent_________驗",
  "rotation": "試_Grid Rotation_____驗",
  "numberRowsColumnsLabel": "試_Define number of rows and columns___________驗",
  "newGRGAreaByRefSystemTitle": "試_GRG from an Area by Reference System____________驗",
  "gridSize": "試_Grid Size____驗",
  "UTMZoneandBand": "試_Grid Zone____驗",
  "100000m": "試_100000 meter_____驗",
  "10000m": "試_10000 meter____驗",
  "1000m": "試_1000 meter____驗",
  "100m": "試_100 meter____驗",
  "10m": "試_10 meter___驗",
  "clipGrid": "試_Clip Grid to GRG Area_______驗",
  "newGRGAreaFromNonStandardTitle": "試_New NRG___驗",
  "newGRGPointBySizeTitle": "試_GRG from Point by Dimension_________驗",
  "newGRGPointByRefSystemTitle": "試_GRG from Point by Reference System___________驗",
  "newGRGPointByTimeTitle": "試_GRG from Point using Time and Speed____________驗",
  "time": "試_Time__驗",
  "rate": "試_Speed___驗",
  "hours": "試_Hours___驗",
  "minutes": "試_Minutes___驗",
  "seconds": "試_Seconds___驗",
  "ftPerSec": "試_Feet / second_____驗",
  "ftPerHour": "試_Feet / hour____驗",
  "kmPerSec": "試_Kilometers / second_______驗",
  "kmPerHour": "試_Kilometers / hour______驗",
  "mPerSec": "試_Meters / second______驗",
  "mPerHour": "試_Meters / hour_____驗",
  "miPerSec": "試_Miles / second_____驗",
  "miPerHour": "試_Miles / hour_____驗",
  "nMPerSec": "試_Nautical Miles / second________驗",
  "nMPerHour": "試_Nautical Miles / hour_______驗",
  "settingsTitle": "試_Settings___驗",
  "labelSettingsLabel": "試_Label Settings_____驗",
  "labelSettingsButtonLabel": "試_Configure Label Settings________驗",
  "gridSettingsLabel": "試_Grid Settings_____驗",
  "gridSettingsButtonLabel": "試_Configure Grid Settings________驗",
  "transparency": "試_Transparency_____驗",
  "labelStyle": "試_Label Style____驗",
  "font": "試_Font__驗",
  "textSize": "試_Text Size____驗",
  "textColor": "試_Text Color____驗",
  "halo": "試_Halo__驗",
  "show": "試_Show__驗",
  "lockSettings": "試_Settings have been locked by the application owner________________驗",
  "gridSettings": {
    "cellShape": "試_Cell Shape____驗",
    "cellUnits": "試_Cell Units____驗",
    "cellOutline": "試_Cell Outline Settings_______驗",
    "cellFill": "試_Cell Fill Settings______驗",
    "gridReferenceSystem": "試_Reference System______驗",
    "gridDatum": "試_Datum: WGS84_____驗",
    "labelStartPosition": "試_Label Origin_____驗",
    "labelType": "試_Label Type____驗",
    "labelDirection": "試_Label Direction______驗",
    "gridOrigin": "試_Grid Origin____驗",
    "default": "試_Rectangle____驗",
    "hexagon": "試_Hexagon___驗",
    "miles": "試_Miles___驗",
    "kilometers": "試_Kilometers____驗",
    "feet": "試_Feet__驗",
    "meters": "試_Meters___驗",
    "yards": "試_Yards___驗",
    "nautical-miles": "試_Nautical Miles_____驗",
    "lowerLeft": "試_Lower-Left____驗",
    "lowerRight": "試_Lower-Right____驗",
    "upperLeft": "試_Upper-Left____驗",
    "upperRight": "試_Upper-Right____驗",
    "center": "試_Center___驗",
    "alphaNumeric": "試_Alpha-Numeric_____驗",
    "alphaAlpha": "試_Alpha-Alpha____驗",
    "numeric": "試_Numeric___驗",
    "horizontal": "試_Horizontal____驗",
    "vertical": "試_Vertical___驗",
    "MGRS": "試_MGRS__驗",
    "USNG": "試_USNG__驗",
    "showLabels": "試_Show Labels____驗"
  },
  "publishTitle": "試_Publish GRG to Portal_______驗",
  "publishGRGBtn": "試_Publish___驗",
  "GRGLayerName": "試_Published GRG Layer Name________驗",
  "invalidGRGLayerName": "試_Layer name must only contain alpha-numeric characters and underscores______________________驗",
  "missingGRGLayerName": "試_You must enter a name for the GRG___________驗",
  "publishingFailedLayerExists": "試_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________驗.",
  "checkService": "試_Check Service: {0}______驗",
  "createService": "試_Create Service: {0}_______驗",
  "unableToCreate": "試_Unable to create: {0}_______驗",
  "addToDefinition": "試_Add to definition: {0}________驗",
  "successfullyPublished": "試_Successfully published web layer{0}Manage the web layer__________________驗",
  "userRole": "試_Unable to create service because user does not have permissions____________________驗",
  "createGRGBtn": "試_Create GRG____驗",
  "clearGRGBtn": "試_Clear___驗",
  "labelFormat": "試_Label Format_____驗",
  "helpIconTooltip": "試_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________驗",
  "addPointToolTip": "試_Add GRG Origin_____驗",
  "cellWidth": "試_Cell Width (x)_____驗",
  "cellHeight": "試_Cell Height (y)______驗",
  "invalidNumberMessage": "試_The value entered is not valid__________驗",
  "invalidRangeMessage": "試_Value must be greater than 0_________驗",
  "gridAngleInvalidRangeMessage": "試_Value must be between -89.9 and 89.9____________驗",
  "formatIconTooltip": "試_Format Input_____驗",
  "coordInputLabel": "試_GRG Origin (DD)______驗",
  "setCoordFormat": "試_Set Coordinate Format String_________驗",
  "prefixNumbers": "試_Add '+/-' prefix to positive and negative numbers________________驗",
  "cancelBtn": "試_Cancel___驗",
  "applyBtn": "試_Apply___驗",
  "comfirmInputNotation": "試_Confirm Input Notation________驗",
  "notationsMatch": "試_notations match your input please confirm which you would like to use______________________驗:",
  "numberOfCellsHorizontal": "試_# Horizontal Cells______驗",
  "numberOfCellsVertical": "試_# Vertical Cells______驗",
  "gridAngle": "試_Grid Rotation_____驗",
  "tooManyCellsErrorMessage": "試_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________驗.",
  "missingParametersMessage": "試_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________驗",
  "missingOriginParametersMessage": "試_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________驗",
  "invalidWidthHeightParametersMessage": "試_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________驗",
  "invalidHorizontalVerticalParametersMessage": "試_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________驗",
  "drawPointToolTip": "試_Click to add GRG origin point__________驗",
  "missingLayerNameMessage": "試_You must enter a valid layer name before you can publish__________________驗",
  "parseCoordinatesError": "試_Unable to parse coordinates. Please check your input_________________驗.",
  "grgPolarRegionError": "試_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________驗.",
  "grgPolarOriginError": "試_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________驗.",
  "DD": "試_DD__驗",
  "DDM": "試_DDM__驗",
  "DMS": "試_DMS__驗",
  "DDRev": "試_DDRev___驗",
  "DDMRev": "試_DDMRev___驗",
  "DMSRev": "試_DMSRev___驗",
  "USNG": "試_USNG__驗",
  "MGRS": "試_MGRS__驗",
  "UTM_H": "試_UTM (H)___驗",
  "UTM": "試_UTM__驗",
  "GARS": "試_GARS__驗",
  "GEOREF": "試_GEOREF___驗",
  "DDLatLongNotation": "試_Decimal Degrees - Latitude/Longitude____________驗",
  "DDLongLatNotation": "試_Decimal Degrees  - Longitude/Latitude____________驗",
  "DDMLatLongNotation": "試_Degrees Decimal Minutes - Latitude/Longitude______________驗",
  "DDMLongLatNotation": "試_Degrees Decimal Minutes - Longitude/Latitude______________驗",
  "DMSLatLongNotation": "試_Degrees Minutes Seconds - Latitude/Longitude______________驗",
  "DMSLongLatNotation": "試_Degrees Minutes Seconds - Longitude/Latitude______________驗",
  "GARSNotation": "試_GARS__驗",
  "GEOREFNotation": "試_GEOREF___驗",
  "MGRSNotation": "試_MGRS__驗",
  "USNGNotation": "試_USNG__驗",
  "UTMBandNotation": "試_UTM - Band Letter______驗",
  "UTMHemNotation": "試_UTM - Hemisphere (N/S)________驗"
});