define({
  "gridTabLabel": "بيت_Grid__لاحقة",
  "labelTabLabel": "بيت_Labels___لاحقة",
  "referenceSystemTabLabel": "بيت_Reference System______لاحقة",
  "gridTabDescription": "بيت_Set the appearance and behavior of the grid cells________________لاحقة.",
  "cellOutlineColor": "بيت_Cell Outine color______لاحقة",
  "cellFillColor": "بيت_Cell Fill color______لاحقة",
  "transparency": "بيت_Transparency_____لاحقة",
  "cellShapeDropDown": "بيت_Cell Shape____لاحقة",
  "default": "بيت_Rectangle____لاحقة",
  "hexagon": "بيت_Hexagon___لاحقة",
  "cellUnitsDropDown": "بيت_Cell Units____لاحقة",
  "miles": "بيت_Miles___لاحقة",
  "kilometers": "بيت_Kilometers____لاحقة",
  "feet": "بيت_Feet__لاحقة",
  "meters": "بيت_Meters___لاحقة",
  "yards": "بيت_Yards___لاحقة",
  "nautical-miles": "بيت_Nautical Miles_____لاحقة",
  "gridOriginDropDown": "بيت_Grid Origin____لاحقة",
  "lowerLeft": "بيت_Lower-Left____لاحقة",
  "lowerRight": "بيت_Lower-Right____لاحقة",
  "upperLeft": "بيت_Upper-Left____لاحقة",
  "upperRight": "بيت_Upper-Right____لاحقة",
  "center": "بيت_Center___لاحقة",
  "labelTabDescription": "بيت_Set the appearance and behavior of the grid labels________________لاحقة.",
  "labelSettings": "بيت_Label Style____لاحقة",
  "font": "بيت_Font__لاحقة",
  "textSize": "بيت_Text Size____لاحقة",
  "textColor": "بيت_Text Color____لاحقة",
  "halo": "بيت_Halo__لاحقة",
  "show": "بيت_Show__لاحقة",
  "labelTypeDropDown": "بيت_Label Type____لاحقة",
  "alphaNumeric": "بيت_Alpha-Numeric_____لاحقة",
  "alphaAlpha": "بيت_Alpha-Alpha____لاحقة",
  "numeric": "بيت_Numeric___لاحقة",
  "labelDirectionDropDown": "بيت_Label Direction______لاحقة",
  "horizontal": "بيت_Horizontal____لاحقة",
  "vertical": "بيت_Vertical___لاحقة",
  "labelOriginDropDown": "بيت_Label Origin_____لاحقة",
  "referenceSystemlTabDescription": "بيت_Set the default reference system___________لاحقة.",
  "MGRS": "بيت_MGRS__لاحقة",
  "USNG": "بيت_USNG__لاحقة",
  "lockSettings": "بيت_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________لاحقة"
});