define({
  "_widgetLabel": "ã_Gridded Reference Graphic_________Ç",
  "newGRGFromAreaButtonLabel": "ã_Define a Grid from an Area_________Ç",
  "newGRGFromPointButtonLabel": "ã_Define a Grid from a Point_________Ç",
  "newGRGFromAreaTitle": "ã_Define a Grid from an Area_________Ç",
  "newGRGFromPointTitle": "ã_Define a Grid from a Point_________Ç",
  "newGRGBySizeButtonLabel": "ã_By Dimension_____Ç",
  "newGRGFromRefSystemButtonLabel": "ã_By Reference System_______Ç",
  "newGRGByTimeLabel": "ã_By Time and Speed______Ç",
  "newGRGFromNonStandardButtonLabel": "ã_Define Non-Standard Grid________Ç",
  "newGRGAreaBySizeTitle": "ã_GRG from an Area by Dimension__________Ç",
  "newGRGAreaBySizeDefineAreaLabel": "ã_GRG Area___Ç",
  "addGRGAreaPolygonToolTip": "ã_Draw GRG Area using polygon_________Ç",
  "addGRGAreaExtentToolTip": "ã_Draw GRG Area using extent_________Ç",
  "rotation": "ã_Grid Rotation_____Ç",
  "numberRowsColumnsLabel": "ã_Define number of rows and columns___________Ç",
  "newGRGAreaByRefSystemTitle": "ã_GRG from an Area by Reference System____________Ç",
  "gridSize": "ã_Grid Size____Ç",
  "UTMZoneandBand": "ã_Grid Zone____Ç",
  "100000m": "ã_100000 meter_____Ç",
  "10000m": "ã_10000 meter____Ç",
  "1000m": "ã_1000 meter____Ç",
  "100m": "ã_100 meter____Ç",
  "10m": "ã_10 meter___Ç",
  "clipGrid": "ã_Clip Grid to GRG Area_______Ç",
  "newGRGAreaFromNonStandardTitle": "ã_New NRG___Ç",
  "newGRGPointBySizeTitle": "ã_GRG from Point by Dimension_________Ç",
  "newGRGPointByRefSystemTitle": "ã_GRG from Point by Reference System___________Ç",
  "newGRGPointByTimeTitle": "ã_GRG from Point using Time and Speed____________Ç",
  "time": "ã_Time__Ç",
  "rate": "ã_Speed___Ç",
  "hours": "ã_Hours___Ç",
  "minutes": "ã_Minutes___Ç",
  "seconds": "ã_Seconds___Ç",
  "ftPerSec": "ã_Feet / second_____Ç",
  "ftPerHour": "ã_Feet / hour____Ç",
  "kmPerSec": "ã_Kilometers / second_______Ç",
  "kmPerHour": "ã_Kilometers / hour______Ç",
  "mPerSec": "ã_Meters / second______Ç",
  "mPerHour": "ã_Meters / hour_____Ç",
  "miPerSec": "ã_Miles / second_____Ç",
  "miPerHour": "ã_Miles / hour_____Ç",
  "nMPerSec": "ã_Nautical Miles / second________Ç",
  "nMPerHour": "ã_Nautical Miles / hour_______Ç",
  "settingsTitle": "ã_Settings___Ç",
  "labelSettingsLabel": "ã_Label Settings_____Ç",
  "labelSettingsButtonLabel": "ã_Configure Label Settings________Ç",
  "gridSettingsLabel": "ã_Grid Settings_____Ç",
  "gridSettingsButtonLabel": "ã_Configure Grid Settings________Ç",
  "transparency": "ã_Transparency_____Ç",
  "labelStyle": "ã_Label Style____Ç",
  "font": "ã_Font__Ç",
  "textSize": "ã_Text Size____Ç",
  "textColor": "ã_Text Color____Ç",
  "halo": "ã_Halo__Ç",
  "show": "ã_Show__Ç",
  "lockSettings": "ã_Settings have been locked by the application owner________________Ç",
  "gridSettings": {
    "cellShape": "ã_Cell Shape____Ç",
    "cellUnits": "ã_Cell Units____Ç",
    "cellOutline": "ã_Cell Outline Settings_______Ç",
    "cellFill": "ã_Cell Fill Settings______Ç",
    "gridReferenceSystem": "ã_Reference System______Ç",
    "gridDatum": "ã_Datum: WGS84_____Ç",
    "labelStartPosition": "ã_Label Origin_____Ç",
    "labelType": "ã_Label Type____Ç",
    "labelDirection": "ã_Label Direction______Ç",
    "gridOrigin": "ã_Grid Origin____Ç",
    "default": "ã_Rectangle____Ç",
    "hexagon": "ã_Hexagon___Ç",
    "miles": "ã_Miles___Ç",
    "kilometers": "ã_Kilometers____Ç",
    "feet": "ã_Feet__Ç",
    "meters": "ã_Meters___Ç",
    "yards": "ã_Yards___Ç",
    "nautical-miles": "ã_Nautical Miles_____Ç",
    "lowerLeft": "ã_Lower-Left____Ç",
    "lowerRight": "ã_Lower-Right____Ç",
    "upperLeft": "ã_Upper-Left____Ç",
    "upperRight": "ã_Upper-Right____Ç",
    "center": "ã_Center___Ç",
    "alphaNumeric": "ã_Alpha-Numeric_____Ç",
    "alphaAlpha": "ã_Alpha-Alpha____Ç",
    "numeric": "ã_Numeric___Ç",
    "horizontal": "ã_Horizontal____Ç",
    "vertical": "ã_Vertical___Ç",
    "MGRS": "ã_MGRS__Ç",
    "USNG": "ã_USNG__Ç",
    "showLabels": "ã_Show Labels____Ç"
  },
  "publishTitle": "ã_Publish GRG to Portal_______Ç",
  "publishGRGBtn": "ã_Publish___Ç",
  "GRGLayerName": "ã_Published GRG Layer Name________Ç",
  "invalidGRGLayerName": "ã_Layer name must only contain alpha-numeric characters and underscores______________________Ç",
  "missingGRGLayerName": "ã_You must enter a name for the GRG___________Ç",
  "publishingFailedLayerExists": "ã_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________Ç.",
  "checkService": "ã_Check Service: {0}______Ç",
  "createService": "ã_Create Service: {0}_______Ç",
  "unableToCreate": "ã_Unable to create: {0}_______Ç",
  "addToDefinition": "ã_Add to definition: {0}________Ç",
  "successfullyPublished": "ã_Successfully published web layer{0}Manage the web layer__________________Ç",
  "userRole": "ã_Unable to create service because user does not have permissions____________________Ç",
  "createGRGBtn": "ã_Create GRG____Ç",
  "clearGRGBtn": "ã_Clear___Ç",
  "labelFormat": "ã_Label Format_____Ç",
  "helpIconTooltip": "ã_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________Ç",
  "addPointToolTip": "ã_Add GRG Origin_____Ç",
  "cellWidth": "ã_Cell Width (x)_____Ç",
  "cellHeight": "ã_Cell Height (y)______Ç",
  "invalidNumberMessage": "ã_The value entered is not valid__________Ç",
  "invalidRangeMessage": "ã_Value must be greater than 0_________Ç",
  "gridAngleInvalidRangeMessage": "ã_Value must be between -89.9 and 89.9____________Ç",
  "formatIconTooltip": "ã_Format Input_____Ç",
  "coordInputLabel": "ã_GRG Origin (DD)______Ç",
  "setCoordFormat": "ã_Set Coordinate Format String_________Ç",
  "prefixNumbers": "ã_Add '+/-' prefix to positive and negative numbers________________Ç",
  "cancelBtn": "ã_Cancel___Ç",
  "applyBtn": "ã_Apply___Ç",
  "comfirmInputNotation": "ã_Confirm Input Notation________Ç",
  "notationsMatch": "ã_notations match your input please confirm which you would like to use______________________Ç:",
  "numberOfCellsHorizontal": "ã_# Horizontal Cells______Ç",
  "numberOfCellsVertical": "ã_# Vertical Cells______Ç",
  "gridAngle": "ã_Grid Rotation_____Ç",
  "tooManyCellsErrorMessage": "ã_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________Ç.",
  "missingParametersMessage": "ã_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________Ç",
  "missingOriginParametersMessage": "ã_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________Ç",
  "invalidWidthHeightParametersMessage": "ã_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________Ç",
  "invalidHorizontalVerticalParametersMessage": "ã_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________Ç",
  "drawPointToolTip": "ã_Click to add GRG origin point__________Ç",
  "missingLayerNameMessage": "ã_You must enter a valid layer name before you can publish__________________Ç",
  "parseCoordinatesError": "ã_Unable to parse coordinates. Please check your input_________________Ç.",
  "grgPolarRegionError": "ã_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________Ç.",
  "grgPolarOriginError": "ã_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________Ç.",
  "DD": "ã_DD__Ç",
  "DDM": "ã_DDM__Ç",
  "DMS": "ã_DMS__Ç",
  "DDRev": "ã_DDRev___Ç",
  "DDMRev": "ã_DDMRev___Ç",
  "DMSRev": "ã_DMSRev___Ç",
  "USNG": "ã_USNG__Ç",
  "MGRS": "ã_MGRS__Ç",
  "UTM_H": "ã_UTM (H)___Ç",
  "UTM": "ã_UTM__Ç",
  "GARS": "ã_GARS__Ç",
  "GEOREF": "ã_GEOREF___Ç",
  "DDLatLongNotation": "ã_Decimal Degrees - Latitude/Longitude____________Ç",
  "DDLongLatNotation": "ã_Decimal Degrees  - Longitude/Latitude____________Ç",
  "DDMLatLongNotation": "ã_Degrees Decimal Minutes - Latitude/Longitude______________Ç",
  "DDMLongLatNotation": "ã_Degrees Decimal Minutes - Longitude/Latitude______________Ç",
  "DMSLatLongNotation": "ã_Degrees Minutes Seconds - Latitude/Longitude______________Ç",
  "DMSLongLatNotation": "ã_Degrees Minutes Seconds - Longitude/Latitude______________Ç",
  "GARSNotation": "ã_GARS__Ç",
  "GEOREFNotation": "ã_GEOREF___Ç",
  "MGRSNotation": "ã_MGRS__Ç",
  "USNGNotation": "ã_USNG__Ç",
  "UTMBandNotation": "ã_UTM - Band Letter______Ç",
  "UTMHemNotation": "ã_UTM - Hemisphere (N/S)________Ç"
});