define({
  "gridTabLabel": "Č_Grid__ž",
  "labelTabLabel": "Č_Labels___ž",
  "referenceSystemTabLabel": "Č_Reference System______ž",
  "gridTabDescription": "Č_Set the appearance and behavior of the grid cells________________ž.",
  "cellOutlineColor": "Č_Cell Outine color______ž",
  "cellFillColor": "Č_Cell Fill color______ž",
  "transparency": "Č_Transparency_____ž",
  "cellShapeDropDown": "Č_Cell Shape____ž",
  "default": "Č_Rectangle____ž",
  "hexagon": "Č_Hexagon___ž",
  "cellUnitsDropDown": "Č_Cell Units____ž",
  "miles": "Č_Miles___ž",
  "kilometers": "Č_Kilometers____ž",
  "feet": "Č_Feet__ž",
  "meters": "Č_Meters___ž",
  "yards": "Č_Yards___ž",
  "nautical-miles": "Č_Nautical Miles_____ž",
  "gridOriginDropDown": "Č_Grid Origin____ž",
  "lowerLeft": "Č_Lower-Left____ž",
  "lowerRight": "Č_Lower-Right____ž",
  "upperLeft": "Č_Upper-Left____ž",
  "upperRight": "Č_Upper-Right____ž",
  "center": "Č_Center___ž",
  "labelTabDescription": "Č_Set the appearance and behavior of the grid labels________________ž.",
  "labelSettings": "Č_Label Style____ž",
  "font": "Č_Font__ž",
  "textSize": "Č_Text Size____ž",
  "textColor": "Č_Text Color____ž",
  "halo": "Č_Halo__ž",
  "show": "Č_Show__ž",
  "labelTypeDropDown": "Č_Label Type____ž",
  "alphaNumeric": "Č_Alpha-Numeric_____ž",
  "alphaAlpha": "Č_Alpha-Alpha____ž",
  "numeric": "Č_Numeric___ž",
  "labelDirectionDropDown": "Č_Label Direction______ž",
  "horizontal": "Č_Horizontal____ž",
  "vertical": "Č_Vertical___ž",
  "labelOriginDropDown": "Č_Label Origin_____ž",
  "referenceSystemlTabDescription": "Č_Set the default reference system___________ž.",
  "MGRS": "Č_MGRS__ž",
  "USNG": "Č_USNG__ž",
  "lockSettings": "Č_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________ž"
});