define({
  "gridTabLabel": "Ж_Grid__Я",
  "labelTabLabel": "Ж_Labels___Я",
  "referenceSystemTabLabel": "Ж_Reference System______Я",
  "gridTabDescription": "Ж_Set the appearance and behavior of the grid cells________________Я.",
  "cellOutlineColor": "Ж_Cell Outine color______Я",
  "cellFillColor": "Ж_Cell Fill color______Я",
  "transparency": "Ж_Transparency_____Я",
  "cellShapeDropDown": "Ж_Cell Shape____Я",
  "default": "Ж_Rectangle____Я",
  "hexagon": "Ж_Hexagon___Я",
  "cellUnitsDropDown": "Ж_Cell Units____Я",
  "miles": "Ж_Miles___Я",
  "kilometers": "Ж_Kilometers____Я",
  "feet": "Ж_Feet__Я",
  "meters": "Ж_Meters___Я",
  "yards": "Ж_Yards___Я",
  "nautical-miles": "Ж_Nautical Miles_____Я",
  "gridOriginDropDown": "Ж_Grid Origin____Я",
  "lowerLeft": "Ж_Lower-Left____Я",
  "lowerRight": "Ж_Lower-Right____Я",
  "upperLeft": "Ж_Upper-Left____Я",
  "upperRight": "Ж_Upper-Right____Я",
  "center": "Ж_Center___Я",
  "labelTabDescription": "Ж_Set the appearance and behavior of the grid labels________________Я.",
  "labelSettings": "Ж_Label Style____Я",
  "font": "Ж_Font__Я",
  "textSize": "Ж_Text Size____Я",
  "textColor": "Ж_Text Color____Я",
  "halo": "Ж_Halo__Я",
  "show": "Ж_Show__Я",
  "labelTypeDropDown": "Ж_Label Type____Я",
  "alphaNumeric": "Ж_Alpha-Numeric_____Я",
  "alphaAlpha": "Ж_Alpha-Alpha____Я",
  "numeric": "Ж_Numeric___Я",
  "labelDirectionDropDown": "Ж_Label Direction______Я",
  "horizontal": "Ж_Horizontal____Я",
  "vertical": "Ж_Vertical___Я",
  "labelOriginDropDown": "Ж_Label Origin_____Я",
  "referenceSystemlTabDescription": "Ж_Set the default reference system___________Я.",
  "MGRS": "Ж_MGRS__Я",
  "USNG": "Ж_USNG__Я",
  "lockSettings": "Ж_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________Я"
});