define({
  "_widgetLabel": "Š_Gridded Reference Graphic_________ä",
  "newGRGFromAreaButtonLabel": "Š_Define a Grid from an Area_________ä",
  "newGRGFromPointButtonLabel": "Š_Define a Grid from a Point_________ä",
  "newGRGFromAreaTitle": "Š_Define a Grid from an Area_________ä",
  "newGRGFromPointTitle": "Š_Define a Grid from a Point_________ä",
  "newGRGBySizeButtonLabel": "Š_By Dimension_____ä",
  "newGRGFromRefSystemButtonLabel": "Š_By Reference System_______ä",
  "newGRGByTimeLabel": "Š_By Time and Speed______ä",
  "newGRGFromNonStandardButtonLabel": "Š_Define Non-Standard Grid________ä",
  "newGRGAreaBySizeTitle": "Š_GRG from an Area by Dimension__________ä",
  "newGRGAreaBySizeDefineAreaLabel": "Š_GRG Area___ä",
  "addGRGAreaPolygonToolTip": "Š_Draw GRG Area using polygon_________ä",
  "addGRGAreaExtentToolTip": "Š_Draw GRG Area using extent_________ä",
  "rotation": "Š_Grid Rotation_____ä",
  "numberRowsColumnsLabel": "Š_Define number of rows and columns___________ä",
  "newGRGAreaByRefSystemTitle": "Š_GRG from an Area by Reference System____________ä",
  "gridSize": "Š_Grid Size____ä",
  "UTMZoneandBand": "Š_Grid Zone____ä",
  "100000m": "Š_100000 meter_____ä",
  "10000m": "Š_10000 meter____ä",
  "1000m": "Š_1000 meter____ä",
  "100m": "Š_100 meter____ä",
  "10m": "Š_10 meter___ä",
  "clipGrid": "Š_Clip Grid to GRG Area_______ä",
  "newGRGAreaFromNonStandardTitle": "Š_New NRG___ä",
  "newGRGPointBySizeTitle": "Š_GRG from Point by Dimension_________ä",
  "newGRGPointByRefSystemTitle": "Š_GRG from Point by Reference System___________ä",
  "newGRGPointByTimeTitle": "Š_GRG from Point using Time and Speed____________ä",
  "time": "Š_Time__ä",
  "rate": "Š_Speed___ä",
  "hours": "Š_Hours___ä",
  "minutes": "Š_Minutes___ä",
  "seconds": "Š_Seconds___ä",
  "ftPerSec": "Š_Feet / second_____ä",
  "ftPerHour": "Š_Feet / hour____ä",
  "kmPerSec": "Š_Kilometers / second_______ä",
  "kmPerHour": "Š_Kilometers / hour______ä",
  "mPerSec": "Š_Meters / second______ä",
  "mPerHour": "Š_Meters / hour_____ä",
  "miPerSec": "Š_Miles / second_____ä",
  "miPerHour": "Š_Miles / hour_____ä",
  "nMPerSec": "Š_Nautical Miles / second________ä",
  "nMPerHour": "Š_Nautical Miles / hour_______ä",
  "settingsTitle": "Š_Settings___ä",
  "labelSettingsLabel": "Š_Label Settings_____ä",
  "labelSettingsButtonLabel": "Š_Configure Label Settings________ä",
  "gridSettingsLabel": "Š_Grid Settings_____ä",
  "gridSettingsButtonLabel": "Š_Configure Grid Settings________ä",
  "transparency": "Š_Transparency_____ä",
  "labelStyle": "Š_Label Style____ä",
  "font": "Š_Font__ä",
  "textSize": "Š_Text Size____ä",
  "textColor": "Š_Text Color____ä",
  "halo": "Š_Halo__ä",
  "show": "Š_Show__ä",
  "lockSettings": "Š_Settings have been locked by the application owner________________ä",
  "gridSettings": {
    "cellShape": "Š_Cell Shape____ä",
    "cellUnits": "Š_Cell Units____ä",
    "cellOutline": "Š_Cell Outline Settings_______ä",
    "cellFill": "Š_Cell Fill Settings______ä",
    "gridReferenceSystem": "Š_Reference System______ä",
    "gridDatum": "Š_Datum: WGS84_____ä",
    "labelStartPosition": "Š_Label Origin_____ä",
    "labelType": "Š_Label Type____ä",
    "labelDirection": "Š_Label Direction______ä",
    "gridOrigin": "Š_Grid Origin____ä",
    "default": "Š_Rectangle____ä",
    "hexagon": "Š_Hexagon___ä",
    "miles": "Š_Miles___ä",
    "kilometers": "Š_Kilometers____ä",
    "feet": "Š_Feet__ä",
    "meters": "Š_Meters___ä",
    "yards": "Š_Yards___ä",
    "nautical-miles": "Š_Nautical Miles_____ä",
    "lowerLeft": "Š_Lower-Left____ä",
    "lowerRight": "Š_Lower-Right____ä",
    "upperLeft": "Š_Upper-Left____ä",
    "upperRight": "Š_Upper-Right____ä",
    "center": "Š_Center___ä",
    "alphaNumeric": "Š_Alpha-Numeric_____ä",
    "alphaAlpha": "Š_Alpha-Alpha____ä",
    "numeric": "Š_Numeric___ä",
    "horizontal": "Š_Horizontal____ä",
    "vertical": "Š_Vertical___ä",
    "MGRS": "Š_MGRS__ä",
    "USNG": "Š_USNG__ä",
    "showLabels": "Š_Show Labels____ä"
  },
  "publishTitle": "Š_Publish GRG to Portal_______ä",
  "publishGRGBtn": "Š_Publish___ä",
  "GRGLayerName": "Š_Published GRG Layer Name________ä",
  "invalidGRGLayerName": "Š_Layer name must only contain alpha-numeric characters and underscores______________________ä",
  "missingGRGLayerName": "Š_You must enter a name for the GRG___________ä",
  "publishingFailedLayerExists": "Š_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ä.",
  "checkService": "Š_Check Service: {0}______ä",
  "createService": "Š_Create Service: {0}_______ä",
  "unableToCreate": "Š_Unable to create: {0}_______ä",
  "addToDefinition": "Š_Add to definition: {0}________ä",
  "successfullyPublished": "Š_Successfully published web layer{0}Manage the web layer__________________ä",
  "userRole": "Š_Unable to create service because user does not have permissions____________________ä",
  "createGRGBtn": "Š_Create GRG____ä",
  "clearGRGBtn": "Š_Clear___ä",
  "labelFormat": "Š_Label Format_____ä",
  "helpIconTooltip": "Š_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________ä",
  "addPointToolTip": "Š_Add GRG Origin_____ä",
  "cellWidth": "Š_Cell Width (x)_____ä",
  "cellHeight": "Š_Cell Height (y)______ä",
  "invalidNumberMessage": "Š_The value entered is not valid__________ä",
  "invalidRangeMessage": "Š_Value must be greater than 0_________ä",
  "gridAngleInvalidRangeMessage": "Š_Value must be between -89.9 and 89.9____________ä",
  "formatIconTooltip": "Š_Format Input_____ä",
  "coordInputLabel": "Š_GRG Origin (DD)______ä",
  "setCoordFormat": "Š_Set Coordinate Format String_________ä",
  "prefixNumbers": "Š_Add '+/-' prefix to positive and negative numbers________________ä",
  "cancelBtn": "Š_Cancel___ä",
  "applyBtn": "Š_Apply___ä",
  "comfirmInputNotation": "Š_Confirm Input Notation________ä",
  "notationsMatch": "Š_notations match your input please confirm which you would like to use______________________ä:",
  "numberOfCellsHorizontal": "Š_# Horizontal Cells______ä",
  "numberOfCellsVertical": "Š_# Vertical Cells______ä",
  "gridAngle": "Š_Grid Rotation_____ä",
  "tooManyCellsErrorMessage": "Š_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________ä.",
  "missingParametersMessage": "Š_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________ä",
  "missingOriginParametersMessage": "Š_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________ä",
  "invalidWidthHeightParametersMessage": "Š_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________ä",
  "invalidHorizontalVerticalParametersMessage": "Š_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________ä",
  "drawPointToolTip": "Š_Click to add GRG origin point__________ä",
  "missingLayerNameMessage": "Š_You must enter a valid layer name before you can publish__________________ä",
  "parseCoordinatesError": "Š_Unable to parse coordinates. Please check your input_________________ä.",
  "grgPolarRegionError": "Š_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________ä.",
  "grgPolarOriginError": "Š_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________ä.",
  "DD": "Š_DD__ä",
  "DDM": "Š_DDM__ä",
  "DMS": "Š_DMS__ä",
  "DDRev": "Š_DDRev___ä",
  "DDMRev": "Š_DDMRev___ä",
  "DMSRev": "Š_DMSRev___ä",
  "USNG": "Š_USNG__ä",
  "MGRS": "Š_MGRS__ä",
  "UTM_H": "Š_UTM (H)___ä",
  "UTM": "Š_UTM__ä",
  "GARS": "Š_GARS__ä",
  "GEOREF": "Š_GEOREF___ä",
  "DDLatLongNotation": "Š_Decimal Degrees - Latitude/Longitude____________ä",
  "DDLongLatNotation": "Š_Decimal Degrees  - Longitude/Latitude____________ä",
  "DDMLatLongNotation": "Š_Degrees Decimal Minutes - Latitude/Longitude______________ä",
  "DDMLongLatNotation": "Š_Degrees Decimal Minutes - Longitude/Latitude______________ä",
  "DMSLatLongNotation": "Š_Degrees Minutes Seconds - Latitude/Longitude______________ä",
  "DMSLongLatNotation": "Š_Degrees Minutes Seconds - Longitude/Latitude______________ä",
  "GARSNotation": "Š_GARS__ä",
  "GEOREFNotation": "Š_GEOREF___ä",
  "MGRSNotation": "Š_MGRS__ä",
  "USNGNotation": "Š_USNG__ä",
  "UTMBandNotation": "Š_UTM - Band Letter______ä",
  "UTMHemNotation": "Š_UTM - Hemisphere (N/S)________ä"
});