define({
  "gridTabLabel": "आ_Grid__ज",
  "labelTabLabel": "आ_Labels___ज",
  "referenceSystemTabLabel": "आ_Reference System______ज",
  "gridTabDescription": "आ_Set the appearance and behavior of the grid cells________________ज.",
  "cellOutlineColor": "आ_Cell Outine color______ज",
  "cellFillColor": "आ_Cell Fill color______ज",
  "transparency": "आ_Transparency_____ज",
  "cellShapeDropDown": "आ_Cell Shape____ज",
  "default": "आ_Rectangle____ज",
  "hexagon": "आ_Hexagon___ज",
  "cellUnitsDropDown": "आ_Cell Units____ज",
  "miles": "आ_Miles___ज",
  "kilometers": "आ_Kilometers____ज",
  "feet": "आ_Feet__ज",
  "meters": "आ_Meters___ज",
  "yards": "आ_Yards___ज",
  "nautical-miles": "आ_Nautical Miles_____ज",
  "gridOriginDropDown": "आ_Grid Origin____ज",
  "lowerLeft": "आ_Lower-Left____ज",
  "lowerRight": "आ_Lower-Right____ज",
  "upperLeft": "आ_Upper-Left____ज",
  "upperRight": "आ_Upper-Right____ज",
  "center": "आ_Center___ज",
  "labelTabDescription": "आ_Set the appearance and behavior of the grid labels________________ज.",
  "labelSettings": "आ_Label Style____ज",
  "font": "आ_Font__ज",
  "textSize": "आ_Text Size____ज",
  "textColor": "आ_Text Color____ज",
  "halo": "आ_Halo__ज",
  "show": "आ_Show__ज",
  "labelTypeDropDown": "आ_Label Type____ज",
  "alphaNumeric": "आ_Alpha-Numeric_____ज",
  "alphaAlpha": "आ_Alpha-Alpha____ज",
  "numeric": "आ_Numeric___ज",
  "labelDirectionDropDown": "आ_Label Direction______ज",
  "horizontal": "आ_Horizontal____ज",
  "vertical": "आ_Vertical___ज",
  "labelOriginDropDown": "आ_Label Origin_____ज",
  "referenceSystemlTabDescription": "आ_Set the default reference system___________ज.",
  "MGRS": "आ_MGRS__ज",
  "USNG": "आ_USNG__ज",
  "lockSettings": "आ_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________ज"
});