define({
  "gridTabLabel": "한_Grid__빠",
  "labelTabLabel": "한_Labels___빠",
  "referenceSystemTabLabel": "한_Reference System______빠",
  "gridTabDescription": "한_Set the appearance and behavior of the grid cells________________빠.",
  "cellOutlineColor": "한_Cell Outine color______빠",
  "cellFillColor": "한_Cell Fill color______빠",
  "transparency": "한_Transparency_____빠",
  "cellShapeDropDown": "한_Cell Shape____빠",
  "default": "한_Rectangle____빠",
  "hexagon": "한_Hexagon___빠",
  "cellUnitsDropDown": "한_Cell Units____빠",
  "miles": "한_Miles___빠",
  "kilometers": "한_Kilometers____빠",
  "feet": "한_Feet__빠",
  "meters": "한_Meters___빠",
  "yards": "한_Yards___빠",
  "nautical-miles": "한_Nautical Miles_____빠",
  "gridOriginDropDown": "한_Grid Origin____빠",
  "lowerLeft": "한_Lower-Left____빠",
  "lowerRight": "한_Lower-Right____빠",
  "upperLeft": "한_Upper-Left____빠",
  "upperRight": "한_Upper-Right____빠",
  "center": "한_Center___빠",
  "labelTabDescription": "한_Set the appearance and behavior of the grid labels________________빠.",
  "labelSettings": "한_Label Style____빠",
  "font": "한_Font__빠",
  "textSize": "한_Text Size____빠",
  "textColor": "한_Text Color____빠",
  "halo": "한_Halo__빠",
  "show": "한_Show__빠",
  "labelTypeDropDown": "한_Label Type____빠",
  "alphaNumeric": "한_Alpha-Numeric_____빠",
  "alphaAlpha": "한_Alpha-Alpha____빠",
  "numeric": "한_Numeric___빠",
  "labelDirectionDropDown": "한_Label Direction______빠",
  "horizontal": "한_Horizontal____빠",
  "vertical": "한_Vertical___빠",
  "labelOriginDropDown": "한_Label Origin_____빠",
  "referenceSystemlTabDescription": "한_Set the default reference system___________빠.",
  "MGRS": "한_MGRS__빠",
  "USNG": "한_USNG__빠",
  "lockSettings": "한_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________빠"
});