define({
  "_widgetLabel": "æ_Gridded Reference Graphic_________Â",
  "newGRGFromAreaButtonLabel": "æ_Define a Grid from an Area_________Â",
  "newGRGFromPointButtonLabel": "æ_Define a Grid from a Point_________Â",
  "newGRGFromAreaTitle": "æ_Define a Grid from an Area_________Â",
  "newGRGFromPointTitle": "æ_Define a Grid from a Point_________Â",
  "newGRGBySizeButtonLabel": "æ_By Dimension_____Â",
  "newGRGFromRefSystemButtonLabel": "æ_By Reference System_______Â",
  "newGRGByTimeLabel": "æ_By Time and Speed______Â",
  "newGRGFromNonStandardButtonLabel": "æ_Define Non-Standard Grid________Â",
  "newGRGAreaBySizeTitle": "æ_GRG from an Area by Dimension__________Â",
  "newGRGAreaBySizeDefineAreaLabel": "æ_GRG Area___Â",
  "addGRGAreaPolygonToolTip": "æ_Draw GRG Area using polygon_________Â",
  "addGRGAreaExtentToolTip": "æ_Draw GRG Area using extent_________Â",
  "rotation": "æ_Grid Rotation_____Â",
  "numberRowsColumnsLabel": "æ_Define number of rows and columns___________Â",
  "newGRGAreaByRefSystemTitle": "æ_GRG from an Area by Reference System____________Â",
  "gridSize": "æ_Grid Size____Â",
  "UTMZoneandBand": "æ_Grid Zone____Â",
  "100000m": "æ_100000 meter_____Â",
  "10000m": "æ_10000 meter____Â",
  "1000m": "æ_1000 meter____Â",
  "100m": "æ_100 meter____Â",
  "10m": "æ_10 meter___Â",
  "clipGrid": "æ_Clip Grid to GRG Area_______Â",
  "newGRGAreaFromNonStandardTitle": "æ_New NRG___Â",
  "newGRGPointBySizeTitle": "æ_GRG from Point by Dimension_________Â",
  "newGRGPointByRefSystemTitle": "æ_GRG from Point by Reference System___________Â",
  "newGRGPointByTimeTitle": "æ_GRG from Point using Time and Speed____________Â",
  "time": "æ_Time__Â",
  "rate": "æ_Speed___Â",
  "hours": "æ_Hours___Â",
  "minutes": "æ_Minutes___Â",
  "seconds": "æ_Seconds___Â",
  "ftPerSec": "æ_Feet / second_____Â",
  "ftPerHour": "æ_Feet / hour____Â",
  "kmPerSec": "æ_Kilometers / second_______Â",
  "kmPerHour": "æ_Kilometers / hour______Â",
  "mPerSec": "æ_Meters / second______Â",
  "mPerHour": "æ_Meters / hour_____Â",
  "miPerSec": "æ_Miles / second_____Â",
  "miPerHour": "æ_Miles / hour_____Â",
  "nMPerSec": "æ_Nautical Miles / second________Â",
  "nMPerHour": "æ_Nautical Miles / hour_______Â",
  "settingsTitle": "æ_Settings___Â",
  "labelSettingsLabel": "æ_Label Settings_____Â",
  "labelSettingsButtonLabel": "æ_Configure Label Settings________Â",
  "gridSettingsLabel": "æ_Grid Settings_____Â",
  "gridSettingsButtonLabel": "æ_Configure Grid Settings________Â",
  "transparency": "æ_Transparency_____Â",
  "labelStyle": "æ_Label Style____Â",
  "font": "æ_Font__Â",
  "textSize": "æ_Text Size____Â",
  "textColor": "æ_Text Color____Â",
  "halo": "æ_Halo__Â",
  "show": "æ_Show__Â",
  "lockSettings": "æ_Settings have been locked by the application owner________________Â",
  "gridSettings": {
    "cellShape": "æ_Cell Shape____Â",
    "cellUnits": "æ_Cell Units____Â",
    "cellOutline": "æ_Cell Outline Settings_______Â",
    "cellFill": "æ_Cell Fill Settings______Â",
    "gridReferenceSystem": "æ_Reference System______Â",
    "gridDatum": "æ_Datum: WGS84_____Â",
    "labelStartPosition": "æ_Label Origin_____Â",
    "labelType": "æ_Label Type____Â",
    "labelDirection": "æ_Label Direction______Â",
    "gridOrigin": "æ_Grid Origin____Â",
    "default": "æ_Rectangle____Â",
    "hexagon": "æ_Hexagon___Â",
    "miles": "æ_Miles___Â",
    "kilometers": "æ_Kilometers____Â",
    "feet": "æ_Feet__Â",
    "meters": "æ_Meters___Â",
    "yards": "æ_Yards___Â",
    "nautical-miles": "æ_Nautical Miles_____Â",
    "lowerLeft": "æ_Lower-Left____Â",
    "lowerRight": "æ_Lower-Right____Â",
    "upperLeft": "æ_Upper-Left____Â",
    "upperRight": "æ_Upper-Right____Â",
    "center": "æ_Center___Â",
    "alphaNumeric": "æ_Alpha-Numeric_____Â",
    "alphaAlpha": "æ_Alpha-Alpha____Â",
    "numeric": "æ_Numeric___Â",
    "horizontal": "æ_Horizontal____Â",
    "vertical": "æ_Vertical___Â",
    "MGRS": "æ_MGRS__Â",
    "USNG": "æ_USNG__Â",
    "showLabels": "æ_Show Labels____Â"
  },
  "publishTitle": "æ_Publish GRG to Portal_______Â",
  "publishGRGBtn": "æ_Publish___Â",
  "GRGLayerName": "æ_Published GRG Layer Name________Â",
  "invalidGRGLayerName": "æ_Layer name must only contain alpha-numeric characters and underscores______________________Â",
  "missingGRGLayerName": "æ_You must enter a name for the GRG___________Â",
  "publishingFailedLayerExists": "æ_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________Â.",
  "checkService": "æ_Check Service: {0}______Â",
  "createService": "æ_Create Service: {0}_______Â",
  "unableToCreate": "æ_Unable to create: {0}_______Â",
  "addToDefinition": "æ_Add to definition: {0}________Â",
  "successfullyPublished": "æ_Successfully published web layer{0}Manage the web layer__________________Â",
  "userRole": "æ_Unable to create service because user does not have permissions____________________Â",
  "createGRGBtn": "æ_Create GRG____Â",
  "clearGRGBtn": "æ_Clear___Â",
  "labelFormat": "æ_Label Format_____Â",
  "helpIconTooltip": "æ_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________Â",
  "addPointToolTip": "æ_Add GRG Origin_____Â",
  "cellWidth": "æ_Cell Width (x)_____Â",
  "cellHeight": "æ_Cell Height (y)______Â",
  "invalidNumberMessage": "æ_The value entered is not valid__________Â",
  "invalidRangeMessage": "æ_Value must be greater than 0_________Â",
  "gridAngleInvalidRangeMessage": "æ_Value must be between -89.9 and 89.9____________Â",
  "formatIconTooltip": "æ_Format Input_____Â",
  "coordInputLabel": "æ_GRG Origin (DD)______Â",
  "setCoordFormat": "æ_Set Coordinate Format String_________Â",
  "prefixNumbers": "æ_Add '+/-' prefix to positive and negative numbers________________Â",
  "cancelBtn": "æ_Cancel___Â",
  "applyBtn": "æ_Apply___Â",
  "comfirmInputNotation": "æ_Confirm Input Notation________Â",
  "notationsMatch": "æ_notations match your input please confirm which you would like to use______________________Â:",
  "numberOfCellsHorizontal": "æ_# Horizontal Cells______Â",
  "numberOfCellsVertical": "æ_# Vertical Cells______Â",
  "gridAngle": "æ_Grid Rotation_____Â",
  "tooManyCellsErrorMessage": "æ_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________Â.",
  "missingParametersMessage": "æ_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________Â",
  "missingOriginParametersMessage": "æ_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________Â",
  "invalidWidthHeightParametersMessage": "æ_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________Â",
  "invalidHorizontalVerticalParametersMessage": "æ_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________Â",
  "drawPointToolTip": "æ_Click to add GRG origin point__________Â",
  "missingLayerNameMessage": "æ_You must enter a valid layer name before you can publish__________________Â",
  "parseCoordinatesError": "æ_Unable to parse coordinates. Please check your input_________________Â.",
  "grgPolarRegionError": "æ_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________Â.",
  "grgPolarOriginError": "æ_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________Â.",
  "DD": "æ_DD__Â",
  "DDM": "æ_DDM__Â",
  "DMS": "æ_DMS__Â",
  "DDRev": "æ_DDRev___Â",
  "DDMRev": "æ_DDMRev___Â",
  "DMSRev": "æ_DMSRev___Â",
  "USNG": "æ_USNG__Â",
  "MGRS": "æ_MGRS__Â",
  "UTM_H": "æ_UTM (H)___Â",
  "UTM": "æ_UTM__Â",
  "GARS": "æ_GARS__Â",
  "GEOREF": "æ_GEOREF___Â",
  "DDLatLongNotation": "æ_Decimal Degrees - Latitude/Longitude____________Â",
  "DDLongLatNotation": "æ_Decimal Degrees  - Longitude/Latitude____________Â",
  "DDMLatLongNotation": "æ_Degrees Decimal Minutes - Latitude/Longitude______________Â",
  "DDMLongLatNotation": "æ_Degrees Decimal Minutes - Longitude/Latitude______________Â",
  "DMSLatLongNotation": "æ_Degrees Minutes Seconds - Latitude/Longitude______________Â",
  "DMSLongLatNotation": "æ_Degrees Minutes Seconds - Longitude/Latitude______________Â",
  "GARSNotation": "æ_GARS__Â",
  "GEOREFNotation": "æ_GEOREF___Â",
  "MGRSNotation": "æ_MGRS__Â",
  "USNGNotation": "æ_USNG__Â",
  "UTMBandNotation": "æ_UTM - Band Letter______Â",
  "UTMHemNotation": "æ_UTM - Hemisphere (N/S)________Â"
});