define({
  "gridTabLabel": "Ř_Grid__ů",
  "labelTabLabel": "Ř_Labels___ů",
  "referenceSystemTabLabel": "Ř_Reference System______ů",
  "gridTabDescription": "Ř_Set the appearance and behavior of the grid cells________________ů.",
  "cellOutlineColor": "Ř_Cell Outine color______ů",
  "cellFillColor": "Ř_Cell Fill color______ů",
  "transparency": "Ř_Transparency_____ů",
  "cellShapeDropDown": "Ř_Cell Shape____ů",
  "default": "Ř_Rectangle____ů",
  "hexagon": "Ř_Hexagon___ů",
  "cellUnitsDropDown": "Ř_Cell Units____ů",
  "miles": "Ř_Miles___ů",
  "kilometers": "Ř_Kilometers____ů",
  "feet": "Ř_Feet__ů",
  "meters": "Ř_Meters___ů",
  "yards": "Ř_Yards___ů",
  "nautical-miles": "Ř_Nautical Miles_____ů",
  "gridOriginDropDown": "Ř_Grid Origin____ů",
  "lowerLeft": "Ř_Lower-Left____ů",
  "lowerRight": "Ř_Lower-Right____ů",
  "upperLeft": "Ř_Upper-Left____ů",
  "upperRight": "Ř_Upper-Right____ů",
  "center": "Ř_Center___ů",
  "labelTabDescription": "Ř_Set the appearance and behavior of the grid labels________________ů.",
  "labelSettings": "Ř_Label Style____ů",
  "font": "Ř_Font__ů",
  "textSize": "Ř_Text Size____ů",
  "textColor": "Ř_Text Color____ů",
  "halo": "Ř_Halo__ů",
  "show": "Ř_Show__ů",
  "labelTypeDropDown": "Ř_Label Type____ů",
  "alphaNumeric": "Ř_Alpha-Numeric_____ů",
  "alphaAlpha": "Ř_Alpha-Alpha____ů",
  "numeric": "Ř_Numeric___ů",
  "labelDirectionDropDown": "Ř_Label Direction______ů",
  "horizontal": "Ř_Horizontal____ů",
  "vertical": "Ř_Vertical___ů",
  "labelOriginDropDown": "Ř_Label Origin_____ů",
  "referenceSystemlTabDescription": "Ř_Set the default reference system___________ů.",
  "MGRS": "Ř_MGRS__ů",
  "USNG": "Ř_USNG__ů",
  "lockSettings": "Ř_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________ů"
});