define({
  "_widgetLabel": "ก้_Gridded Reference Graphic_________ษฺ",
  "newGRGFromAreaButtonLabel": "ก้_Define a Grid from an Area_________ษฺ",
  "newGRGFromPointButtonLabel": "ก้_Define a Grid from a Point_________ษฺ",
  "newGRGFromAreaTitle": "ก้_Define a Grid from an Area_________ษฺ",
  "newGRGFromPointTitle": "ก้_Define a Grid from a Point_________ษฺ",
  "newGRGBySizeButtonLabel": "ก้_By Dimension_____ษฺ",
  "newGRGFromRefSystemButtonLabel": "ก้_By Reference System_______ษฺ",
  "newGRGByTimeLabel": "ก้_By Time and Speed______ษฺ",
  "newGRGFromNonStandardButtonLabel": "ก้_Define Non-Standard Grid________ษฺ",
  "newGRGAreaBySizeTitle": "ก้_GRG from an Area by Dimension__________ษฺ",
  "newGRGAreaBySizeDefineAreaLabel": "ก้_GRG Area___ษฺ",
  "addGRGAreaPolygonToolTip": "ก้_Draw GRG Area using polygon_________ษฺ",
  "addGRGAreaExtentToolTip": "ก้_Draw GRG Area using extent_________ษฺ",
  "rotation": "ก้_Grid Rotation_____ษฺ",
  "numberRowsColumnsLabel": "ก้_Define number of rows and columns___________ษฺ",
  "newGRGAreaByRefSystemTitle": "ก้_GRG from an Area by Reference System____________ษฺ",
  "gridSize": "ก้_Grid Size____ษฺ",
  "UTMZoneandBand": "ก้_Grid Zone____ษฺ",
  "100000m": "ก้_100000 meter_____ษฺ",
  "10000m": "ก้_10000 meter____ษฺ",
  "1000m": "ก้_1000 meter____ษฺ",
  "100m": "ก้_100 meter____ษฺ",
  "10m": "ก้_10 meter___ษฺ",
  "clipGrid": "ก้_Clip Grid to GRG Area_______ษฺ",
  "newGRGAreaFromNonStandardTitle": "ก้_New NRG___ษฺ",
  "newGRGPointBySizeTitle": "ก้_GRG from Point by Dimension_________ษฺ",
  "newGRGPointByRefSystemTitle": "ก้_GRG from Point by Reference System___________ษฺ",
  "newGRGPointByTimeTitle": "ก้_GRG from Point using Time and Speed____________ษฺ",
  "time": "ก้_Time__ษฺ",
  "rate": "ก้_Speed___ษฺ",
  "hours": "ก้_Hours___ษฺ",
  "minutes": "ก้_Minutes___ษฺ",
  "seconds": "ก้_Seconds___ษฺ",
  "ftPerSec": "ก้_Feet / second_____ษฺ",
  "ftPerHour": "ก้_Feet / hour____ษฺ",
  "kmPerSec": "ก้_Kilometers / second_______ษฺ",
  "kmPerHour": "ก้_Kilometers / hour______ษฺ",
  "mPerSec": "ก้_Meters / second______ษฺ",
  "mPerHour": "ก้_Meters / hour_____ษฺ",
  "miPerSec": "ก้_Miles / second_____ษฺ",
  "miPerHour": "ก้_Miles / hour_____ษฺ",
  "nMPerSec": "ก้_Nautical Miles / second________ษฺ",
  "nMPerHour": "ก้_Nautical Miles / hour_______ษฺ",
  "settingsTitle": "ก้_Settings___ษฺ",
  "labelSettingsLabel": "ก้_Label Settings_____ษฺ",
  "labelSettingsButtonLabel": "ก้_Configure Label Settings________ษฺ",
  "gridSettingsLabel": "ก้_Grid Settings_____ษฺ",
  "gridSettingsButtonLabel": "ก้_Configure Grid Settings________ษฺ",
  "transparency": "ก้_Transparency_____ษฺ",
  "labelStyle": "ก้_Label Style____ษฺ",
  "font": "ก้_Font__ษฺ",
  "textSize": "ก้_Text Size____ษฺ",
  "textColor": "ก้_Text Color____ษฺ",
  "halo": "ก้_Halo__ษฺ",
  "show": "ก้_Show__ษฺ",
  "lockSettings": "ก้_Settings have been locked by the application owner________________ษฺ",
  "gridSettings": {
    "cellShape": "ก้_Cell Shape____ษฺ",
    "cellUnits": "ก้_Cell Units____ษฺ",
    "cellOutline": "ก้_Cell Outline Settings_______ษฺ",
    "cellFill": "ก้_Cell Fill Settings______ษฺ",
    "gridReferenceSystem": "ก้_Reference System______ษฺ",
    "gridDatum": "ก้_Datum: WGS84_____ษฺ",
    "labelStartPosition": "ก้_Label Origin_____ษฺ",
    "labelType": "ก้_Label Type____ษฺ",
    "labelDirection": "ก้_Label Direction______ษฺ",
    "gridOrigin": "ก้_Grid Origin____ษฺ",
    "default": "ก้_Rectangle____ษฺ",
    "hexagon": "ก้_Hexagon___ษฺ",
    "miles": "ก้_Miles___ษฺ",
    "kilometers": "ก้_Kilometers____ษฺ",
    "feet": "ก้_Feet__ษฺ",
    "meters": "ก้_Meters___ษฺ",
    "yards": "ก้_Yards___ษฺ",
    "nautical-miles": "ก้_Nautical Miles_____ษฺ",
    "lowerLeft": "ก้_Lower-Left____ษฺ",
    "lowerRight": "ก้_Lower-Right____ษฺ",
    "upperLeft": "ก้_Upper-Left____ษฺ",
    "upperRight": "ก้_Upper-Right____ษฺ",
    "center": "ก้_Center___ษฺ",
    "alphaNumeric": "ก้_Alpha-Numeric_____ษฺ",
    "alphaAlpha": "ก้_Alpha-Alpha____ษฺ",
    "numeric": "ก้_Numeric___ษฺ",
    "horizontal": "ก้_Horizontal____ษฺ",
    "vertical": "ก้_Vertical___ษฺ",
    "MGRS": "ก้_MGRS__ษฺ",
    "USNG": "ก้_USNG__ษฺ",
    "showLabels": "ก้_Show Labels____ษฺ"
  },
  "publishTitle": "ก้_Publish GRG to Portal_______ษฺ",
  "publishGRGBtn": "ก้_Publish___ษฺ",
  "GRGLayerName": "ก้_Published GRG Layer Name________ษฺ",
  "invalidGRGLayerName": "ก้_Layer name must only contain alpha-numeric characters and underscores______________________ษฺ",
  "missingGRGLayerName": "ก้_You must enter a name for the GRG___________ษฺ",
  "publishingFailedLayerExists": "ก้_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ษฺ.",
  "checkService": "ก้_Check Service: {0}______ษฺ",
  "createService": "ก้_Create Service: {0}_______ษฺ",
  "unableToCreate": "ก้_Unable to create: {0}_______ษฺ",
  "addToDefinition": "ก้_Add to definition: {0}________ษฺ",
  "successfullyPublished": "ก้_Successfully published web layer{0}Manage the web layer__________________ษฺ",
  "userRole": "ก้_Unable to create service because user does not have permissions____________________ษฺ",
  "createGRGBtn": "ก้_Create GRG____ษฺ",
  "clearGRGBtn": "ก้_Clear___ษฺ",
  "labelFormat": "ก้_Label Format_____ษฺ",
  "helpIconTooltip": "ก้_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________ษฺ",
  "addPointToolTip": "ก้_Add GRG Origin_____ษฺ",
  "cellWidth": "ก้_Cell Width (x)_____ษฺ",
  "cellHeight": "ก้_Cell Height (y)______ษฺ",
  "invalidNumberMessage": "ก้_The value entered is not valid__________ษฺ",
  "invalidRangeMessage": "ก้_Value must be greater than 0_________ษฺ",
  "gridAngleInvalidRangeMessage": "ก้_Value must be between -89.9 and 89.9____________ษฺ",
  "formatIconTooltip": "ก้_Format Input_____ษฺ",
  "coordInputLabel": "ก้_GRG Origin (DD)______ษฺ",
  "setCoordFormat": "ก้_Set Coordinate Format String_________ษฺ",
  "prefixNumbers": "ก้_Add '+/-' prefix to positive and negative numbers________________ษฺ",
  "cancelBtn": "ก้_Cancel___ษฺ",
  "applyBtn": "ก้_Apply___ษฺ",
  "comfirmInputNotation": "ก้_Confirm Input Notation________ษฺ",
  "notationsMatch": "ก้_notations match your input please confirm which you would like to use______________________ษฺ:",
  "numberOfCellsHorizontal": "ก้_# Horizontal Cells______ษฺ",
  "numberOfCellsVertical": "ก้_# Vertical Cells______ษฺ",
  "gridAngle": "ก้_Grid Rotation_____ษฺ",
  "tooManyCellsErrorMessage": "ก้_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________ษฺ.",
  "missingParametersMessage": "ก้_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________ษฺ",
  "missingOriginParametersMessage": "ก้_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________ษฺ",
  "invalidWidthHeightParametersMessage": "ก้_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________ษฺ",
  "invalidHorizontalVerticalParametersMessage": "ก้_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________ษฺ",
  "drawPointToolTip": "ก้_Click to add GRG origin point__________ษฺ",
  "missingLayerNameMessage": "ก้_You must enter a valid layer name before you can publish__________________ษฺ",
  "parseCoordinatesError": "ก้_Unable to parse coordinates. Please check your input_________________ษฺ.",
  "grgPolarRegionError": "ก้_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________ษฺ.",
  "grgPolarOriginError": "ก้_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________ษฺ.",
  "DD": "ก้_DD__ษฺ",
  "DDM": "ก้_DDM__ษฺ",
  "DMS": "ก้_DMS__ษฺ",
  "DDRev": "ก้_DDRev___ษฺ",
  "DDMRev": "ก้_DDMRev___ษฺ",
  "DMSRev": "ก้_DMSRev___ษฺ",
  "USNG": "ก้_USNG__ษฺ",
  "MGRS": "ก้_MGRS__ษฺ",
  "UTM_H": "ก้_UTM (H)___ษฺ",
  "UTM": "ก้_UTM__ษฺ",
  "GARS": "ก้_GARS__ษฺ",
  "GEOREF": "ก้_GEOREF___ษฺ",
  "DDLatLongNotation": "ก้_Decimal Degrees - Latitude/Longitude____________ษฺ",
  "DDLongLatNotation": "ก้_Decimal Degrees  - Longitude/Latitude____________ษฺ",
  "DDMLatLongNotation": "ก้_Degrees Decimal Minutes - Latitude/Longitude______________ษฺ",
  "DDMLongLatNotation": "ก้_Degrees Decimal Minutes - Longitude/Latitude______________ษฺ",
  "DMSLatLongNotation": "ก้_Degrees Minutes Seconds - Latitude/Longitude______________ษฺ",
  "DMSLongLatNotation": "ก้_Degrees Minutes Seconds - Longitude/Latitude______________ษฺ",
  "GARSNotation": "ก้_GARS__ษฺ",
  "GEOREFNotation": "ก้_GEOREF___ษฺ",
  "MGRSNotation": "ก้_MGRS__ษฺ",
  "USNGNotation": "ก้_USNG__ษฺ",
  "UTMBandNotation": "ก้_UTM - Band Letter______ษฺ",
  "UTMHemNotation": "ก้_UTM - Hemisphere (N/S)________ษฺ"
});