define({
  "_widgetLabel": "ng_Gridded Reference Graphic_________ny",
  "newGRGFromAreaButtonLabel": "ng_Define a Grid from an Area_________ny",
  "newGRGFromPointButtonLabel": "ng_Define a Grid from a Point_________ny",
  "newGRGFromAreaTitle": "ng_Define a Grid from an Area_________ny",
  "newGRGFromPointTitle": "ng_Define a Grid from a Point_________ny",
  "newGRGBySizeButtonLabel": "ng_By Dimension_____ny",
  "newGRGFromRefSystemButtonLabel": "ng_By Reference System_______ny",
  "newGRGByTimeLabel": "ng_By Time and Speed______ny",
  "newGRGFromNonStandardButtonLabel": "ng_Define Non-Standard Grid________ny",
  "newGRGAreaBySizeTitle": "ng_GRG from an Area by Dimension__________ny",
  "newGRGAreaBySizeDefineAreaLabel": "ng_GRG Area___ny",
  "addGRGAreaPolygonToolTip": "ng_Draw GRG Area using polygon_________ny",
  "addGRGAreaExtentToolTip": "ng_Draw GRG Area using extent_________ny",
  "rotation": "ng_Grid Rotation_____ny",
  "numberRowsColumnsLabel": "ng_Define number of rows and columns___________ny",
  "newGRGAreaByRefSystemTitle": "ng_GRG from an Area by Reference System____________ny",
  "gridSize": "ng_Grid Size____ny",
  "UTMZoneandBand": "ng_Grid Zone____ny",
  "100000m": "ng_100000 meter_____ny",
  "10000m": "ng_10000 meter____ny",
  "1000m": "ng_1000 meter____ny",
  "100m": "ng_100 meter____ny",
  "10m": "ng_10 meter___ny",
  "clipGrid": "ng_Clip Grid to GRG Area_______ny",
  "newGRGAreaFromNonStandardTitle": "ng_New NRG___ny",
  "newGRGPointBySizeTitle": "ng_GRG from Point by Dimension_________ny",
  "newGRGPointByRefSystemTitle": "ng_GRG from Point by Reference System___________ny",
  "newGRGPointByTimeTitle": "ng_GRG from Point using Time and Speed____________ny",
  "time": "ng_Time__ny",
  "rate": "ng_Speed___ny",
  "hours": "ng_Hours___ny",
  "minutes": "ng_Minutes___ny",
  "seconds": "ng_Seconds___ny",
  "ftPerSec": "ng_Feet / second_____ny",
  "ftPerHour": "ng_Feet / hour____ny",
  "kmPerSec": "ng_Kilometers / second_______ny",
  "kmPerHour": "ng_Kilometers / hour______ny",
  "mPerSec": "ng_Meters / second______ny",
  "mPerHour": "ng_Meters / hour_____ny",
  "miPerSec": "ng_Miles / second_____ny",
  "miPerHour": "ng_Miles / hour_____ny",
  "nMPerSec": "ng_Nautical Miles / second________ny",
  "nMPerHour": "ng_Nautical Miles / hour_______ny",
  "settingsTitle": "ng_Settings___ny",
  "labelSettingsLabel": "ng_Label Settings_____ny",
  "labelSettingsButtonLabel": "ng_Configure Label Settings________ny",
  "gridSettingsLabel": "ng_Grid Settings_____ny",
  "gridSettingsButtonLabel": "ng_Configure Grid Settings________ny",
  "transparency": "ng_Transparency_____ny",
  "labelStyle": "ng_Label Style____ny",
  "font": "ng_Font__ny",
  "textSize": "ng_Text Size____ny",
  "textColor": "ng_Text Color____ny",
  "halo": "ng_Halo__ny",
  "show": "ng_Show__ny",
  "lockSettings": "ng_Settings have been locked by the application owner________________ny",
  "gridSettings": {
    "cellShape": "ng_Cell Shape____ny",
    "cellUnits": "ng_Cell Units____ny",
    "cellOutline": "ng_Cell Outline Settings_______ny",
    "cellFill": "ng_Cell Fill Settings______ny",
    "gridReferenceSystem": "ng_Reference System______ny",
    "gridDatum": "ng_Datum: WGS84_____ny",
    "labelStartPosition": "ng_Label Origin_____ny",
    "labelType": "ng_Label Type____ny",
    "labelDirection": "ng_Label Direction______ny",
    "gridOrigin": "ng_Grid Origin____ny",
    "default": "ng_Rectangle____ny",
    "hexagon": "ng_Hexagon___ny",
    "miles": "ng_Miles___ny",
    "kilometers": "ng_Kilometers____ny",
    "feet": "ng_Feet__ny",
    "meters": "ng_Meters___ny",
    "yards": "ng_Yards___ny",
    "nautical-miles": "ng_Nautical Miles_____ny",
    "lowerLeft": "ng_Lower-Left____ny",
    "lowerRight": "ng_Lower-Right____ny",
    "upperLeft": "ng_Upper-Left____ny",
    "upperRight": "ng_Upper-Right____ny",
    "center": "ng_Center___ny",
    "alphaNumeric": "ng_Alpha-Numeric_____ny",
    "alphaAlpha": "ng_Alpha-Alpha____ny",
    "numeric": "ng_Numeric___ny",
    "horizontal": "ng_Horizontal____ny",
    "vertical": "ng_Vertical___ny",
    "MGRS": "ng_MGRS__ny",
    "USNG": "ng_USNG__ny",
    "showLabels": "ng_Show Labels____ny"
  },
  "publishTitle": "ng_Publish GRG to Portal_______ny",
  "publishGRGBtn": "ng_Publish___ny",
  "GRGLayerName": "ng_Published GRG Layer Name________ny",
  "invalidGRGLayerName": "ng_Layer name must only contain alpha-numeric characters and underscores______________________ny",
  "missingGRGLayerName": "ng_You must enter a name for the GRG___________ny",
  "publishingFailedLayerExists": "ng_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ny.",
  "checkService": "ng_Check Service: {0}______ny",
  "createService": "ng_Create Service: {0}_______ny",
  "unableToCreate": "ng_Unable to create: {0}_______ny",
  "addToDefinition": "ng_Add to definition: {0}________ny",
  "successfullyPublished": "ng_Successfully published web layer{0}Manage the web layer__________________ny",
  "userRole": "ng_Unable to create service because user does not have permissions____________________ny",
  "createGRGBtn": "ng_Create GRG____ny",
  "clearGRGBtn": "ng_Clear___ny",
  "labelFormat": "ng_Label Format_____ny",
  "helpIconTooltip": "ng_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________ny",
  "addPointToolTip": "ng_Add GRG Origin_____ny",
  "cellWidth": "ng_Cell Width (x)_____ny",
  "cellHeight": "ng_Cell Height (y)______ny",
  "invalidNumberMessage": "ng_The value entered is not valid__________ny",
  "invalidRangeMessage": "ng_Value must be greater than 0_________ny",
  "gridAngleInvalidRangeMessage": "ng_Value must be between -89.9 and 89.9____________ny",
  "formatIconTooltip": "ng_Format Input_____ny",
  "coordInputLabel": "ng_GRG Origin (DD)______ny",
  "setCoordFormat": "ng_Set Coordinate Format String_________ny",
  "prefixNumbers": "ng_Add '+/-' prefix to positive and negative numbers________________ny",
  "cancelBtn": "ng_Cancel___ny",
  "applyBtn": "ng_Apply___ny",
  "comfirmInputNotation": "ng_Confirm Input Notation________ny",
  "notationsMatch": "ng_notations match your input please confirm which you would like to use______________________ny:",
  "numberOfCellsHorizontal": "ng_# Horizontal Cells______ny",
  "numberOfCellsVertical": "ng_# Vertical Cells______ny",
  "gridAngle": "ng_Grid Rotation_____ny",
  "tooManyCellsErrorMessage": "ng_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________ny.",
  "missingParametersMessage": "ng_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________ny",
  "missingOriginParametersMessage": "ng_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________ny",
  "invalidWidthHeightParametersMessage": "ng_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________ny",
  "invalidHorizontalVerticalParametersMessage": "ng_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________ny",
  "drawPointToolTip": "ng_Click to add GRG origin point__________ny",
  "missingLayerNameMessage": "ng_You must enter a valid layer name before you can publish__________________ny",
  "parseCoordinatesError": "ng_Unable to parse coordinates. Please check your input_________________ny.",
  "grgPolarRegionError": "ng_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________ny.",
  "grgPolarOriginError": "ng_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________ny.",
  "DD": "ng_DD__ny",
  "DDM": "ng_DDM__ny",
  "DMS": "ng_DMS__ny",
  "DDRev": "ng_DDRev___ny",
  "DDMRev": "ng_DDMRev___ny",
  "DMSRev": "ng_DMSRev___ny",
  "USNG": "ng_USNG__ny",
  "MGRS": "ng_MGRS__ny",
  "UTM_H": "ng_UTM (H)___ny",
  "UTM": "ng_UTM__ny",
  "GARS": "ng_GARS__ny",
  "GEOREF": "ng_GEOREF___ny",
  "DDLatLongNotation": "ng_Decimal Degrees - Latitude/Longitude____________ny",
  "DDLongLatNotation": "ng_Decimal Degrees  - Longitude/Latitude____________ny",
  "DDMLatLongNotation": "ng_Degrees Decimal Minutes - Latitude/Longitude______________ny",
  "DDMLongLatNotation": "ng_Degrees Decimal Minutes - Longitude/Latitude______________ny",
  "DMSLatLongNotation": "ng_Degrees Minutes Seconds - Latitude/Longitude______________ny",
  "DMSLongLatNotation": "ng_Degrees Minutes Seconds - Longitude/Latitude______________ny",
  "GARSNotation": "ng_GARS__ny",
  "GEOREFNotation": "ng_GEOREF___ny",
  "MGRSNotation": "ng_MGRS__ny",
  "USNGNotation": "ng_USNG__ny",
  "UTMBandNotation": "ng_UTM - Band Letter______ny",
  "UTMHemNotation": "ng_UTM - Hemisphere (N/S)________ny"
});