define({
  "gridTabLabel": "é_Grid__È",
  "labelTabLabel": "é_Labels___È",
  "referenceSystemTabLabel": "é_Reference System______È",
  "gridTabDescription": "é_Set the appearance and behavior of the grid cells________________È.",
  "cellOutlineColor": "é_Cell Outine color______È",
  "cellFillColor": "é_Cell Fill color______È",
  "transparency": "é_Transparency_____È",
  "cellShapeDropDown": "é_Cell Shape____È",
  "default": "é_Rectangle____È",
  "hexagon": "é_Hexagon___È",
  "cellUnitsDropDown": "é_Cell Units____È",
  "miles": "é_Miles___È",
  "kilometers": "é_Kilometers____È",
  "feet": "é_Feet__È",
  "meters": "é_Meters___È",
  "yards": "é_Yards___È",
  "nautical-miles": "é_Nautical Miles_____È",
  "gridOriginDropDown": "é_Grid Origin____È",
  "lowerLeft": "é_Lower-Left____È",
  "lowerRight": "é_Lower-Right____È",
  "upperLeft": "é_Upper-Left____È",
  "upperRight": "é_Upper-Right____È",
  "center": "é_Center___È",
  "labelTabDescription": "é_Set the appearance and behavior of the grid labels________________È.",
  "labelSettings": "é_Label Style____È",
  "font": "é_Font__È",
  "textSize": "é_Text Size____È",
  "textColor": "é_Text Color____È",
  "halo": "é_Halo__È",
  "show": "é_Show__È",
  "labelTypeDropDown": "é_Label Type____È",
  "alphaNumeric": "é_Alpha-Numeric_____È",
  "alphaAlpha": "é_Alpha-Alpha____È",
  "numeric": "é_Numeric___È",
  "labelDirectionDropDown": "é_Label Direction______È",
  "horizontal": "é_Horizontal____È",
  "vertical": "é_Vertical___È",
  "labelOriginDropDown": "é_Label Origin_____È",
  "referenceSystemlTabDescription": "é_Set the default reference system___________È.",
  "MGRS": "é_MGRS__È",
  "USNG": "é_USNG__È",
  "lockSettings": "é_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________È"
});