define({
  "gridTabLabel": "ķ_Grid__ū",
  "labelTabLabel": "ķ_Labels___ū",
  "referenceSystemTabLabel": "ķ_Reference System______ū",
  "gridTabDescription": "ķ_Set the appearance and behavior of the grid cells________________ū.",
  "cellOutlineColor": "ķ_Cell Outine color______ū",
  "cellFillColor": "ķ_Cell Fill color______ū",
  "transparency": "ķ_Transparency_____ū",
  "cellShapeDropDown": "ķ_Cell Shape____ū",
  "default": "ķ_Rectangle____ū",
  "hexagon": "ķ_Hexagon___ū",
  "cellUnitsDropDown": "ķ_Cell Units____ū",
  "miles": "ķ_Miles___ū",
  "kilometers": "ķ_Kilometers____ū",
  "feet": "ķ_Feet__ū",
  "meters": "ķ_Meters___ū",
  "yards": "ķ_Yards___ū",
  "nautical-miles": "ķ_Nautical Miles_____ū",
  "gridOriginDropDown": "ķ_Grid Origin____ū",
  "lowerLeft": "ķ_Lower-Left____ū",
  "lowerRight": "ķ_Lower-Right____ū",
  "upperLeft": "ķ_Upper-Left____ū",
  "upperRight": "ķ_Upper-Right____ū",
  "center": "ķ_Center___ū",
  "labelTabDescription": "ķ_Set the appearance and behavior of the grid labels________________ū.",
  "labelSettings": "ķ_Label Style____ū",
  "font": "ķ_Font__ū",
  "textSize": "ķ_Text Size____ū",
  "textColor": "ķ_Text Color____ū",
  "halo": "ķ_Halo__ū",
  "show": "ķ_Show__ū",
  "labelTypeDropDown": "ķ_Label Type____ū",
  "alphaNumeric": "ķ_Alpha-Numeric_____ū",
  "alphaAlpha": "ķ_Alpha-Alpha____ū",
  "numeric": "ķ_Numeric___ū",
  "labelDirectionDropDown": "ķ_Label Direction______ū",
  "horizontal": "ķ_Horizontal____ū",
  "vertical": "ķ_Vertical___ū",
  "labelOriginDropDown": "ķ_Label Origin_____ū",
  "referenceSystemlTabDescription": "ķ_Set the default reference system___________ū.",
  "MGRS": "ķ_MGRS__ū",
  "USNG": "ķ_USNG__ū",
  "lockSettings": "ķ_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________ū"
});