define({
  "_widgetLabel": "Ř_Gridded Reference Graphic_________ů",
  "newGRGFromAreaButtonLabel": "Ř_Define a Grid from an Area_________ů",
  "newGRGFromPointButtonLabel": "Ř_Define a Grid from a Point_________ů",
  "newGRGFromAreaTitle": "Ř_Define a Grid from an Area_________ů",
  "newGRGFromPointTitle": "Ř_Define a Grid from a Point_________ů",
  "newGRGBySizeButtonLabel": "Ř_By Dimension_____ů",
  "newGRGFromRefSystemButtonLabel": "Ř_By Reference System_______ů",
  "newGRGByTimeLabel": "Ř_By Time and Speed______ů",
  "newGRGFromNonStandardButtonLabel": "Ř_Define Non-Standard Grid________ů",
  "newGRGAreaBySizeTitle": "Ř_GRG from an Area by Dimension__________ů",
  "newGRGAreaBySizeDefineAreaLabel": "Ř_GRG Area___ů",
  "addGRGAreaPolygonToolTip": "Ř_Draw GRG Area using polygon_________ů",
  "addGRGAreaExtentToolTip": "Ř_Draw GRG Area using extent_________ů",
  "rotation": "Ř_Grid Rotation_____ů",
  "numberRowsColumnsLabel": "Ř_Define number of rows and columns___________ů",
  "newGRGAreaByRefSystemTitle": "Ř_GRG from an Area by Reference System____________ů",
  "gridSize": "Ř_Grid Size____ů",
  "UTMZoneandBand": "Ř_Grid Zone____ů",
  "100000m": "Ř_100000 meter_____ů",
  "10000m": "Ř_10000 meter____ů",
  "1000m": "Ř_1000 meter____ů",
  "100m": "Ř_100 meter____ů",
  "10m": "Ř_10 meter___ů",
  "clipGrid": "Ř_Clip Grid to GRG Area_______ů",
  "newGRGAreaFromNonStandardTitle": "Ř_New NRG___ů",
  "newGRGPointBySizeTitle": "Ř_GRG from Point by Dimension_________ů",
  "newGRGPointByRefSystemTitle": "Ř_GRG from Point by Reference System___________ů",
  "newGRGPointByTimeTitle": "Ř_GRG from Point using Time and Speed____________ů",
  "time": "Ř_Time__ů",
  "rate": "Ř_Speed___ů",
  "hours": "Ř_Hours___ů",
  "minutes": "Ř_Minutes___ů",
  "seconds": "Ř_Seconds___ů",
  "ftPerSec": "Ř_Feet / second_____ů",
  "ftPerHour": "Ř_Feet / hour____ů",
  "kmPerSec": "Ř_Kilometers / second_______ů",
  "kmPerHour": "Ř_Kilometers / hour______ů",
  "mPerSec": "Ř_Meters / second______ů",
  "mPerHour": "Ř_Meters / hour_____ů",
  "miPerSec": "Ř_Miles / second_____ů",
  "miPerHour": "Ř_Miles / hour_____ů",
  "nMPerSec": "Ř_Nautical Miles / second________ů",
  "nMPerHour": "Ř_Nautical Miles / hour_______ů",
  "settingsTitle": "Ř_Settings___ů",
  "labelSettingsLabel": "Ř_Label Settings_____ů",
  "labelSettingsButtonLabel": "Ř_Configure Label Settings________ů",
  "gridSettingsLabel": "Ř_Grid Settings_____ů",
  "gridSettingsButtonLabel": "Ř_Configure Grid Settings________ů",
  "transparency": "Ř_Transparency_____ů",
  "labelStyle": "Ř_Label Style____ů",
  "font": "Ř_Font__ů",
  "textSize": "Ř_Text Size____ů",
  "textColor": "Ř_Text Color____ů",
  "halo": "Ř_Halo__ů",
  "show": "Ř_Show__ů",
  "lockSettings": "Ř_Settings have been locked by the application owner________________ů",
  "gridSettings": {
    "cellShape": "Ř_Cell Shape____ů",
    "cellUnits": "Ř_Cell Units____ů",
    "cellOutline": "Ř_Cell Outline Settings_______ů",
    "cellFill": "Ř_Cell Fill Settings______ů",
    "gridReferenceSystem": "Ř_Reference System______ů",
    "gridDatum": "Ř_Datum: WGS84_____ů",
    "labelStartPosition": "Ř_Label Origin_____ů",
    "labelType": "Ř_Label Type____ů",
    "labelDirection": "Ř_Label Direction______ů",
    "gridOrigin": "Ř_Grid Origin____ů",
    "default": "Ř_Rectangle____ů",
    "hexagon": "Ř_Hexagon___ů",
    "miles": "Ř_Miles___ů",
    "kilometers": "Ř_Kilometers____ů",
    "feet": "Ř_Feet__ů",
    "meters": "Ř_Meters___ů",
    "yards": "Ř_Yards___ů",
    "nautical-miles": "Ř_Nautical Miles_____ů",
    "lowerLeft": "Ř_Lower-Left____ů",
    "lowerRight": "Ř_Lower-Right____ů",
    "upperLeft": "Ř_Upper-Left____ů",
    "upperRight": "Ř_Upper-Right____ů",
    "center": "Ř_Center___ů",
    "alphaNumeric": "Ř_Alpha-Numeric_____ů",
    "alphaAlpha": "Ř_Alpha-Alpha____ů",
    "numeric": "Ř_Numeric___ů",
    "horizontal": "Ř_Horizontal____ů",
    "vertical": "Ř_Vertical___ů",
    "MGRS": "Ř_MGRS__ů",
    "USNG": "Ř_USNG__ů",
    "showLabels": "Ř_Show Labels____ů"
  },
  "publishTitle": "Ř_Publish GRG to Portal_______ů",
  "publishGRGBtn": "Ř_Publish___ů",
  "GRGLayerName": "Ř_Published GRG Layer Name________ů",
  "invalidGRGLayerName": "Ř_Layer name must only contain alpha-numeric characters and underscores______________________ů",
  "missingGRGLayerName": "Ř_You must enter a name for the GRG___________ů",
  "publishingFailedLayerExists": "Ř_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ů.",
  "checkService": "Ř_Check Service: {0}______ů",
  "createService": "Ř_Create Service: {0}_______ů",
  "unableToCreate": "Ř_Unable to create: {0}_______ů",
  "addToDefinition": "Ř_Add to definition: {0}________ů",
  "successfullyPublished": "Ř_Successfully published web layer{0}Manage the web layer__________________ů",
  "userRole": "Ř_Unable to create service because user does not have permissions____________________ů",
  "createGRGBtn": "Ř_Create GRG____ů",
  "clearGRGBtn": "Ř_Clear___ů",
  "labelFormat": "Ř_Label Format_____ů",
  "helpIconTooltip": "Ř_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________ů",
  "addPointToolTip": "Ř_Add GRG Origin_____ů",
  "cellWidth": "Ř_Cell Width (x)_____ů",
  "cellHeight": "Ř_Cell Height (y)______ů",
  "invalidNumberMessage": "Ř_The value entered is not valid__________ů",
  "invalidRangeMessage": "Ř_Value must be greater than 0_________ů",
  "gridAngleInvalidRangeMessage": "Ř_Value must be between -89.9 and 89.9____________ů",
  "formatIconTooltip": "Ř_Format Input_____ů",
  "coordInputLabel": "Ř_GRG Origin (DD)______ů",
  "setCoordFormat": "Ř_Set Coordinate Format String_________ů",
  "prefixNumbers": "Ř_Add '+/-' prefix to positive and negative numbers________________ů",
  "cancelBtn": "Ř_Cancel___ů",
  "applyBtn": "Ř_Apply___ů",
  "comfirmInputNotation": "Ř_Confirm Input Notation________ů",
  "notationsMatch": "Ř_notations match your input please confirm which you would like to use______________________ů:",
  "numberOfCellsHorizontal": "Ř_# Horizontal Cells______ů",
  "numberOfCellsVertical": "Ř_# Vertical Cells______ů",
  "gridAngle": "Ř_Grid Rotation_____ů",
  "tooManyCellsErrorMessage": "Ř_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________ů.",
  "missingParametersMessage": "Ř_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________ů",
  "missingOriginParametersMessage": "Ř_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________ů",
  "invalidWidthHeightParametersMessage": "Ř_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________ů",
  "invalidHorizontalVerticalParametersMessage": "Ř_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________ů",
  "drawPointToolTip": "Ř_Click to add GRG origin point__________ů",
  "missingLayerNameMessage": "Ř_You must enter a valid layer name before you can publish__________________ů",
  "parseCoordinatesError": "Ř_Unable to parse coordinates. Please check your input_________________ů.",
  "grgPolarRegionError": "Ř_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________ů.",
  "grgPolarOriginError": "Ř_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________ů.",
  "DD": "Ř_DD__ů",
  "DDM": "Ř_DDM__ů",
  "DMS": "Ř_DMS__ů",
  "DDRev": "Ř_DDRev___ů",
  "DDMRev": "Ř_DDMRev___ů",
  "DMSRev": "Ř_DMSRev___ů",
  "USNG": "Ř_USNG__ů",
  "MGRS": "Ř_MGRS__ů",
  "UTM_H": "Ř_UTM (H)___ů",
  "UTM": "Ř_UTM__ů",
  "GARS": "Ř_GARS__ů",
  "GEOREF": "Ř_GEOREF___ů",
  "DDLatLongNotation": "Ř_Decimal Degrees - Latitude/Longitude____________ů",
  "DDLongLatNotation": "Ř_Decimal Degrees  - Longitude/Latitude____________ů",
  "DDMLatLongNotation": "Ř_Degrees Decimal Minutes - Latitude/Longitude______________ů",
  "DDMLongLatNotation": "Ř_Degrees Decimal Minutes - Longitude/Latitude______________ů",
  "DMSLatLongNotation": "Ř_Degrees Minutes Seconds - Latitude/Longitude______________ů",
  "DMSLongLatNotation": "Ř_Degrees Minutes Seconds - Longitude/Latitude______________ů",
  "GARSNotation": "Ř_GARS__ů",
  "GEOREFNotation": "Ř_GEOREF___ů",
  "MGRSNotation": "Ř_MGRS__ů",
  "USNGNotation": "Ř_USNG__ů",
  "UTMBandNotation": "Ř_UTM - Band Letter______ů",
  "UTMHemNotation": "Ř_UTM - Hemisphere (N/S)________ů"
});