define({
  "_widgetLabel": "á_Gridded Reference Graphic_________Ó",
  "newGRGFromAreaButtonLabel": "á_Define a Grid from an Area_________Ó",
  "newGRGFromPointButtonLabel": "á_Define a Grid from a Point_________Ó",
  "newGRGFromAreaTitle": "á_Define a Grid from an Area_________Ó",
  "newGRGFromPointTitle": "á_Define a Grid from a Point_________Ó",
  "newGRGBySizeButtonLabel": "á_By Dimension_____Ó",
  "newGRGFromRefSystemButtonLabel": "á_By Reference System_______Ó",
  "newGRGByTimeLabel": "á_By Time and Speed______Ó",
  "newGRGFromNonStandardButtonLabel": "á_Define Non-Standard Grid________Ó",
  "newGRGAreaBySizeTitle": "á_GRG from an Area by Dimension__________Ó",
  "newGRGAreaBySizeDefineAreaLabel": "á_GRG Area___Ó",
  "addGRGAreaPolygonToolTip": "á_Draw GRG Area using polygon_________Ó",
  "addGRGAreaExtentToolTip": "á_Draw GRG Area using extent_________Ó",
  "rotation": "á_Grid Rotation_____Ó",
  "numberRowsColumnsLabel": "á_Define number of rows and columns___________Ó",
  "newGRGAreaByRefSystemTitle": "á_GRG from an Area by Reference System____________Ó",
  "gridSize": "á_Grid Size____Ó",
  "UTMZoneandBand": "á_Grid Zone____Ó",
  "100000m": "á_100000 meter_____Ó",
  "10000m": "á_10000 meter____Ó",
  "1000m": "á_1000 meter____Ó",
  "100m": "á_100 meter____Ó",
  "10m": "á_10 meter___Ó",
  "clipGrid": "á_Clip Grid to GRG Area_______Ó",
  "newGRGAreaFromNonStandardTitle": "á_New NRG___Ó",
  "newGRGPointBySizeTitle": "á_GRG from Point by Dimension_________Ó",
  "newGRGPointByRefSystemTitle": "á_GRG from Point by Reference System___________Ó",
  "newGRGPointByTimeTitle": "á_GRG from Point using Time and Speed____________Ó",
  "time": "á_Time__Ó",
  "rate": "á_Speed___Ó",
  "hours": "á_Hours___Ó",
  "minutes": "á_Minutes___Ó",
  "seconds": "á_Seconds___Ó",
  "ftPerSec": "á_Feet / second_____Ó",
  "ftPerHour": "á_Feet / hour____Ó",
  "kmPerSec": "á_Kilometers / second_______Ó",
  "kmPerHour": "á_Kilometers / hour______Ó",
  "mPerSec": "á_Meters / second______Ó",
  "mPerHour": "á_Meters / hour_____Ó",
  "miPerSec": "á_Miles / second_____Ó",
  "miPerHour": "á_Miles / hour_____Ó",
  "nMPerSec": "á_Nautical Miles / second________Ó",
  "nMPerHour": "á_Nautical Miles / hour_______Ó",
  "settingsTitle": "á_Settings___Ó",
  "labelSettingsLabel": "á_Label Settings_____Ó",
  "labelSettingsButtonLabel": "á_Configure Label Settings________Ó",
  "gridSettingsLabel": "á_Grid Settings_____Ó",
  "gridSettingsButtonLabel": "á_Configure Grid Settings________Ó",
  "transparency": "á_Transparency_____Ó",
  "labelStyle": "á_Label Style____Ó",
  "font": "á_Font__Ó",
  "textSize": "á_Text Size____Ó",
  "textColor": "á_Text Color____Ó",
  "halo": "á_Halo__Ó",
  "show": "á_Show__Ó",
  "lockSettings": "á_Settings have been locked by the application owner________________Ó",
  "gridSettings": {
    "cellShape": "á_Cell Shape____Ó",
    "cellUnits": "á_Cell Units____Ó",
    "cellOutline": "á_Cell Outline Settings_______Ó",
    "cellFill": "á_Cell Fill Settings______Ó",
    "gridReferenceSystem": "á_Reference System______Ó",
    "gridDatum": "á_Datum: WGS84_____Ó",
    "labelStartPosition": "á_Label Origin_____Ó",
    "labelType": "á_Label Type____Ó",
    "labelDirection": "á_Label Direction______Ó",
    "gridOrigin": "á_Grid Origin____Ó",
    "default": "á_Rectangle____Ó",
    "hexagon": "á_Hexagon___Ó",
    "miles": "á_Miles___Ó",
    "kilometers": "á_Kilometers____Ó",
    "feet": "á_Feet__Ó",
    "meters": "á_Meters___Ó",
    "yards": "á_Yards___Ó",
    "nautical-miles": "á_Nautical Miles_____Ó",
    "lowerLeft": "á_Lower-Left____Ó",
    "lowerRight": "á_Lower-Right____Ó",
    "upperLeft": "á_Upper-Left____Ó",
    "upperRight": "á_Upper-Right____Ó",
    "center": "á_Center___Ó",
    "alphaNumeric": "á_Alpha-Numeric_____Ó",
    "alphaAlpha": "á_Alpha-Alpha____Ó",
    "numeric": "á_Numeric___Ó",
    "horizontal": "á_Horizontal____Ó",
    "vertical": "á_Vertical___Ó",
    "MGRS": "á_MGRS__Ó",
    "USNG": "á_USNG__Ó",
    "showLabels": "á_Show Labels____Ó"
  },
  "publishTitle": "á_Publish GRG to Portal_______Ó",
  "publishGRGBtn": "á_Publish___Ó",
  "GRGLayerName": "á_Published GRG Layer Name________Ó",
  "invalidGRGLayerName": "á_Layer name must only contain alpha-numeric characters and underscores______________________Ó",
  "missingGRGLayerName": "á_You must enter a name for the GRG___________Ó",
  "publishingFailedLayerExists": "á_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________Ó.",
  "checkService": "á_Check Service: {0}______Ó",
  "createService": "á_Create Service: {0}_______Ó",
  "unableToCreate": "á_Unable to create: {0}_______Ó",
  "addToDefinition": "á_Add to definition: {0}________Ó",
  "successfullyPublished": "á_Successfully published web layer{0}Manage the web layer__________________Ó",
  "userRole": "á_Unable to create service because user does not have permissions____________________Ó",
  "createGRGBtn": "á_Create GRG____Ó",
  "clearGRGBtn": "á_Clear___Ó",
  "labelFormat": "á_Label Format_____Ó",
  "helpIconTooltip": "á_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________Ó",
  "addPointToolTip": "á_Add GRG Origin_____Ó",
  "cellWidth": "á_Cell Width (x)_____Ó",
  "cellHeight": "á_Cell Height (y)______Ó",
  "invalidNumberMessage": "á_The value entered is not valid__________Ó",
  "invalidRangeMessage": "á_Value must be greater than 0_________Ó",
  "gridAngleInvalidRangeMessage": "á_Value must be between -89.9 and 89.9____________Ó",
  "formatIconTooltip": "á_Format Input_____Ó",
  "coordInputLabel": "á_GRG Origin (DD)______Ó",
  "setCoordFormat": "á_Set Coordinate Format String_________Ó",
  "prefixNumbers": "á_Add '+/-' prefix to positive and negative numbers________________Ó",
  "cancelBtn": "á_Cancel___Ó",
  "applyBtn": "á_Apply___Ó",
  "comfirmInputNotation": "á_Confirm Input Notation________Ó",
  "notationsMatch": "á_notations match your input please confirm which you would like to use______________________Ó:",
  "numberOfCellsHorizontal": "á_# Horizontal Cells______Ó",
  "numberOfCellsVertical": "á_# Vertical Cells______Ó",
  "gridAngle": "á_Grid Rotation_____Ó",
  "tooManyCellsErrorMessage": "á_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________Ó.",
  "missingParametersMessage": "á_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________Ó",
  "missingOriginParametersMessage": "á_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________Ó",
  "invalidWidthHeightParametersMessage": "á_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________Ó",
  "invalidHorizontalVerticalParametersMessage": "á_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________Ó",
  "drawPointToolTip": "á_Click to add GRG origin point__________Ó",
  "missingLayerNameMessage": "á_You must enter a valid layer name before you can publish__________________Ó",
  "parseCoordinatesError": "á_Unable to parse coordinates. Please check your input_________________Ó.",
  "grgPolarRegionError": "á_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________Ó.",
  "grgPolarOriginError": "á_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________Ó.",
  "DD": "á_DD__Ó",
  "DDM": "á_DDM__Ó",
  "DMS": "á_DMS__Ó",
  "DDRev": "á_DDRev___Ó",
  "DDMRev": "á_DDMRev___Ó",
  "DMSRev": "á_DMSRev___Ó",
  "USNG": "á_USNG__Ó",
  "MGRS": "á_MGRS__Ó",
  "UTM_H": "á_UTM (H)___Ó",
  "UTM": "á_UTM__Ó",
  "GARS": "á_GARS__Ó",
  "GEOREF": "á_GEOREF___Ó",
  "DDLatLongNotation": "á_Decimal Degrees - Latitude/Longitude____________Ó",
  "DDLongLatNotation": "á_Decimal Degrees  - Longitude/Latitude____________Ó",
  "DDMLatLongNotation": "á_Degrees Decimal Minutes - Latitude/Longitude______________Ó",
  "DDMLongLatNotation": "á_Degrees Decimal Minutes - Longitude/Latitude______________Ó",
  "DMSLatLongNotation": "á_Degrees Minutes Seconds - Latitude/Longitude______________Ó",
  "DMSLongLatNotation": "á_Degrees Minutes Seconds - Longitude/Latitude______________Ó",
  "GARSNotation": "á_GARS__Ó",
  "GEOREFNotation": "á_GEOREF___Ó",
  "MGRSNotation": "á_MGRS__Ó",
  "USNGNotation": "á_USNG__Ó",
  "UTMBandNotation": "á_UTM - Band Letter______Ó",
  "UTMHemNotation": "á_UTM - Hemisphere (N/S)________Ó"
});