define({
  "gridTabLabel": "æ_Grid__Â",
  "labelTabLabel": "æ_Labels___Â",
  "referenceSystemTabLabel": "æ_Reference System______Â",
  "gridTabDescription": "æ_Set the appearance and behavior of the grid cells________________Â.",
  "cellOutlineColor": "æ_Cell Outine color______Â",
  "cellFillColor": "æ_Cell Fill color______Â",
  "transparency": "æ_Transparency_____Â",
  "cellShapeDropDown": "æ_Cell Shape____Â",
  "default": "æ_Rectangle____Â",
  "hexagon": "æ_Hexagon___Â",
  "cellUnitsDropDown": "æ_Cell Units____Â",
  "miles": "æ_Miles___Â",
  "kilometers": "æ_Kilometers____Â",
  "feet": "æ_Feet__Â",
  "meters": "æ_Meters___Â",
  "yards": "æ_Yards___Â",
  "nautical-miles": "æ_Nautical Miles_____Â",
  "gridOriginDropDown": "æ_Grid Origin____Â",
  "lowerLeft": "æ_Lower-Left____Â",
  "lowerRight": "æ_Lower-Right____Â",
  "upperLeft": "æ_Upper-Left____Â",
  "upperRight": "æ_Upper-Right____Â",
  "center": "æ_Center___Â",
  "labelTabDescription": "æ_Set the appearance and behavior of the grid labels________________Â.",
  "labelSettings": "æ_Label Style____Â",
  "font": "æ_Font__Â",
  "textSize": "æ_Text Size____Â",
  "textColor": "æ_Text Color____Â",
  "halo": "æ_Halo__Â",
  "show": "æ_Show__Â",
  "labelTypeDropDown": "æ_Label Type____Â",
  "alphaNumeric": "æ_Alpha-Numeric_____Â",
  "alphaAlpha": "æ_Alpha-Alpha____Â",
  "numeric": "æ_Numeric___Â",
  "labelDirectionDropDown": "æ_Label Direction______Â",
  "horizontal": "æ_Horizontal____Â",
  "vertical": "æ_Vertical___Â",
  "labelOriginDropDown": "æ_Label Origin_____Â",
  "referenceSystemlTabDescription": "æ_Set the default reference system___________Â.",
  "MGRS": "æ_MGRS__Â",
  "USNG": "æ_USNG__Â",
  "lockSettings": "æ_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________Â"
});