define({
  "gridTabLabel": "Å_Grid__ö",
  "labelTabLabel": "Å_Labels___ö",
  "referenceSystemTabLabel": "Å_Reference System______ö",
  "gridTabDescription": "Å_Set the appearance and behavior of the grid cells________________ö.",
  "cellOutlineColor": "Å_Cell Outine color______ö",
  "cellFillColor": "Å_Cell Fill color______ö",
  "transparency": "Å_Transparency_____ö",
  "cellShapeDropDown": "Å_Cell Shape____ö",
  "default": "Å_Rectangle____ö",
  "hexagon": "Å_Hexagon___ö",
  "cellUnitsDropDown": "Å_Cell Units____ö",
  "miles": "Å_Miles___ö",
  "kilometers": "Å_Kilometers____ö",
  "feet": "Å_Feet__ö",
  "meters": "Å_Meters___ö",
  "yards": "Å_Yards___ö",
  "nautical-miles": "Å_Nautical Miles_____ö",
  "gridOriginDropDown": "Å_Grid Origin____ö",
  "lowerLeft": "Å_Lower-Left____ö",
  "lowerRight": "Å_Lower-Right____ö",
  "upperLeft": "Å_Upper-Left____ö",
  "upperRight": "Å_Upper-Right____ö",
  "center": "Å_Center___ö",
  "labelTabDescription": "Å_Set the appearance and behavior of the grid labels________________ö.",
  "labelSettings": "Å_Label Style____ö",
  "font": "Å_Font__ö",
  "textSize": "Å_Text Size____ö",
  "textColor": "Å_Text Color____ö",
  "halo": "Å_Halo__ö",
  "show": "Å_Show__ö",
  "labelTypeDropDown": "Å_Label Type____ö",
  "alphaNumeric": "Å_Alpha-Numeric_____ö",
  "alphaAlpha": "Å_Alpha-Alpha____ö",
  "numeric": "Å_Numeric___ö",
  "labelDirectionDropDown": "Å_Label Direction______ö",
  "horizontal": "Å_Horizontal____ö",
  "vertical": "Å_Vertical___ö",
  "labelOriginDropDown": "Å_Label Origin_____ö",
  "referenceSystemlTabDescription": "Å_Set the default reference system___________ö.",
  "MGRS": "Å_MGRS__ö",
  "USNG": "Å_USNG__ö",
  "lockSettings": "Å_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________ö"
});