define({
  "gridTabLabel": "ก้_Grid__ษฺ",
  "labelTabLabel": "ก้_Labels___ษฺ",
  "referenceSystemTabLabel": "ก้_Reference System______ษฺ",
  "gridTabDescription": "ก้_Set the appearance and behavior of the grid cells________________ษฺ.",
  "cellOutlineColor": "ก้_Cell Outine color______ษฺ",
  "cellFillColor": "ก้_Cell Fill color______ษฺ",
  "transparency": "ก้_Transparency_____ษฺ",
  "cellShapeDropDown": "ก้_Cell Shape____ษฺ",
  "default": "ก้_Rectangle____ษฺ",
  "hexagon": "ก้_Hexagon___ษฺ",
  "cellUnitsDropDown": "ก้_Cell Units____ษฺ",
  "miles": "ก้_Miles___ษฺ",
  "kilometers": "ก้_Kilometers____ษฺ",
  "feet": "ก้_Feet__ษฺ",
  "meters": "ก้_Meters___ษฺ",
  "yards": "ก้_Yards___ษฺ",
  "nautical-miles": "ก้_Nautical Miles_____ษฺ",
  "gridOriginDropDown": "ก้_Grid Origin____ษฺ",
  "lowerLeft": "ก้_Lower-Left____ษฺ",
  "lowerRight": "ก้_Lower-Right____ษฺ",
  "upperLeft": "ก้_Upper-Left____ษฺ",
  "upperRight": "ก้_Upper-Right____ษฺ",
  "center": "ก้_Center___ษฺ",
  "labelTabDescription": "ก้_Set the appearance and behavior of the grid labels________________ษฺ.",
  "labelSettings": "ก้_Label Style____ษฺ",
  "font": "ก้_Font__ษฺ",
  "textSize": "ก้_Text Size____ษฺ",
  "textColor": "ก้_Text Color____ษฺ",
  "halo": "ก้_Halo__ษฺ",
  "show": "ก้_Show__ษฺ",
  "labelTypeDropDown": "ก้_Label Type____ษฺ",
  "alphaNumeric": "ก้_Alpha-Numeric_____ษฺ",
  "alphaAlpha": "ก้_Alpha-Alpha____ษฺ",
  "numeric": "ก้_Numeric___ษฺ",
  "labelDirectionDropDown": "ก้_Label Direction______ษฺ",
  "horizontal": "ก้_Horizontal____ษฺ",
  "vertical": "ก้_Vertical___ษฺ",
  "labelOriginDropDown": "ก้_Label Origin_____ษฺ",
  "referenceSystemlTabDescription": "ก้_Set the default reference system___________ษฺ.",
  "MGRS": "ก้_MGRS__ษฺ",
  "USNG": "ก้_USNG__ษฺ",
  "lockSettings": "ก้_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________ษฺ"
});