define({
  "_widgetLabel": "Ă_Gridded Reference Graphic_________ș",
  "newGRGFromAreaButtonLabel": "Ă_Define a Grid from an Area_________ș",
  "newGRGFromPointButtonLabel": "Ă_Define a Grid from a Point_________ș",
  "newGRGFromAreaTitle": "Ă_Define a Grid from an Area_________ș",
  "newGRGFromPointTitle": "Ă_Define a Grid from a Point_________ș",
  "newGRGBySizeButtonLabel": "Ă_By Dimension_____ș",
  "newGRGFromRefSystemButtonLabel": "Ă_By Reference System_______ș",
  "newGRGByTimeLabel": "Ă_By Time and Speed______ș",
  "newGRGFromNonStandardButtonLabel": "Ă_Define Non-Standard Grid________ș",
  "newGRGAreaBySizeTitle": "Ă_GRG from an Area by Dimension__________ș",
  "newGRGAreaBySizeDefineAreaLabel": "Ă_GRG Area___ș",
  "addGRGAreaPolygonToolTip": "Ă_Draw GRG Area using polygon_________ș",
  "addGRGAreaExtentToolTip": "Ă_Draw GRG Area using extent_________ș",
  "rotation": "Ă_Grid Rotation_____ș",
  "numberRowsColumnsLabel": "Ă_Define number of rows and columns___________ș",
  "newGRGAreaByRefSystemTitle": "Ă_GRG from an Area by Reference System____________ș",
  "gridSize": "Ă_Grid Size____ș",
  "UTMZoneandBand": "Ă_Grid Zone____ș",
  "100000m": "Ă_100000 meter_____ș",
  "10000m": "Ă_10000 meter____ș",
  "1000m": "Ă_1000 meter____ș",
  "100m": "Ă_100 meter____ș",
  "10m": "Ă_10 meter___ș",
  "clipGrid": "Ă_Clip Grid to GRG Area_______ș",
  "newGRGAreaFromNonStandardTitle": "Ă_New NRG___ș",
  "newGRGPointBySizeTitle": "Ă_GRG from Point by Dimension_________ș",
  "newGRGPointByRefSystemTitle": "Ă_GRG from Point by Reference System___________ș",
  "newGRGPointByTimeTitle": "Ă_GRG from Point using Time and Speed____________ș",
  "time": "Ă_Time__ș",
  "rate": "Ă_Speed___ș",
  "hours": "Ă_Hours___ș",
  "minutes": "Ă_Minutes___ș",
  "seconds": "Ă_Seconds___ș",
  "ftPerSec": "Ă_Feet / second_____ș",
  "ftPerHour": "Ă_Feet / hour____ș",
  "kmPerSec": "Ă_Kilometers / second_______ș",
  "kmPerHour": "Ă_Kilometers / hour______ș",
  "mPerSec": "Ă_Meters / second______ș",
  "mPerHour": "Ă_Meters / hour_____ș",
  "miPerSec": "Ă_Miles / second_____ș",
  "miPerHour": "Ă_Miles / hour_____ș",
  "nMPerSec": "Ă_Nautical Miles / second________ș",
  "nMPerHour": "Ă_Nautical Miles / hour_______ș",
  "settingsTitle": "Ă_Settings___ș",
  "labelSettingsLabel": "Ă_Label Settings_____ș",
  "labelSettingsButtonLabel": "Ă_Configure Label Settings________ș",
  "gridSettingsLabel": "Ă_Grid Settings_____ș",
  "gridSettingsButtonLabel": "Ă_Configure Grid Settings________ș",
  "transparency": "Ă_Transparency_____ș",
  "labelStyle": "Ă_Label Style____ș",
  "font": "Ă_Font__ș",
  "textSize": "Ă_Text Size____ș",
  "textColor": "Ă_Text Color____ș",
  "halo": "Ă_Halo__ș",
  "show": "Ă_Show__ș",
  "lockSettings": "Ă_Settings have been locked by the application owner________________ș",
  "gridSettings": {
    "cellShape": "Ă_Cell Shape____ș",
    "cellUnits": "Ă_Cell Units____ș",
    "cellOutline": "Ă_Cell Outline Settings_______ș",
    "cellFill": "Ă_Cell Fill Settings______ș",
    "gridReferenceSystem": "Ă_Reference System______ș",
    "gridDatum": "Ă_Datum: WGS84_____ș",
    "labelStartPosition": "Ă_Label Origin_____ș",
    "labelType": "Ă_Label Type____ș",
    "labelDirection": "Ă_Label Direction______ș",
    "gridOrigin": "Ă_Grid Origin____ș",
    "default": "Ă_Rectangle____ș",
    "hexagon": "Ă_Hexagon___ș",
    "miles": "Ă_Miles___ș",
    "kilometers": "Ă_Kilometers____ș",
    "feet": "Ă_Feet__ș",
    "meters": "Ă_Meters___ș",
    "yards": "Ă_Yards___ș",
    "nautical-miles": "Ă_Nautical Miles_____ș",
    "lowerLeft": "Ă_Lower-Left____ș",
    "lowerRight": "Ă_Lower-Right____ș",
    "upperLeft": "Ă_Upper-Left____ș",
    "upperRight": "Ă_Upper-Right____ș",
    "center": "Ă_Center___ș",
    "alphaNumeric": "Ă_Alpha-Numeric_____ș",
    "alphaAlpha": "Ă_Alpha-Alpha____ș",
    "numeric": "Ă_Numeric___ș",
    "horizontal": "Ă_Horizontal____ș",
    "vertical": "Ă_Vertical___ș",
    "MGRS": "Ă_MGRS__ș",
    "USNG": "Ă_USNG__ș",
    "showLabels": "Ă_Show Labels____ș"
  },
  "publishTitle": "Ă_Publish GRG to Portal_______ș",
  "publishGRGBtn": "Ă_Publish___ș",
  "GRGLayerName": "Ă_Published GRG Layer Name________ș",
  "invalidGRGLayerName": "Ă_Layer name must only contain alpha-numeric characters and underscores______________________ș",
  "missingGRGLayerName": "Ă_You must enter a name for the GRG___________ș",
  "publishingFailedLayerExists": "Ă_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ș.",
  "checkService": "Ă_Check Service: {0}______ș",
  "createService": "Ă_Create Service: {0}_______ș",
  "unableToCreate": "Ă_Unable to create: {0}_______ș",
  "addToDefinition": "Ă_Add to definition: {0}________ș",
  "successfullyPublished": "Ă_Successfully published web layer{0}Manage the web layer__________________ș",
  "userRole": "Ă_Unable to create service because user does not have permissions____________________ș",
  "createGRGBtn": "Ă_Create GRG____ș",
  "clearGRGBtn": "Ă_Clear___ș",
  "labelFormat": "Ă_Label Format_____ș",
  "helpIconTooltip": "Ă_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________ș",
  "addPointToolTip": "Ă_Add GRG Origin_____ș",
  "cellWidth": "Ă_Cell Width (x)_____ș",
  "cellHeight": "Ă_Cell Height (y)______ș",
  "invalidNumberMessage": "Ă_The value entered is not valid__________ș",
  "invalidRangeMessage": "Ă_Value must be greater than 0_________ș",
  "gridAngleInvalidRangeMessage": "Ă_Value must be between -89.9 and 89.9____________ș",
  "formatIconTooltip": "Ă_Format Input_____ș",
  "coordInputLabel": "Ă_GRG Origin (DD)______ș",
  "setCoordFormat": "Ă_Set Coordinate Format String_________ș",
  "prefixNumbers": "Ă_Add '+/-' prefix to positive and negative numbers________________ș",
  "cancelBtn": "Ă_Cancel___ș",
  "applyBtn": "Ă_Apply___ș",
  "comfirmInputNotation": "Ă_Confirm Input Notation________ș",
  "notationsMatch": "Ă_notations match your input please confirm which you would like to use______________________ș:",
  "numberOfCellsHorizontal": "Ă_# Horizontal Cells______ș",
  "numberOfCellsVertical": "Ă_# Vertical Cells______ș",
  "gridAngle": "Ă_Grid Rotation_____ș",
  "tooManyCellsErrorMessage": "Ă_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________ș.",
  "missingParametersMessage": "Ă_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________ș",
  "missingOriginParametersMessage": "Ă_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________ș",
  "invalidWidthHeightParametersMessage": "Ă_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________ș",
  "invalidHorizontalVerticalParametersMessage": "Ă_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________ș",
  "drawPointToolTip": "Ă_Click to add GRG origin point__________ș",
  "missingLayerNameMessage": "Ă_You must enter a valid layer name before you can publish__________________ș",
  "parseCoordinatesError": "Ă_Unable to parse coordinates. Please check your input_________________ș.",
  "grgPolarRegionError": "Ă_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________ș.",
  "grgPolarOriginError": "Ă_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________ș.",
  "DD": "Ă_DD__ș",
  "DDM": "Ă_DDM__ș",
  "DMS": "Ă_DMS__ș",
  "DDRev": "Ă_DDRev___ș",
  "DDMRev": "Ă_DDMRev___ș",
  "DMSRev": "Ă_DMSRev___ș",
  "USNG": "Ă_USNG__ș",
  "MGRS": "Ă_MGRS__ș",
  "UTM_H": "Ă_UTM (H)___ș",
  "UTM": "Ă_UTM__ș",
  "GARS": "Ă_GARS__ș",
  "GEOREF": "Ă_GEOREF___ș",
  "DDLatLongNotation": "Ă_Decimal Degrees - Latitude/Longitude____________ș",
  "DDLongLatNotation": "Ă_Decimal Degrees  - Longitude/Latitude____________ș",
  "DDMLatLongNotation": "Ă_Degrees Decimal Minutes - Latitude/Longitude______________ș",
  "DDMLongLatNotation": "Ă_Degrees Decimal Minutes - Longitude/Latitude______________ș",
  "DMSLatLongNotation": "Ă_Degrees Minutes Seconds - Latitude/Longitude______________ș",
  "DMSLongLatNotation": "Ă_Degrees Minutes Seconds - Longitude/Latitude______________ș",
  "GARSNotation": "Ă_GARS__ș",
  "GEOREFNotation": "Ă_GEOREF___ș",
  "MGRSNotation": "Ă_MGRS__ș",
  "USNGNotation": "Ă_USNG__ș",
  "UTMBandNotation": "Ă_UTM - Band Letter______ș",
  "UTMHemNotation": "Ă_UTM - Hemisphere (N/S)________ș"
});