define({
  "_widgetLabel": "Ĳ_Gridded Reference Graphic_________ä",
  "newGRGFromAreaButtonLabel": "Ĳ_Define a Grid from an Area_________ä",
  "newGRGFromPointButtonLabel": "Ĳ_Define a Grid from a Point_________ä",
  "newGRGFromAreaTitle": "Ĳ_Define a Grid from an Area_________ä",
  "newGRGFromPointTitle": "Ĳ_Define a Grid from a Point_________ä",
  "newGRGBySizeButtonLabel": "Ĳ_By Dimension_____ä",
  "newGRGFromRefSystemButtonLabel": "Ĳ_By Reference System_______ä",
  "newGRGByTimeLabel": "Ĳ_By Time and Speed______ä",
  "newGRGFromNonStandardButtonLabel": "Ĳ_Define Non-Standard Grid________ä",
  "newGRGAreaBySizeTitle": "Ĳ_GRG from an Area by Dimension__________ä",
  "newGRGAreaBySizeDefineAreaLabel": "Ĳ_GRG Area___ä",
  "addGRGAreaPolygonToolTip": "Ĳ_Draw GRG Area using polygon_________ä",
  "addGRGAreaExtentToolTip": "Ĳ_Draw GRG Area using extent_________ä",
  "rotation": "Ĳ_Grid Rotation_____ä",
  "numberRowsColumnsLabel": "Ĳ_Define number of rows and columns___________ä",
  "newGRGAreaByRefSystemTitle": "Ĳ_GRG from an Area by Reference System____________ä",
  "gridSize": "Ĳ_Grid Size____ä",
  "UTMZoneandBand": "Ĳ_Grid Zone____ä",
  "100000m": "Ĳ_100000 meter_____ä",
  "10000m": "Ĳ_10000 meter____ä",
  "1000m": "Ĳ_1000 meter____ä",
  "100m": "Ĳ_100 meter____ä",
  "10m": "Ĳ_10 meter___ä",
  "clipGrid": "Ĳ_Clip Grid to GRG Area_______ä",
  "newGRGAreaFromNonStandardTitle": "Ĳ_New NRG___ä",
  "newGRGPointBySizeTitle": "Ĳ_GRG from Point by Dimension_________ä",
  "newGRGPointByRefSystemTitle": "Ĳ_GRG from Point by Reference System___________ä",
  "newGRGPointByTimeTitle": "Ĳ_GRG from Point using Time and Speed____________ä",
  "time": "Ĳ_Time__ä",
  "rate": "Ĳ_Speed___ä",
  "hours": "Ĳ_Hours___ä",
  "minutes": "Ĳ_Minutes___ä",
  "seconds": "Ĳ_Seconds___ä",
  "ftPerSec": "Ĳ_Feet / second_____ä",
  "ftPerHour": "Ĳ_Feet / hour____ä",
  "kmPerSec": "Ĳ_Kilometers / second_______ä",
  "kmPerHour": "Ĳ_Kilometers / hour______ä",
  "mPerSec": "Ĳ_Meters / second______ä",
  "mPerHour": "Ĳ_Meters / hour_____ä",
  "miPerSec": "Ĳ_Miles / second_____ä",
  "miPerHour": "Ĳ_Miles / hour_____ä",
  "nMPerSec": "Ĳ_Nautical Miles / second________ä",
  "nMPerHour": "Ĳ_Nautical Miles / hour_______ä",
  "settingsTitle": "Ĳ_Settings___ä",
  "labelSettingsLabel": "Ĳ_Label Settings_____ä",
  "labelSettingsButtonLabel": "Ĳ_Configure Label Settings________ä",
  "gridSettingsLabel": "Ĳ_Grid Settings_____ä",
  "gridSettingsButtonLabel": "Ĳ_Configure Grid Settings________ä",
  "transparency": "Ĳ_Transparency_____ä",
  "labelStyle": "Ĳ_Label Style____ä",
  "font": "Ĳ_Font__ä",
  "textSize": "Ĳ_Text Size____ä",
  "textColor": "Ĳ_Text Color____ä",
  "halo": "Ĳ_Halo__ä",
  "show": "Ĳ_Show__ä",
  "lockSettings": "Ĳ_Settings have been locked by the application owner________________ä",
  "gridSettings": {
    "cellShape": "Ĳ_Cell Shape____ä",
    "cellUnits": "Ĳ_Cell Units____ä",
    "cellOutline": "Ĳ_Cell Outline Settings_______ä",
    "cellFill": "Ĳ_Cell Fill Settings______ä",
    "gridReferenceSystem": "Ĳ_Reference System______ä",
    "gridDatum": "Ĳ_Datum: WGS84_____ä",
    "labelStartPosition": "Ĳ_Label Origin_____ä",
    "labelType": "Ĳ_Label Type____ä",
    "labelDirection": "Ĳ_Label Direction______ä",
    "gridOrigin": "Ĳ_Grid Origin____ä",
    "default": "Ĳ_Rectangle____ä",
    "hexagon": "Ĳ_Hexagon___ä",
    "miles": "Ĳ_Miles___ä",
    "kilometers": "Ĳ_Kilometers____ä",
    "feet": "Ĳ_Feet__ä",
    "meters": "Ĳ_Meters___ä",
    "yards": "Ĳ_Yards___ä",
    "nautical-miles": "Ĳ_Nautical Miles_____ä",
    "lowerLeft": "Ĳ_Lower-Left____ä",
    "lowerRight": "Ĳ_Lower-Right____ä",
    "upperLeft": "Ĳ_Upper-Left____ä",
    "upperRight": "Ĳ_Upper-Right____ä",
    "center": "Ĳ_Center___ä",
    "alphaNumeric": "Ĳ_Alpha-Numeric_____ä",
    "alphaAlpha": "Ĳ_Alpha-Alpha____ä",
    "numeric": "Ĳ_Numeric___ä",
    "horizontal": "Ĳ_Horizontal____ä",
    "vertical": "Ĳ_Vertical___ä",
    "MGRS": "Ĳ_MGRS__ä",
    "USNG": "Ĳ_USNG__ä",
    "showLabels": "Ĳ_Show Labels____ä"
  },
  "publishTitle": "Ĳ_Publish GRG to Portal_______ä",
  "publishGRGBtn": "Ĳ_Publish___ä",
  "GRGLayerName": "Ĳ_Published GRG Layer Name________ä",
  "invalidGRGLayerName": "Ĳ_Layer name must only contain alpha-numeric characters and underscores______________________ä",
  "missingGRGLayerName": "Ĳ_You must enter a name for the GRG___________ä",
  "publishingFailedLayerExists": "Ĳ_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ä.",
  "checkService": "Ĳ_Check Service: {0}______ä",
  "createService": "Ĳ_Create Service: {0}_______ä",
  "unableToCreate": "Ĳ_Unable to create: {0}_______ä",
  "addToDefinition": "Ĳ_Add to definition: {0}________ä",
  "successfullyPublished": "Ĳ_Successfully published web layer{0}Manage the web layer__________________ä",
  "userRole": "Ĳ_Unable to create service because user does not have permissions____________________ä",
  "createGRGBtn": "Ĳ_Create GRG____ä",
  "clearGRGBtn": "Ĳ_Clear___ä",
  "labelFormat": "Ĳ_Label Format_____ä",
  "helpIconTooltip": "Ĳ_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________ä",
  "addPointToolTip": "Ĳ_Add GRG Origin_____ä",
  "cellWidth": "Ĳ_Cell Width (x)_____ä",
  "cellHeight": "Ĳ_Cell Height (y)______ä",
  "invalidNumberMessage": "Ĳ_The value entered is not valid__________ä",
  "invalidRangeMessage": "Ĳ_Value must be greater than 0_________ä",
  "gridAngleInvalidRangeMessage": "Ĳ_Value must be between -89.9 and 89.9____________ä",
  "formatIconTooltip": "Ĳ_Format Input_____ä",
  "coordInputLabel": "Ĳ_GRG Origin (DD)______ä",
  "setCoordFormat": "Ĳ_Set Coordinate Format String_________ä",
  "prefixNumbers": "Ĳ_Add '+/-' prefix to positive and negative numbers________________ä",
  "cancelBtn": "Ĳ_Cancel___ä",
  "applyBtn": "Ĳ_Apply___ä",
  "comfirmInputNotation": "Ĳ_Confirm Input Notation________ä",
  "notationsMatch": "Ĳ_notations match your input please confirm which you would like to use______________________ä:",
  "numberOfCellsHorizontal": "Ĳ_# Horizontal Cells______ä",
  "numberOfCellsVertical": "Ĳ_# Vertical Cells______ä",
  "gridAngle": "Ĳ_Grid Rotation_____ä",
  "tooManyCellsErrorMessage": "Ĳ_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________ä.",
  "missingParametersMessage": "Ĳ_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________ä",
  "missingOriginParametersMessage": "Ĳ_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________ä",
  "invalidWidthHeightParametersMessage": "Ĳ_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________ä",
  "invalidHorizontalVerticalParametersMessage": "Ĳ_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________ä",
  "drawPointToolTip": "Ĳ_Click to add GRG origin point__________ä",
  "missingLayerNameMessage": "Ĳ_You must enter a valid layer name before you can publish__________________ä",
  "parseCoordinatesError": "Ĳ_Unable to parse coordinates. Please check your input_________________ä.",
  "grgPolarRegionError": "Ĳ_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________ä.",
  "grgPolarOriginError": "Ĳ_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________ä.",
  "DD": "Ĳ_DD__ä",
  "DDM": "Ĳ_DDM__ä",
  "DMS": "Ĳ_DMS__ä",
  "DDRev": "Ĳ_DDRev___ä",
  "DDMRev": "Ĳ_DDMRev___ä",
  "DMSRev": "Ĳ_DMSRev___ä",
  "USNG": "Ĳ_USNG__ä",
  "MGRS": "Ĳ_MGRS__ä",
  "UTM_H": "Ĳ_UTM (H)___ä",
  "UTM": "Ĳ_UTM__ä",
  "GARS": "Ĳ_GARS__ä",
  "GEOREF": "Ĳ_GEOREF___ä",
  "DDLatLongNotation": "Ĳ_Decimal Degrees - Latitude/Longitude____________ä",
  "DDLongLatNotation": "Ĳ_Decimal Degrees  - Longitude/Latitude____________ä",
  "DDMLatLongNotation": "Ĳ_Degrees Decimal Minutes - Latitude/Longitude______________ä",
  "DDMLongLatNotation": "Ĳ_Degrees Decimal Minutes - Longitude/Latitude______________ä",
  "DMSLatLongNotation": "Ĳ_Degrees Minutes Seconds - Latitude/Longitude______________ä",
  "DMSLongLatNotation": "Ĳ_Degrees Minutes Seconds - Longitude/Latitude______________ä",
  "GARSNotation": "Ĳ_GARS__ä",
  "GEOREFNotation": "Ĳ_GEOREF___ä",
  "MGRSNotation": "Ĳ_MGRS__ä",
  "USNGNotation": "Ĳ_USNG__ä",
  "UTMBandNotation": "Ĳ_UTM - Band Letter______ä",
  "UTMHemNotation": "Ĳ_UTM - Hemisphere (N/S)________ä"
});