define({
  "_widgetLabel": "ł_Gridded Reference Graphic_________ą",
  "newGRGFromAreaButtonLabel": "ł_Define a Grid from an Area_________ą",
  "newGRGFromPointButtonLabel": "ł_Define a Grid from a Point_________ą",
  "newGRGFromAreaTitle": "ł_Define a Grid from an Area_________ą",
  "newGRGFromPointTitle": "ł_Define a Grid from a Point_________ą",
  "newGRGBySizeButtonLabel": "ł_By Dimension_____ą",
  "newGRGFromRefSystemButtonLabel": "ł_By Reference System_______ą",
  "newGRGByTimeLabel": "ł_By Time and Speed______ą",
  "newGRGFromNonStandardButtonLabel": "ł_Define Non-Standard Grid________ą",
  "newGRGAreaBySizeTitle": "ł_GRG from an Area by Dimension__________ą",
  "newGRGAreaBySizeDefineAreaLabel": "ł_GRG Area___ą",
  "addGRGAreaPolygonToolTip": "ł_Draw GRG Area using polygon_________ą",
  "addGRGAreaExtentToolTip": "ł_Draw GRG Area using extent_________ą",
  "rotation": "ł_Grid Rotation_____ą",
  "numberRowsColumnsLabel": "ł_Define number of rows and columns___________ą",
  "newGRGAreaByRefSystemTitle": "ł_GRG from an Area by Reference System____________ą",
  "gridSize": "ł_Grid Size____ą",
  "UTMZoneandBand": "ł_Grid Zone____ą",
  "100000m": "ł_100000 meter_____ą",
  "10000m": "ł_10000 meter____ą",
  "1000m": "ł_1000 meter____ą",
  "100m": "ł_100 meter____ą",
  "10m": "ł_10 meter___ą",
  "clipGrid": "ł_Clip Grid to GRG Area_______ą",
  "newGRGAreaFromNonStandardTitle": "ł_New NRG___ą",
  "newGRGPointBySizeTitle": "ł_GRG from Point by Dimension_________ą",
  "newGRGPointByRefSystemTitle": "ł_GRG from Point by Reference System___________ą",
  "newGRGPointByTimeTitle": "ł_GRG from Point using Time and Speed____________ą",
  "time": "ł_Time__ą",
  "rate": "ł_Speed___ą",
  "hours": "ł_Hours___ą",
  "minutes": "ł_Minutes___ą",
  "seconds": "ł_Seconds___ą",
  "ftPerSec": "ł_Feet / second_____ą",
  "ftPerHour": "ł_Feet / hour____ą",
  "kmPerSec": "ł_Kilometers / second_______ą",
  "kmPerHour": "ł_Kilometers / hour______ą",
  "mPerSec": "ł_Meters / second______ą",
  "mPerHour": "ł_Meters / hour_____ą",
  "miPerSec": "ł_Miles / second_____ą",
  "miPerHour": "ł_Miles / hour_____ą",
  "nMPerSec": "ł_Nautical Miles / second________ą",
  "nMPerHour": "ł_Nautical Miles / hour_______ą",
  "settingsTitle": "ł_Settings___ą",
  "labelSettingsLabel": "ł_Label Settings_____ą",
  "labelSettingsButtonLabel": "ł_Configure Label Settings________ą",
  "gridSettingsLabel": "ł_Grid Settings_____ą",
  "gridSettingsButtonLabel": "ł_Configure Grid Settings________ą",
  "transparency": "ł_Transparency_____ą",
  "labelStyle": "ł_Label Style____ą",
  "font": "ł_Font__ą",
  "textSize": "ł_Text Size____ą",
  "textColor": "ł_Text Color____ą",
  "halo": "ł_Halo__ą",
  "show": "ł_Show__ą",
  "lockSettings": "ł_Settings have been locked by the application owner________________ą",
  "gridSettings": {
    "cellShape": "ł_Cell Shape____ą",
    "cellUnits": "ł_Cell Units____ą",
    "cellOutline": "ł_Cell Outline Settings_______ą",
    "cellFill": "ł_Cell Fill Settings______ą",
    "gridReferenceSystem": "ł_Reference System______ą",
    "gridDatum": "ł_Datum: WGS84_____ą",
    "labelStartPosition": "ł_Label Origin_____ą",
    "labelType": "ł_Label Type____ą",
    "labelDirection": "ł_Label Direction______ą",
    "gridOrigin": "ł_Grid Origin____ą",
    "default": "ł_Rectangle____ą",
    "hexagon": "ł_Hexagon___ą",
    "miles": "ł_Miles___ą",
    "kilometers": "ł_Kilometers____ą",
    "feet": "ł_Feet__ą",
    "meters": "ł_Meters___ą",
    "yards": "ł_Yards___ą",
    "nautical-miles": "ł_Nautical Miles_____ą",
    "lowerLeft": "ł_Lower-Left____ą",
    "lowerRight": "ł_Lower-Right____ą",
    "upperLeft": "ł_Upper-Left____ą",
    "upperRight": "ł_Upper-Right____ą",
    "center": "ł_Center___ą",
    "alphaNumeric": "ł_Alpha-Numeric_____ą",
    "alphaAlpha": "ł_Alpha-Alpha____ą",
    "numeric": "ł_Numeric___ą",
    "horizontal": "ł_Horizontal____ą",
    "vertical": "ł_Vertical___ą",
    "MGRS": "ł_MGRS__ą",
    "USNG": "ł_USNG__ą",
    "showLabels": "ł_Show Labels____ą"
  },
  "publishTitle": "ł_Publish GRG to Portal_______ą",
  "publishGRGBtn": "ł_Publish___ą",
  "GRGLayerName": "ł_Published GRG Layer Name________ą",
  "invalidGRGLayerName": "ł_Layer name must only contain alpha-numeric characters and underscores______________________ą",
  "missingGRGLayerName": "ł_You must enter a name for the GRG___________ą",
  "publishingFailedLayerExists": "ł_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ą.",
  "checkService": "ł_Check Service: {0}______ą",
  "createService": "ł_Create Service: {0}_______ą",
  "unableToCreate": "ł_Unable to create: {0}_______ą",
  "addToDefinition": "ł_Add to definition: {0}________ą",
  "successfullyPublished": "ł_Successfully published web layer{0}Manage the web layer__________________ą",
  "userRole": "ł_Unable to create service because user does not have permissions____________________ą",
  "createGRGBtn": "ł_Create GRG____ą",
  "clearGRGBtn": "ł_Clear___ą",
  "labelFormat": "ł_Label Format_____ą",
  "helpIconTooltip": "ł_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________ą",
  "addPointToolTip": "ł_Add GRG Origin_____ą",
  "cellWidth": "ł_Cell Width (x)_____ą",
  "cellHeight": "ł_Cell Height (y)______ą",
  "invalidNumberMessage": "ł_The value entered is not valid__________ą",
  "invalidRangeMessage": "ł_Value must be greater than 0_________ą",
  "gridAngleInvalidRangeMessage": "ł_Value must be between -89.9 and 89.9____________ą",
  "formatIconTooltip": "ł_Format Input_____ą",
  "coordInputLabel": "ł_GRG Origin (DD)______ą",
  "setCoordFormat": "ł_Set Coordinate Format String_________ą",
  "prefixNumbers": "ł_Add '+/-' prefix to positive and negative numbers________________ą",
  "cancelBtn": "ł_Cancel___ą",
  "applyBtn": "ł_Apply___ą",
  "comfirmInputNotation": "ł_Confirm Input Notation________ą",
  "notationsMatch": "ł_notations match your input please confirm which you would like to use______________________ą:",
  "numberOfCellsHorizontal": "ł_# Horizontal Cells______ą",
  "numberOfCellsVertical": "ł_# Vertical Cells______ą",
  "gridAngle": "ł_Grid Rotation_____ą",
  "tooManyCellsErrorMessage": "ł_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________ą.",
  "missingParametersMessage": "ł_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________ą",
  "missingOriginParametersMessage": "ł_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________ą",
  "invalidWidthHeightParametersMessage": "ł_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________ą",
  "invalidHorizontalVerticalParametersMessage": "ł_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________ą",
  "drawPointToolTip": "ł_Click to add GRG origin point__________ą",
  "missingLayerNameMessage": "ł_You must enter a valid layer name before you can publish__________________ą",
  "parseCoordinatesError": "ł_Unable to parse coordinates. Please check your input_________________ą.",
  "grgPolarRegionError": "ł_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________ą.",
  "grgPolarOriginError": "ł_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________ą.",
  "DD": "ł_DD__ą",
  "DDM": "ł_DDM__ą",
  "DMS": "ł_DMS__ą",
  "DDRev": "ł_DDRev___ą",
  "DDMRev": "ł_DDMRev___ą",
  "DMSRev": "ł_DMSRev___ą",
  "USNG": "ł_USNG__ą",
  "MGRS": "ł_MGRS__ą",
  "UTM_H": "ł_UTM (H)___ą",
  "UTM": "ł_UTM__ą",
  "GARS": "ł_GARS__ą",
  "GEOREF": "ł_GEOREF___ą",
  "DDLatLongNotation": "ł_Decimal Degrees - Latitude/Longitude____________ą",
  "DDLongLatNotation": "ł_Decimal Degrees  - Longitude/Latitude____________ą",
  "DDMLatLongNotation": "ł_Degrees Decimal Minutes - Latitude/Longitude______________ą",
  "DDMLongLatNotation": "ł_Degrees Decimal Minutes - Longitude/Latitude______________ą",
  "DMSLatLongNotation": "ł_Degrees Minutes Seconds - Latitude/Longitude______________ą",
  "DMSLongLatNotation": "ł_Degrees Minutes Seconds - Longitude/Latitude______________ą",
  "GARSNotation": "ł_GARS__ą",
  "GEOREFNotation": "ł_GEOREF___ą",
  "MGRSNotation": "ł_MGRS__ą",
  "USNGNotation": "ł_USNG__ą",
  "UTMBandNotation": "ł_UTM - Band Letter______ą",
  "UTMHemNotation": "ł_UTM - Hemisphere (N/S)________ą"
});