define({
  "_widgetLabel": "Å_Gridded Reference Graphic_________ö",
  "newGRGFromAreaButtonLabel": "Å_Define a Grid from an Area_________ö",
  "newGRGFromPointButtonLabel": "Å_Define a Grid from a Point_________ö",
  "newGRGFromAreaTitle": "Å_Define a Grid from an Area_________ö",
  "newGRGFromPointTitle": "Å_Define a Grid from a Point_________ö",
  "newGRGBySizeButtonLabel": "Å_By Dimension_____ö",
  "newGRGFromRefSystemButtonLabel": "Å_By Reference System_______ö",
  "newGRGByTimeLabel": "Å_By Time and Speed______ö",
  "newGRGFromNonStandardButtonLabel": "Å_Define Non-Standard Grid________ö",
  "newGRGAreaBySizeTitle": "Å_GRG from an Area by Dimension__________ö",
  "newGRGAreaBySizeDefineAreaLabel": "Å_GRG Area___ö",
  "addGRGAreaPolygonToolTip": "Å_Draw GRG Area using polygon_________ö",
  "addGRGAreaExtentToolTip": "Å_Draw GRG Area using extent_________ö",
  "rotation": "Å_Grid Rotation_____ö",
  "numberRowsColumnsLabel": "Å_Define number of rows and columns___________ö",
  "newGRGAreaByRefSystemTitle": "Å_GRG from an Area by Reference System____________ö",
  "gridSize": "Å_Grid Size____ö",
  "UTMZoneandBand": "Å_Grid Zone____ö",
  "100000m": "Å_100000 meter_____ö",
  "10000m": "Å_10000 meter____ö",
  "1000m": "Å_1000 meter____ö",
  "100m": "Å_100 meter____ö",
  "10m": "Å_10 meter___ö",
  "clipGrid": "Å_Clip Grid to GRG Area_______ö",
  "newGRGAreaFromNonStandardTitle": "Å_New NRG___ö",
  "newGRGPointBySizeTitle": "Å_GRG from Point by Dimension_________ö",
  "newGRGPointByRefSystemTitle": "Å_GRG from Point by Reference System___________ö",
  "newGRGPointByTimeTitle": "Å_GRG from Point using Time and Speed____________ö",
  "time": "Å_Time__ö",
  "rate": "Å_Speed___ö",
  "hours": "Å_Hours___ö",
  "minutes": "Å_Minutes___ö",
  "seconds": "Å_Seconds___ö",
  "ftPerSec": "Å_Feet / second_____ö",
  "ftPerHour": "Å_Feet / hour____ö",
  "kmPerSec": "Å_Kilometers / second_______ö",
  "kmPerHour": "Å_Kilometers / hour______ö",
  "mPerSec": "Å_Meters / second______ö",
  "mPerHour": "Å_Meters / hour_____ö",
  "miPerSec": "Å_Miles / second_____ö",
  "miPerHour": "Å_Miles / hour_____ö",
  "nMPerSec": "Å_Nautical Miles / second________ö",
  "nMPerHour": "Å_Nautical Miles / hour_______ö",
  "settingsTitle": "Å_Settings___ö",
  "labelSettingsLabel": "Å_Label Settings_____ö",
  "labelSettingsButtonLabel": "Å_Configure Label Settings________ö",
  "gridSettingsLabel": "Å_Grid Settings_____ö",
  "gridSettingsButtonLabel": "Å_Configure Grid Settings________ö",
  "transparency": "Å_Transparency_____ö",
  "labelStyle": "Å_Label Style____ö",
  "font": "Å_Font__ö",
  "textSize": "Å_Text Size____ö",
  "textColor": "Å_Text Color____ö",
  "halo": "Å_Halo__ö",
  "show": "Å_Show__ö",
  "lockSettings": "Å_Settings have been locked by the application owner________________ö",
  "gridSettings": {
    "cellShape": "Å_Cell Shape____ö",
    "cellUnits": "Å_Cell Units____ö",
    "cellOutline": "Å_Cell Outline Settings_______ö",
    "cellFill": "Å_Cell Fill Settings______ö",
    "gridReferenceSystem": "Å_Reference System______ö",
    "gridDatum": "Å_Datum: WGS84_____ö",
    "labelStartPosition": "Å_Label Origin_____ö",
    "labelType": "Å_Label Type____ö",
    "labelDirection": "Å_Label Direction______ö",
    "gridOrigin": "Å_Grid Origin____ö",
    "default": "Å_Rectangle____ö",
    "hexagon": "Å_Hexagon___ö",
    "miles": "Å_Miles___ö",
    "kilometers": "Å_Kilometers____ö",
    "feet": "Å_Feet__ö",
    "meters": "Å_Meters___ö",
    "yards": "Å_Yards___ö",
    "nautical-miles": "Å_Nautical Miles_____ö",
    "lowerLeft": "Å_Lower-Left____ö",
    "lowerRight": "Å_Lower-Right____ö",
    "upperLeft": "Å_Upper-Left____ö",
    "upperRight": "Å_Upper-Right____ö",
    "center": "Å_Center___ö",
    "alphaNumeric": "Å_Alpha-Numeric_____ö",
    "alphaAlpha": "Å_Alpha-Alpha____ö",
    "numeric": "Å_Numeric___ö",
    "horizontal": "Å_Horizontal____ö",
    "vertical": "Å_Vertical___ö",
    "MGRS": "Å_MGRS__ö",
    "USNG": "Å_USNG__ö",
    "showLabels": "Å_Show Labels____ö"
  },
  "publishTitle": "Å_Publish GRG to Portal_______ö",
  "publishGRGBtn": "Å_Publish___ö",
  "GRGLayerName": "Å_Published GRG Layer Name________ö",
  "invalidGRGLayerName": "Å_Layer name must only contain alpha-numeric characters and underscores______________________ö",
  "missingGRGLayerName": "Å_You must enter a name for the GRG___________ö",
  "publishingFailedLayerExists": "Å_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ö.",
  "checkService": "Å_Check Service: {0}______ö",
  "createService": "Å_Create Service: {0}_______ö",
  "unableToCreate": "Å_Unable to create: {0}_______ö",
  "addToDefinition": "Å_Add to definition: {0}________ö",
  "successfullyPublished": "Å_Successfully published web layer{0}Manage the web layer__________________ö",
  "userRole": "Å_Unable to create service because user does not have permissions____________________ö",
  "createGRGBtn": "Å_Create GRG____ö",
  "clearGRGBtn": "Å_Clear___ö",
  "labelFormat": "Å_Label Format_____ö",
  "helpIconTooltip": "Å_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________ö",
  "addPointToolTip": "Å_Add GRG Origin_____ö",
  "cellWidth": "Å_Cell Width (x)_____ö",
  "cellHeight": "Å_Cell Height (y)______ö",
  "invalidNumberMessage": "Å_The value entered is not valid__________ö",
  "invalidRangeMessage": "Å_Value must be greater than 0_________ö",
  "gridAngleInvalidRangeMessage": "Å_Value must be between -89.9 and 89.9____________ö",
  "formatIconTooltip": "Å_Format Input_____ö",
  "coordInputLabel": "Å_GRG Origin (DD)______ö",
  "setCoordFormat": "Å_Set Coordinate Format String_________ö",
  "prefixNumbers": "Å_Add '+/-' prefix to positive and negative numbers________________ö",
  "cancelBtn": "Å_Cancel___ö",
  "applyBtn": "Å_Apply___ö",
  "comfirmInputNotation": "Å_Confirm Input Notation________ö",
  "notationsMatch": "Å_notations match your input please confirm which you would like to use______________________ö:",
  "numberOfCellsHorizontal": "Å_# Horizontal Cells______ö",
  "numberOfCellsVertical": "Å_# Vertical Cells______ö",
  "gridAngle": "Å_Grid Rotation_____ö",
  "tooManyCellsErrorMessage": "Å_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________ö.",
  "missingParametersMessage": "Å_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________ö",
  "missingOriginParametersMessage": "Å_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________ö",
  "invalidWidthHeightParametersMessage": "Å_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________ö",
  "invalidHorizontalVerticalParametersMessage": "Å_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________ö",
  "drawPointToolTip": "Å_Click to add GRG origin point__________ö",
  "missingLayerNameMessage": "Å_You must enter a valid layer name before you can publish__________________ö",
  "parseCoordinatesError": "Å_Unable to parse coordinates. Please check your input_________________ö.",
  "grgPolarRegionError": "Å_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________ö.",
  "grgPolarOriginError": "Å_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________ö.",
  "DD": "Å_DD__ö",
  "DDM": "Å_DDM__ö",
  "DMS": "Å_DMS__ö",
  "DDRev": "Å_DDRev___ö",
  "DDMRev": "Å_DDMRev___ö",
  "DMSRev": "Å_DMSRev___ö",
  "USNG": "Å_USNG__ö",
  "MGRS": "Å_MGRS__ö",
  "UTM_H": "Å_UTM (H)___ö",
  "UTM": "Å_UTM__ö",
  "GARS": "Å_GARS__ö",
  "GEOREF": "Å_GEOREF___ö",
  "DDLatLongNotation": "Å_Decimal Degrees - Latitude/Longitude____________ö",
  "DDLongLatNotation": "Å_Decimal Degrees  - Longitude/Latitude____________ö",
  "DDMLatLongNotation": "Å_Degrees Decimal Minutes - Latitude/Longitude______________ö",
  "DDMLongLatNotation": "Å_Degrees Decimal Minutes - Longitude/Latitude______________ö",
  "DMSLatLongNotation": "Å_Degrees Minutes Seconds - Latitude/Longitude______________ö",
  "DMSLongLatNotation": "Å_Degrees Minutes Seconds - Longitude/Latitude______________ö",
  "GARSNotation": "Å_GARS__ö",
  "GEOREFNotation": "Å_GEOREF___ö",
  "MGRSNotation": "Å_MGRS__ö",
  "USNGNotation": "Å_USNG__ö",
  "UTMBandNotation": "Å_UTM - Band Letter______ö",
  "UTMHemNotation": "Å_UTM - Hemisphere (N/S)________ö"
});