define({
  "_widgetLabel": "כן_Gridded Reference Graphic_________ש",
  "newGRGFromAreaButtonLabel": "כן_Define a Grid from an Area_________ש",
  "newGRGFromPointButtonLabel": "כן_Define a Grid from a Point_________ש",
  "newGRGFromAreaTitle": "כן_Define a Grid from an Area_________ש",
  "newGRGFromPointTitle": "כן_Define a Grid from a Point_________ש",
  "newGRGBySizeButtonLabel": "כן_By Dimension_____ש",
  "newGRGFromRefSystemButtonLabel": "כן_By Reference System_______ש",
  "newGRGByTimeLabel": "כן_By Time and Speed______ש",
  "newGRGFromNonStandardButtonLabel": "כן_Define Non-Standard Grid________ש",
  "newGRGAreaBySizeTitle": "כן_GRG from an Area by Dimension__________ש",
  "newGRGAreaBySizeDefineAreaLabel": "כן_GRG Area___ש",
  "addGRGAreaPolygonToolTip": "כן_Draw GRG Area using polygon_________ש",
  "addGRGAreaExtentToolTip": "כן_Draw GRG Area using extent_________ש",
  "rotation": "כן_Grid Rotation_____ש",
  "numberRowsColumnsLabel": "כן_Define number of rows and columns___________ש",
  "newGRGAreaByRefSystemTitle": "כן_GRG from an Area by Reference System____________ש",
  "gridSize": "כן_Grid Size____ש",
  "UTMZoneandBand": "כן_Grid Zone____ש",
  "100000m": "כן_100000 meter_____ש",
  "10000m": "כן_10000 meter____ש",
  "1000m": "כן_1000 meter____ש",
  "100m": "כן_100 meter____ש",
  "10m": "כן_10 meter___ש",
  "clipGrid": "כן_Clip Grid to GRG Area_______ש",
  "newGRGAreaFromNonStandardTitle": "כן_New NRG___ש",
  "newGRGPointBySizeTitle": "כן_GRG from Point by Dimension_________ש",
  "newGRGPointByRefSystemTitle": "כן_GRG from Point by Reference System___________ש",
  "newGRGPointByTimeTitle": "כן_GRG from Point using Time and Speed____________ש",
  "time": "כן_Time__ש",
  "rate": "כן_Speed___ש",
  "hours": "כן_Hours___ש",
  "minutes": "כן_Minutes___ש",
  "seconds": "כן_Seconds___ש",
  "ftPerSec": "כן_Feet / second_____ש",
  "ftPerHour": "כן_Feet / hour____ש",
  "kmPerSec": "כן_Kilometers / second_______ש",
  "kmPerHour": "כן_Kilometers / hour______ש",
  "mPerSec": "כן_Meters / second______ש",
  "mPerHour": "כן_Meters / hour_____ש",
  "miPerSec": "כן_Miles / second_____ש",
  "miPerHour": "כן_Miles / hour_____ש",
  "nMPerSec": "כן_Nautical Miles / second________ש",
  "nMPerHour": "כן_Nautical Miles / hour_______ש",
  "settingsTitle": "כן_Settings___ש",
  "labelSettingsLabel": "כן_Label Settings_____ש",
  "labelSettingsButtonLabel": "כן_Configure Label Settings________ש",
  "gridSettingsLabel": "כן_Grid Settings_____ש",
  "gridSettingsButtonLabel": "כן_Configure Grid Settings________ש",
  "transparency": "כן_Transparency_____ש",
  "labelStyle": "כן_Label Style____ש",
  "font": "כן_Font__ש",
  "textSize": "כן_Text Size____ש",
  "textColor": "כן_Text Color____ש",
  "halo": "כן_Halo__ש",
  "show": "כן_Show__ש",
  "lockSettings": "כן_Settings have been locked by the application owner________________ש",
  "gridSettings": {
    "cellShape": "כן_Cell Shape____ש",
    "cellUnits": "כן_Cell Units____ש",
    "cellOutline": "כן_Cell Outline Settings_______ש",
    "cellFill": "כן_Cell Fill Settings______ש",
    "gridReferenceSystem": "כן_Reference System______ש",
    "gridDatum": "כן_Datum: WGS84_____ש",
    "labelStartPosition": "כן_Label Origin_____ש",
    "labelType": "כן_Label Type____ש",
    "labelDirection": "כן_Label Direction______ש",
    "gridOrigin": "כן_Grid Origin____ש",
    "default": "כן_Rectangle____ש",
    "hexagon": "כן_Hexagon___ש",
    "miles": "כן_Miles___ש",
    "kilometers": "כן_Kilometers____ש",
    "feet": "כן_Feet__ש",
    "meters": "כן_Meters___ש",
    "yards": "כן_Yards___ש",
    "nautical-miles": "כן_Nautical Miles_____ש",
    "lowerLeft": "כן_Lower-Left____ש",
    "lowerRight": "כן_Lower-Right____ש",
    "upperLeft": "כן_Upper-Left____ש",
    "upperRight": "כן_Upper-Right____ש",
    "center": "כן_Center___ש",
    "alphaNumeric": "כן_Alpha-Numeric_____ש",
    "alphaAlpha": "כן_Alpha-Alpha____ש",
    "numeric": "כן_Numeric___ש",
    "horizontal": "כן_Horizontal____ש",
    "vertical": "כן_Vertical___ש",
    "MGRS": "כן_MGRS__ש",
    "USNG": "כן_USNG__ש",
    "showLabels": "כן_Show Labels____ש"
  },
  "publishTitle": "כן_Publish GRG to Portal_______ש",
  "publishGRGBtn": "כן_Publish___ש",
  "GRGLayerName": "כן_Published GRG Layer Name________ש",
  "invalidGRGLayerName": "כן_Layer name must only contain alpha-numeric characters and underscores______________________ש",
  "missingGRGLayerName": "כן_You must enter a name for the GRG___________ש",
  "publishingFailedLayerExists": "כן_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ש.",
  "checkService": "כן_Check Service: {0}______ש",
  "createService": "כן_Create Service: {0}_______ש",
  "unableToCreate": "כן_Unable to create: {0}_______ש",
  "addToDefinition": "כן_Add to definition: {0}________ש",
  "successfullyPublished": "כן_Successfully published web layer{0}Manage the web layer__________________ש",
  "userRole": "כן_Unable to create service because user does not have permissions____________________ש",
  "createGRGBtn": "כן_Create GRG____ש",
  "clearGRGBtn": "כן_Clear___ש",
  "labelFormat": "כן_Label Format_____ש",
  "helpIconTooltip": "כן_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________ש",
  "addPointToolTip": "כן_Add GRG Origin_____ש",
  "cellWidth": "כן_Cell Width (x)_____ש",
  "cellHeight": "כן_Cell Height (y)______ש",
  "invalidNumberMessage": "כן_The value entered is not valid__________ש",
  "invalidRangeMessage": "כן_Value must be greater than 0_________ש",
  "gridAngleInvalidRangeMessage": "כן_Value must be between -89.9 and 89.9____________ש",
  "formatIconTooltip": "כן_Format Input_____ש",
  "coordInputLabel": "כן_GRG Origin (DD)______ש",
  "setCoordFormat": "כן_Set Coordinate Format String_________ש",
  "prefixNumbers": "כן_Add '+/-' prefix to positive and negative numbers________________ש",
  "cancelBtn": "כן_Cancel___ש",
  "applyBtn": "כן_Apply___ש",
  "comfirmInputNotation": "כן_Confirm Input Notation________ש",
  "notationsMatch": "כן_notations match your input please confirm which you would like to use______________________ש:",
  "numberOfCellsHorizontal": "כן_# Horizontal Cells______ש",
  "numberOfCellsVertical": "כן_# Vertical Cells______ש",
  "gridAngle": "כן_Grid Rotation_____ש",
  "tooManyCellsErrorMessage": "כן_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________ש.",
  "missingParametersMessage": "כן_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________ש",
  "missingOriginParametersMessage": "כן_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________ש",
  "invalidWidthHeightParametersMessage": "כן_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________ש",
  "invalidHorizontalVerticalParametersMessage": "כן_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________ש",
  "drawPointToolTip": "כן_Click to add GRG origin point__________ש",
  "missingLayerNameMessage": "כן_You must enter a valid layer name before you can publish__________________ש",
  "parseCoordinatesError": "כן_Unable to parse coordinates. Please check your input_________________ש.",
  "grgPolarRegionError": "כן_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________ש.",
  "grgPolarOriginError": "כן_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________ש.",
  "DD": "כן_DD__ש",
  "DDM": "כן_DDM__ש",
  "DMS": "כן_DMS__ש",
  "DDRev": "כן_DDRev___ש",
  "DDMRev": "כן_DDMRev___ש",
  "DMSRev": "כן_DMSRev___ש",
  "USNG": "כן_USNG__ש",
  "MGRS": "כן_MGRS__ש",
  "UTM_H": "כן_UTM (H)___ש",
  "UTM": "כן_UTM__ש",
  "GARS": "כן_GARS__ש",
  "GEOREF": "כן_GEOREF___ש",
  "DDLatLongNotation": "כן_Decimal Degrees - Latitude/Longitude____________ש",
  "DDLongLatNotation": "כן_Decimal Degrees  - Longitude/Latitude____________ש",
  "DDMLatLongNotation": "כן_Degrees Decimal Minutes - Latitude/Longitude______________ש",
  "DDMLongLatNotation": "כן_Degrees Decimal Minutes - Longitude/Latitude______________ש",
  "DMSLatLongNotation": "כן_Degrees Minutes Seconds - Latitude/Longitude______________ש",
  "DMSLongLatNotation": "כן_Degrees Minutes Seconds - Longitude/Latitude______________ש",
  "GARSNotation": "כן_GARS__ש",
  "GEOREFNotation": "כן_GEOREF___ש",
  "MGRSNotation": "כן_MGRS__ש",
  "USNGNotation": "כן_USNG__ש",
  "UTMBandNotation": "כן_UTM - Band Letter______ש",
  "UTMHemNotation": "כן_UTM - Hemisphere (N/S)________ש"
});