define({
  "_widgetLabel": "Đ_Gridded Reference Graphic_________ớ",
  "newGRGFromAreaButtonLabel": "Đ_Define a Grid from an Area_________ớ",
  "newGRGFromPointButtonLabel": "Đ_Define a Grid from a Point_________ớ",
  "newGRGFromAreaTitle": "Đ_Define a Grid from an Area_________ớ",
  "newGRGFromPointTitle": "Đ_Define a Grid from a Point_________ớ",
  "newGRGBySizeButtonLabel": "Đ_By Dimension_____ớ",
  "newGRGFromRefSystemButtonLabel": "Đ_By Reference System_______ớ",
  "newGRGByTimeLabel": "Đ_By Time and Speed______ớ",
  "newGRGFromNonStandardButtonLabel": "Đ_Define Non-Standard Grid________ớ",
  "newGRGAreaBySizeTitle": "Đ_GRG from an Area by Dimension__________ớ",
  "newGRGAreaBySizeDefineAreaLabel": "Đ_GRG Area___ớ",
  "addGRGAreaPolygonToolTip": "Đ_Draw GRG Area using polygon_________ớ",
  "addGRGAreaExtentToolTip": "Đ_Draw GRG Area using extent_________ớ",
  "rotation": "Đ_Grid Rotation_____ớ",
  "numberRowsColumnsLabel": "Đ_Define number of rows and columns___________ớ",
  "newGRGAreaByRefSystemTitle": "Đ_GRG from an Area by Reference System____________ớ",
  "gridSize": "Đ_Grid Size____ớ",
  "UTMZoneandBand": "Đ_Grid Zone____ớ",
  "100000m": "Đ_100000 meter_____ớ",
  "10000m": "Đ_10000 meter____ớ",
  "1000m": "Đ_1000 meter____ớ",
  "100m": "Đ_100 meter____ớ",
  "10m": "Đ_10 meter___ớ",
  "clipGrid": "Đ_Clip Grid to GRG Area_______ớ",
  "newGRGAreaFromNonStandardTitle": "Đ_New NRG___ớ",
  "newGRGPointBySizeTitle": "Đ_GRG from Point by Dimension_________ớ",
  "newGRGPointByRefSystemTitle": "Đ_GRG from Point by Reference System___________ớ",
  "newGRGPointByTimeTitle": "Đ_GRG from Point using Time and Speed____________ớ",
  "time": "Đ_Time__ớ",
  "rate": "Đ_Speed___ớ",
  "hours": "Đ_Hours___ớ",
  "minutes": "Đ_Minutes___ớ",
  "seconds": "Đ_Seconds___ớ",
  "ftPerSec": "Đ_Feet / second_____ớ",
  "ftPerHour": "Đ_Feet / hour____ớ",
  "kmPerSec": "Đ_Kilometers / second_______ớ",
  "kmPerHour": "Đ_Kilometers / hour______ớ",
  "mPerSec": "Đ_Meters / second______ớ",
  "mPerHour": "Đ_Meters / hour_____ớ",
  "miPerSec": "Đ_Miles / second_____ớ",
  "miPerHour": "Đ_Miles / hour_____ớ",
  "nMPerSec": "Đ_Nautical Miles / second________ớ",
  "nMPerHour": "Đ_Nautical Miles / hour_______ớ",
  "settingsTitle": "Đ_Settings___ớ",
  "labelSettingsLabel": "Đ_Label Settings_____ớ",
  "labelSettingsButtonLabel": "Đ_Configure Label Settings________ớ",
  "gridSettingsLabel": "Đ_Grid Settings_____ớ",
  "gridSettingsButtonLabel": "Đ_Configure Grid Settings________ớ",
  "transparency": "Đ_Transparency_____ớ",
  "labelStyle": "Đ_Label Style____ớ",
  "font": "Đ_Font__ớ",
  "textSize": "Đ_Text Size____ớ",
  "textColor": "Đ_Text Color____ớ",
  "halo": "Đ_Halo__ớ",
  "show": "Đ_Show__ớ",
  "lockSettings": "Đ_Settings have been locked by the application owner________________ớ",
  "gridSettings": {
    "cellShape": "Đ_Cell Shape____ớ",
    "cellUnits": "Đ_Cell Units____ớ",
    "cellOutline": "Đ_Cell Outline Settings_______ớ",
    "cellFill": "Đ_Cell Fill Settings______ớ",
    "gridReferenceSystem": "Đ_Reference System______ớ",
    "gridDatum": "Đ_Datum: WGS84_____ớ",
    "labelStartPosition": "Đ_Label Origin_____ớ",
    "labelType": "Đ_Label Type____ớ",
    "labelDirection": "Đ_Label Direction______ớ",
    "gridOrigin": "Đ_Grid Origin____ớ",
    "default": "Đ_Rectangle____ớ",
    "hexagon": "Đ_Hexagon___ớ",
    "miles": "Đ_Miles___ớ",
    "kilometers": "Đ_Kilometers____ớ",
    "feet": "Đ_Feet__ớ",
    "meters": "Đ_Meters___ớ",
    "yards": "Đ_Yards___ớ",
    "nautical-miles": "Đ_Nautical Miles_____ớ",
    "lowerLeft": "Đ_Lower-Left____ớ",
    "lowerRight": "Đ_Lower-Right____ớ",
    "upperLeft": "Đ_Upper-Left____ớ",
    "upperRight": "Đ_Upper-Right____ớ",
    "center": "Đ_Center___ớ",
    "alphaNumeric": "Đ_Alpha-Numeric_____ớ",
    "alphaAlpha": "Đ_Alpha-Alpha____ớ",
    "numeric": "Đ_Numeric___ớ",
    "horizontal": "Đ_Horizontal____ớ",
    "vertical": "Đ_Vertical___ớ",
    "MGRS": "Đ_MGRS__ớ",
    "USNG": "Đ_USNG__ớ",
    "showLabels": "Đ_Show Labels____ớ"
  },
  "publishTitle": "Đ_Publish GRG to Portal_______ớ",
  "publishGRGBtn": "Đ_Publish___ớ",
  "GRGLayerName": "Đ_Published GRG Layer Name________ớ",
  "invalidGRGLayerName": "Đ_Layer name must only contain alpha-numeric characters and underscores______________________ớ",
  "missingGRGLayerName": "Đ_You must enter a name for the GRG___________ớ",
  "publishingFailedLayerExists": "Đ_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ớ.",
  "checkService": "Đ_Check Service: {0}______ớ",
  "createService": "Đ_Create Service: {0}_______ớ",
  "unableToCreate": "Đ_Unable to create: {0}_______ớ",
  "addToDefinition": "Đ_Add to definition: {0}________ớ",
  "successfullyPublished": "Đ_Successfully published web layer{0}Manage the web layer__________________ớ",
  "userRole": "Đ_Unable to create service because user does not have permissions____________________ớ",
  "createGRGBtn": "Đ_Create GRG____ớ",
  "clearGRGBtn": "Đ_Clear___ớ",
  "labelFormat": "Đ_Label Format_____ớ",
  "helpIconTooltip": "Đ_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________ớ",
  "addPointToolTip": "Đ_Add GRG Origin_____ớ",
  "cellWidth": "Đ_Cell Width (x)_____ớ",
  "cellHeight": "Đ_Cell Height (y)______ớ",
  "invalidNumberMessage": "Đ_The value entered is not valid__________ớ",
  "invalidRangeMessage": "Đ_Value must be greater than 0_________ớ",
  "gridAngleInvalidRangeMessage": "Đ_Value must be between -89.9 and 89.9____________ớ",
  "formatIconTooltip": "Đ_Format Input_____ớ",
  "coordInputLabel": "Đ_GRG Origin (DD)______ớ",
  "setCoordFormat": "Đ_Set Coordinate Format String_________ớ",
  "prefixNumbers": "Đ_Add '+/-' prefix to positive and negative numbers________________ớ",
  "cancelBtn": "Đ_Cancel___ớ",
  "applyBtn": "Đ_Apply___ớ",
  "comfirmInputNotation": "Đ_Confirm Input Notation________ớ",
  "notationsMatch": "Đ_notations match your input please confirm which you would like to use______________________ớ:",
  "numberOfCellsHorizontal": "Đ_# Horizontal Cells______ớ",
  "numberOfCellsVertical": "Đ_# Vertical Cells______ớ",
  "gridAngle": "Đ_Grid Rotation_____ớ",
  "tooManyCellsErrorMessage": "Đ_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________ớ.",
  "missingParametersMessage": "Đ_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________ớ",
  "missingOriginParametersMessage": "Đ_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________ớ",
  "invalidWidthHeightParametersMessage": "Đ_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________ớ",
  "invalidHorizontalVerticalParametersMessage": "Đ_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________ớ",
  "drawPointToolTip": "Đ_Click to add GRG origin point__________ớ",
  "missingLayerNameMessage": "Đ_You must enter a valid layer name before you can publish__________________ớ",
  "parseCoordinatesError": "Đ_Unable to parse coordinates. Please check your input_________________ớ.",
  "grgPolarRegionError": "Đ_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________ớ.",
  "grgPolarOriginError": "Đ_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________ớ.",
  "DD": "Đ_DD__ớ",
  "DDM": "Đ_DDM__ớ",
  "DMS": "Đ_DMS__ớ",
  "DDRev": "Đ_DDRev___ớ",
  "DDMRev": "Đ_DDMRev___ớ",
  "DMSRev": "Đ_DMSRev___ớ",
  "USNG": "Đ_USNG__ớ",
  "MGRS": "Đ_MGRS__ớ",
  "UTM_H": "Đ_UTM (H)___ớ",
  "UTM": "Đ_UTM__ớ",
  "GARS": "Đ_GARS__ớ",
  "GEOREF": "Đ_GEOREF___ớ",
  "DDLatLongNotation": "Đ_Decimal Degrees - Latitude/Longitude____________ớ",
  "DDLongLatNotation": "Đ_Decimal Degrees  - Longitude/Latitude____________ớ",
  "DDMLatLongNotation": "Đ_Degrees Decimal Minutes - Latitude/Longitude______________ớ",
  "DDMLongLatNotation": "Đ_Degrees Decimal Minutes - Longitude/Latitude______________ớ",
  "DMSLatLongNotation": "Đ_Degrees Minutes Seconds - Latitude/Longitude______________ớ",
  "DMSLongLatNotation": "Đ_Degrees Minutes Seconds - Longitude/Latitude______________ớ",
  "GARSNotation": "Đ_GARS__ớ",
  "GEOREFNotation": "Đ_GEOREF___ớ",
  "MGRSNotation": "Đ_MGRS__ớ",
  "USNGNotation": "Đ_USNG__ớ",
  "UTMBandNotation": "Đ_UTM - Band Letter______ớ",
  "UTMHemNotation": "Đ_UTM - Hemisphere (N/S)________ớ"
});