define({
  "_widgetLabel": "بيت_Gridded Reference Graphic_________لاحقة",
  "newGRGFromAreaButtonLabel": "بيت_Define a Grid from an Area_________لاحقة",
  "newGRGFromPointButtonLabel": "بيت_Define a Grid from a Point_________لاحقة",
  "newGRGFromAreaTitle": "بيت_Define a Grid from an Area_________لاحقة",
  "newGRGFromPointTitle": "بيت_Define a Grid from a Point_________لاحقة",
  "newGRGBySizeButtonLabel": "بيت_By Dimension_____لاحقة",
  "newGRGFromRefSystemButtonLabel": "بيت_By Reference System_______لاحقة",
  "newGRGByTimeLabel": "بيت_By Time and Speed______لاحقة",
  "newGRGFromNonStandardButtonLabel": "بيت_Define Non-Standard Grid________لاحقة",
  "newGRGAreaBySizeTitle": "بيت_GRG from an Area by Dimension__________لاحقة",
  "newGRGAreaBySizeDefineAreaLabel": "بيت_GRG Area___لاحقة",
  "addGRGAreaPolygonToolTip": "بيت_Draw GRG Area using polygon_________لاحقة",
  "addGRGAreaExtentToolTip": "بيت_Draw GRG Area using extent_________لاحقة",
  "rotation": "بيت_Grid Rotation_____لاحقة",
  "numberRowsColumnsLabel": "بيت_Define number of rows and columns___________لاحقة",
  "newGRGAreaByRefSystemTitle": "بيت_GRG from an Area by Reference System____________لاحقة",
  "gridSize": "بيت_Grid Size____لاحقة",
  "UTMZoneandBand": "بيت_Grid Zone____لاحقة",
  "100000m": "بيت_100000 meter_____لاحقة",
  "10000m": "بيت_10000 meter____لاحقة",
  "1000m": "بيت_1000 meter____لاحقة",
  "100m": "بيت_100 meter____لاحقة",
  "10m": "بيت_10 meter___لاحقة",
  "clipGrid": "بيت_Clip Grid to GRG Area_______لاحقة",
  "newGRGAreaFromNonStandardTitle": "بيت_New NRG___لاحقة",
  "newGRGPointBySizeTitle": "بيت_GRG from Point by Dimension_________لاحقة",
  "newGRGPointByRefSystemTitle": "بيت_GRG from Point by Reference System___________لاحقة",
  "newGRGPointByTimeTitle": "بيت_GRG from Point using Time and Speed____________لاحقة",
  "time": "بيت_Time__لاحقة",
  "rate": "بيت_Speed___لاحقة",
  "hours": "بيت_Hours___لاحقة",
  "minutes": "بيت_Minutes___لاحقة",
  "seconds": "بيت_Seconds___لاحقة",
  "ftPerSec": "بيت_Feet / second_____لاحقة",
  "ftPerHour": "بيت_Feet / hour____لاحقة",
  "kmPerSec": "بيت_Kilometers / second_______لاحقة",
  "kmPerHour": "بيت_Kilometers / hour______لاحقة",
  "mPerSec": "بيت_Meters / second______لاحقة",
  "mPerHour": "بيت_Meters / hour_____لاحقة",
  "miPerSec": "بيت_Miles / second_____لاحقة",
  "miPerHour": "بيت_Miles / hour_____لاحقة",
  "nMPerSec": "بيت_Nautical Miles / second________لاحقة",
  "nMPerHour": "بيت_Nautical Miles / hour_______لاحقة",
  "settingsTitle": "بيت_Settings___لاحقة",
  "labelSettingsLabel": "بيت_Label Settings_____لاحقة",
  "labelSettingsButtonLabel": "بيت_Configure Label Settings________لاحقة",
  "gridSettingsLabel": "بيت_Grid Settings_____لاحقة",
  "gridSettingsButtonLabel": "بيت_Configure Grid Settings________لاحقة",
  "transparency": "بيت_Transparency_____لاحقة",
  "labelStyle": "بيت_Label Style____لاحقة",
  "font": "بيت_Font__لاحقة",
  "textSize": "بيت_Text Size____لاحقة",
  "textColor": "بيت_Text Color____لاحقة",
  "halo": "بيت_Halo__لاحقة",
  "show": "بيت_Show__لاحقة",
  "lockSettings": "بيت_Settings have been locked by the application owner________________لاحقة",
  "gridSettings": {
    "cellShape": "بيت_Cell Shape____لاحقة",
    "cellUnits": "بيت_Cell Units____لاحقة",
    "cellOutline": "بيت_Cell Outline Settings_______لاحقة",
    "cellFill": "بيت_Cell Fill Settings______لاحقة",
    "gridReferenceSystem": "بيت_Reference System______لاحقة",
    "gridDatum": "بيت_Datum: WGS84_____لاحقة",
    "labelStartPosition": "بيت_Label Origin_____لاحقة",
    "labelType": "بيت_Label Type____لاحقة",
    "labelDirection": "بيت_Label Direction______لاحقة",
    "gridOrigin": "بيت_Grid Origin____لاحقة",
    "default": "بيت_Rectangle____لاحقة",
    "hexagon": "بيت_Hexagon___لاحقة",
    "miles": "بيت_Miles___لاحقة",
    "kilometers": "بيت_Kilometers____لاحقة",
    "feet": "بيت_Feet__لاحقة",
    "meters": "بيت_Meters___لاحقة",
    "yards": "بيت_Yards___لاحقة",
    "nautical-miles": "بيت_Nautical Miles_____لاحقة",
    "lowerLeft": "بيت_Lower-Left____لاحقة",
    "lowerRight": "بيت_Lower-Right____لاحقة",
    "upperLeft": "بيت_Upper-Left____لاحقة",
    "upperRight": "بيت_Upper-Right____لاحقة",
    "center": "بيت_Center___لاحقة",
    "alphaNumeric": "بيت_Alpha-Numeric_____لاحقة",
    "alphaAlpha": "بيت_Alpha-Alpha____لاحقة",
    "numeric": "بيت_Numeric___لاحقة",
    "horizontal": "بيت_Horizontal____لاحقة",
    "vertical": "بيت_Vertical___لاحقة",
    "MGRS": "بيت_MGRS__لاحقة",
    "USNG": "بيت_USNG__لاحقة",
    "showLabels": "بيت_Show Labels____لاحقة"
  },
  "publishTitle": "بيت_Publish GRG to Portal_______لاحقة",
  "publishGRGBtn": "بيت_Publish___لاحقة",
  "GRGLayerName": "بيت_Published GRG Layer Name________لاحقة",
  "invalidGRGLayerName": "بيت_Layer name must only contain alpha-numeric characters and underscores______________________لاحقة",
  "missingGRGLayerName": "بيت_You must enter a name for the GRG___________لاحقة",
  "publishingFailedLayerExists": "بيت_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________لاحقة.",
  "checkService": "بيت_Check Service: {0}______لاحقة",
  "createService": "بيت_Create Service: {0}_______لاحقة",
  "unableToCreate": "بيت_Unable to create: {0}_______لاحقة",
  "addToDefinition": "بيت_Add to definition: {0}________لاحقة",
  "successfullyPublished": "بيت_Successfully published web layer{0}Manage the web layer__________________لاحقة",
  "userRole": "بيت_Unable to create service because user does not have permissions____________________لاحقة",
  "createGRGBtn": "بيت_Create GRG____لاحقة",
  "clearGRGBtn": "بيت_Clear___لاحقة",
  "labelFormat": "بيت_Label Format_____لاحقة",
  "helpIconTooltip": "بيت_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________لاحقة",
  "addPointToolTip": "بيت_Add GRG Origin_____لاحقة",
  "cellWidth": "بيت_Cell Width (x)_____لاحقة",
  "cellHeight": "بيت_Cell Height (y)______لاحقة",
  "invalidNumberMessage": "بيت_The value entered is not valid__________لاحقة",
  "invalidRangeMessage": "بيت_Value must be greater than 0_________لاحقة",
  "gridAngleInvalidRangeMessage": "بيت_Value must be between -89.9 and 89.9____________لاحقة",
  "formatIconTooltip": "بيت_Format Input_____لاحقة",
  "coordInputLabel": "بيت_GRG Origin (DD)______لاحقة",
  "setCoordFormat": "بيت_Set Coordinate Format String_________لاحقة",
  "prefixNumbers": "بيت_Add '+/-' prefix to positive and negative numbers________________لاحقة",
  "cancelBtn": "بيت_Cancel___لاحقة",
  "applyBtn": "بيت_Apply___لاحقة",
  "comfirmInputNotation": "بيت_Confirm Input Notation________لاحقة",
  "notationsMatch": "بيت_notations match your input please confirm which you would like to use______________________لاحقة:",
  "numberOfCellsHorizontal": "بيت_# Horizontal Cells______لاحقة",
  "numberOfCellsVertical": "بيت_# Vertical Cells______لاحقة",
  "gridAngle": "بيت_Grid Rotation_____لاحقة",
  "tooManyCellsErrorMessage": "بيت_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________لاحقة.",
  "missingParametersMessage": "بيت_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________لاحقة",
  "missingOriginParametersMessage": "بيت_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________لاحقة",
  "invalidWidthHeightParametersMessage": "بيت_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________لاحقة",
  "invalidHorizontalVerticalParametersMessage": "بيت_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________لاحقة",
  "drawPointToolTip": "بيت_Click to add GRG origin point__________لاحقة",
  "missingLayerNameMessage": "بيت_You must enter a valid layer name before you can publish__________________لاحقة",
  "parseCoordinatesError": "بيت_Unable to parse coordinates. Please check your input_________________لاحقة.",
  "grgPolarRegionError": "بيت_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________لاحقة.",
  "grgPolarOriginError": "بيت_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________لاحقة.",
  "DD": "بيت_DD__لاحقة",
  "DDM": "بيت_DDM__لاحقة",
  "DMS": "بيت_DMS__لاحقة",
  "DDRev": "بيت_DDRev___لاحقة",
  "DDMRev": "بيت_DDMRev___لاحقة",
  "DMSRev": "بيت_DMSRev___لاحقة",
  "USNG": "بيت_USNG__لاحقة",
  "MGRS": "بيت_MGRS__لاحقة",
  "UTM_H": "بيت_UTM (H)___لاحقة",
  "UTM": "بيت_UTM__لاحقة",
  "GARS": "بيت_GARS__لاحقة",
  "GEOREF": "بيت_GEOREF___لاحقة",
  "DDLatLongNotation": "بيت_Decimal Degrees - Latitude/Longitude____________لاحقة",
  "DDLongLatNotation": "بيت_Decimal Degrees  - Longitude/Latitude____________لاحقة",
  "DDMLatLongNotation": "بيت_Degrees Decimal Minutes - Latitude/Longitude______________لاحقة",
  "DDMLongLatNotation": "بيت_Degrees Decimal Minutes - Longitude/Latitude______________لاحقة",
  "DMSLatLongNotation": "بيت_Degrees Minutes Seconds - Latitude/Longitude______________لاحقة",
  "DMSLongLatNotation": "بيت_Degrees Minutes Seconds - Longitude/Latitude______________لاحقة",
  "GARSNotation": "بيت_GARS__لاحقة",
  "GEOREFNotation": "بيت_GEOREF___لاحقة",
  "MGRSNotation": "بيت_MGRS__لاحقة",
  "USNGNotation": "بيت_USNG__لاحقة",
  "UTMBandNotation": "بيت_UTM - Band Letter______لاحقة",
  "UTMHemNotation": "بيت_UTM - Hemisphere (N/S)________لاحقة"
});