define({
  "gridTabLabel": "ø_Grid__å",
  "labelTabLabel": "ø_Labels___å",
  "referenceSystemTabLabel": "ø_Reference System______å",
  "gridTabDescription": "ø_Set the appearance and behavior of the grid cells________________å.",
  "cellOutlineColor": "ø_Cell Outine color______å",
  "cellFillColor": "ø_Cell Fill color______å",
  "transparency": "ø_Transparency_____å",
  "cellShapeDropDown": "ø_Cell Shape____å",
  "default": "ø_Rectangle____å",
  "hexagon": "ø_Hexagon___å",
  "cellUnitsDropDown": "ø_Cell Units____å",
  "miles": "ø_Miles___å",
  "kilometers": "ø_Kilometers____å",
  "feet": "ø_Feet__å",
  "meters": "ø_Meters___å",
  "yards": "ø_Yards___å",
  "nautical-miles": "ø_Nautical Miles_____å",
  "gridOriginDropDown": "ø_Grid Origin____å",
  "lowerLeft": "ø_Lower-Left____å",
  "lowerRight": "ø_Lower-Right____å",
  "upperLeft": "ø_Upper-Left____å",
  "upperRight": "ø_Upper-Right____å",
  "center": "ø_Center___å",
  "labelTabDescription": "ø_Set the appearance and behavior of the grid labels________________å.",
  "labelSettings": "ø_Label Style____å",
  "font": "ø_Font__å",
  "textSize": "ø_Text Size____å",
  "textColor": "ø_Text Color____å",
  "halo": "ø_Halo__å",
  "show": "ø_Show__å",
  "labelTypeDropDown": "ø_Label Type____å",
  "alphaNumeric": "ø_Alpha-Numeric_____å",
  "alphaAlpha": "ø_Alpha-Alpha____å",
  "numeric": "ø_Numeric___å",
  "labelDirectionDropDown": "ø_Label Direction______å",
  "horizontal": "ø_Horizontal____å",
  "vertical": "ø_Vertical___å",
  "labelOriginDropDown": "ø_Label Origin_____å",
  "referenceSystemlTabDescription": "ø_Set the default reference system___________å.",
  "MGRS": "ø_MGRS__å",
  "USNG": "ø_USNG__å",
  "lockSettings": "ø_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________å"
});