define({
  "gridTabLabel": "Đ_Grid__ớ",
  "labelTabLabel": "Đ_Labels___ớ",
  "referenceSystemTabLabel": "Đ_Reference System______ớ",
  "gridTabDescription": "Đ_Set the appearance and behavior of the grid cells________________ớ.",
  "cellOutlineColor": "Đ_Cell Outine color______ớ",
  "cellFillColor": "Đ_Cell Fill color______ớ",
  "transparency": "Đ_Transparency_____ớ",
  "cellShapeDropDown": "Đ_Cell Shape____ớ",
  "default": "Đ_Rectangle____ớ",
  "hexagon": "Đ_Hexagon___ớ",
  "cellUnitsDropDown": "Đ_Cell Units____ớ",
  "miles": "Đ_Miles___ớ",
  "kilometers": "Đ_Kilometers____ớ",
  "feet": "Đ_Feet__ớ",
  "meters": "Đ_Meters___ớ",
  "yards": "Đ_Yards___ớ",
  "nautical-miles": "Đ_Nautical Miles_____ớ",
  "gridOriginDropDown": "Đ_Grid Origin____ớ",
  "lowerLeft": "Đ_Lower-Left____ớ",
  "lowerRight": "Đ_Lower-Right____ớ",
  "upperLeft": "Đ_Upper-Left____ớ",
  "upperRight": "Đ_Upper-Right____ớ",
  "center": "Đ_Center___ớ",
  "labelTabDescription": "Đ_Set the appearance and behavior of the grid labels________________ớ.",
  "labelSettings": "Đ_Label Style____ớ",
  "font": "Đ_Font__ớ",
  "textSize": "Đ_Text Size____ớ",
  "textColor": "Đ_Text Color____ớ",
  "halo": "Đ_Halo__ớ",
  "show": "Đ_Show__ớ",
  "labelTypeDropDown": "Đ_Label Type____ớ",
  "alphaNumeric": "Đ_Alpha-Numeric_____ớ",
  "alphaAlpha": "Đ_Alpha-Alpha____ớ",
  "numeric": "Đ_Numeric___ớ",
  "labelDirectionDropDown": "Đ_Label Direction______ớ",
  "horizontal": "Đ_Horizontal____ớ",
  "vertical": "Đ_Vertical___ớ",
  "labelOriginDropDown": "Đ_Label Origin_____ớ",
  "referenceSystemlTabDescription": "Đ_Set the default reference system___________ớ.",
  "MGRS": "Đ_MGRS__ớ",
  "USNG": "Đ_USNG__ớ",
  "lockSettings": "Đ_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________ớ"
});