define({
  "_widgetLabel": "试_Gridded Reference Graphic_________验",
  "newGRGFromAreaButtonLabel": "试_Define a Grid from an Area_________验",
  "newGRGFromPointButtonLabel": "试_Define a Grid from a Point_________验",
  "newGRGFromAreaTitle": "试_Define a Grid from an Area_________验",
  "newGRGFromPointTitle": "试_Define a Grid from a Point_________验",
  "newGRGBySizeButtonLabel": "试_By Dimension_____验",
  "newGRGFromRefSystemButtonLabel": "试_By Reference System_______验",
  "newGRGByTimeLabel": "试_By Time and Speed______验",
  "newGRGFromNonStandardButtonLabel": "试_Define Non-Standard Grid________验",
  "newGRGAreaBySizeTitle": "试_GRG from an Area by Dimension__________验",
  "newGRGAreaBySizeDefineAreaLabel": "试_GRG Area___验",
  "addGRGAreaPolygonToolTip": "试_Draw GRG Area using polygon_________验",
  "addGRGAreaExtentToolTip": "试_Draw GRG Area using extent_________验",
  "rotation": "试_Grid Rotation_____验",
  "numberRowsColumnsLabel": "试_Define number of rows and columns___________验",
  "newGRGAreaByRefSystemTitle": "试_GRG from an Area by Reference System____________验",
  "gridSize": "试_Grid Size____验",
  "UTMZoneandBand": "试_Grid Zone____验",
  "100000m": "试_100000 meter_____验",
  "10000m": "试_10000 meter____验",
  "1000m": "试_1000 meter____验",
  "100m": "试_100 meter____验",
  "10m": "试_10 meter___验",
  "clipGrid": "试_Clip Grid to GRG Area_______验",
  "newGRGAreaFromNonStandardTitle": "试_New NRG___验",
  "newGRGPointBySizeTitle": "试_GRG from Point by Dimension_________验",
  "newGRGPointByRefSystemTitle": "试_GRG from Point by Reference System___________验",
  "newGRGPointByTimeTitle": "试_GRG from Point using Time and Speed____________验",
  "time": "试_Time__验",
  "rate": "试_Speed___验",
  "hours": "试_Hours___验",
  "minutes": "试_Minutes___验",
  "seconds": "试_Seconds___验",
  "ftPerSec": "试_Feet / second_____验",
  "ftPerHour": "试_Feet / hour____验",
  "kmPerSec": "试_Kilometers / second_______验",
  "kmPerHour": "试_Kilometers / hour______验",
  "mPerSec": "试_Meters / second______验",
  "mPerHour": "试_Meters / hour_____验",
  "miPerSec": "试_Miles / second_____验",
  "miPerHour": "试_Miles / hour_____验",
  "nMPerSec": "试_Nautical Miles / second________验",
  "nMPerHour": "试_Nautical Miles / hour_______验",
  "settingsTitle": "试_Settings___验",
  "labelSettingsLabel": "试_Label Settings_____验",
  "labelSettingsButtonLabel": "试_Configure Label Settings________验",
  "gridSettingsLabel": "试_Grid Settings_____验",
  "gridSettingsButtonLabel": "试_Configure Grid Settings________验",
  "transparency": "试_Transparency_____验",
  "labelStyle": "试_Label Style____验",
  "font": "试_Font__验",
  "textSize": "试_Text Size____验",
  "textColor": "试_Text Color____验",
  "halo": "试_Halo__验",
  "show": "试_Show__验",
  "lockSettings": "试_Settings have been locked by the application owner________________验",
  "gridSettings": {
    "cellShape": "试_Cell Shape____验",
    "cellUnits": "试_Cell Units____验",
    "cellOutline": "试_Cell Outline Settings_______验",
    "cellFill": "试_Cell Fill Settings______验",
    "gridReferenceSystem": "试_Reference System______验",
    "gridDatum": "试_Datum: WGS84_____验",
    "labelStartPosition": "试_Label Origin_____验",
    "labelType": "试_Label Type____验",
    "labelDirection": "试_Label Direction______验",
    "gridOrigin": "试_Grid Origin____验",
    "default": "试_Rectangle____验",
    "hexagon": "试_Hexagon___验",
    "miles": "试_Miles___验",
    "kilometers": "试_Kilometers____验",
    "feet": "试_Feet__验",
    "meters": "试_Meters___验",
    "yards": "试_Yards___验",
    "nautical-miles": "试_Nautical Miles_____验",
    "lowerLeft": "试_Lower-Left____验",
    "lowerRight": "试_Lower-Right____验",
    "upperLeft": "试_Upper-Left____验",
    "upperRight": "试_Upper-Right____验",
    "center": "试_Center___验",
    "alphaNumeric": "试_Alpha-Numeric_____验",
    "alphaAlpha": "试_Alpha-Alpha____验",
    "numeric": "试_Numeric___验",
    "horizontal": "试_Horizontal____验",
    "vertical": "试_Vertical___验",
    "MGRS": "试_MGRS__验",
    "USNG": "试_USNG__验",
    "showLabels": "试_Show Labels____验"
  },
  "publishTitle": "试_Publish GRG to Portal_______验",
  "publishGRGBtn": "试_Publish___验",
  "GRGLayerName": "试_Published GRG Layer Name________验",
  "invalidGRGLayerName": "试_Layer name must only contain alpha-numeric characters and underscores______________________验",
  "missingGRGLayerName": "试_You must enter a name for the GRG___________验",
  "publishingFailedLayerExists": "试_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________验.",
  "checkService": "试_Check Service: {0}______验",
  "createService": "试_Create Service: {0}_______验",
  "unableToCreate": "试_Unable to create: {0}_______验",
  "addToDefinition": "试_Add to definition: {0}________验",
  "successfullyPublished": "试_Successfully published web layer{0}Manage the web layer__________________验",
  "userRole": "试_Unable to create service because user does not have permissions____________________验",
  "createGRGBtn": "试_Create GRG____验",
  "clearGRGBtn": "试_Clear___验",
  "labelFormat": "试_Label Format_____验",
  "helpIconTooltip": "试_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________验",
  "addPointToolTip": "试_Add GRG Origin_____验",
  "cellWidth": "试_Cell Width (x)_____验",
  "cellHeight": "试_Cell Height (y)______验",
  "invalidNumberMessage": "试_The value entered is not valid__________验",
  "invalidRangeMessage": "试_Value must be greater than 0_________验",
  "gridAngleInvalidRangeMessage": "试_Value must be between -89.9 and 89.9____________验",
  "formatIconTooltip": "试_Format Input_____验",
  "coordInputLabel": "试_GRG Origin (DD)______验",
  "setCoordFormat": "试_Set Coordinate Format String_________验",
  "prefixNumbers": "试_Add '+/-' prefix to positive and negative numbers________________验",
  "cancelBtn": "试_Cancel___验",
  "applyBtn": "试_Apply___验",
  "comfirmInputNotation": "试_Confirm Input Notation________验",
  "notationsMatch": "试_notations match your input please confirm which you would like to use______________________验:",
  "numberOfCellsHorizontal": "试_# Horizontal Cells______验",
  "numberOfCellsVertical": "试_# Vertical Cells______验",
  "gridAngle": "试_Grid Rotation_____验",
  "tooManyCellsErrorMessage": "试_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________验.",
  "missingParametersMessage": "试_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________验",
  "missingOriginParametersMessage": "试_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________验",
  "invalidWidthHeightParametersMessage": "试_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________验",
  "invalidHorizontalVerticalParametersMessage": "试_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________验",
  "drawPointToolTip": "试_Click to add GRG origin point__________验",
  "missingLayerNameMessage": "试_You must enter a valid layer name before you can publish__________________验",
  "parseCoordinatesError": "试_Unable to parse coordinates. Please check your input_________________验.",
  "grgPolarRegionError": "试_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________验.",
  "grgPolarOriginError": "试_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________验.",
  "DD": "试_DD__验",
  "DDM": "试_DDM__验",
  "DMS": "试_DMS__验",
  "DDRev": "试_DDRev___验",
  "DDMRev": "试_DDMRev___验",
  "DMSRev": "试_DMSRev___验",
  "USNG": "试_USNG__验",
  "MGRS": "试_MGRS__验",
  "UTM_H": "试_UTM (H)___验",
  "UTM": "试_UTM__验",
  "GARS": "试_GARS__验",
  "GEOREF": "试_GEOREF___验",
  "DDLatLongNotation": "试_Decimal Degrees - Latitude/Longitude____________验",
  "DDLongLatNotation": "试_Decimal Degrees  - Longitude/Latitude____________验",
  "DDMLatLongNotation": "试_Degrees Decimal Minutes - Latitude/Longitude______________验",
  "DDMLongLatNotation": "试_Degrees Decimal Minutes - Longitude/Latitude______________验",
  "DMSLatLongNotation": "试_Degrees Minutes Seconds - Latitude/Longitude______________验",
  "DMSLongLatNotation": "试_Degrees Minutes Seconds - Longitude/Latitude______________验",
  "GARSNotation": "试_GARS__验",
  "GEOREFNotation": "试_GEOREF___验",
  "MGRSNotation": "试_MGRS__验",
  "USNGNotation": "试_USNG__验",
  "UTMBandNotation": "试_UTM - Band Letter______验",
  "UTMHemNotation": "试_UTM - Hemisphere (N/S)________验"
});