define({
  "gridTabLabel": "ã_Grid__Ç",
  "labelTabLabel": "ã_Labels___Ç",
  "referenceSystemTabLabel": "ã_Reference System______Ç",
  "gridTabDescription": "ã_Set the appearance and behavior of the grid cells________________Ç.",
  "cellOutlineColor": "ã_Cell Outine color______Ç",
  "cellFillColor": "ã_Cell Fill color______Ç",
  "transparency": "ã_Transparency_____Ç",
  "cellShapeDropDown": "ã_Cell Shape____Ç",
  "default": "ã_Rectangle____Ç",
  "hexagon": "ã_Hexagon___Ç",
  "cellUnitsDropDown": "ã_Cell Units____Ç",
  "miles": "ã_Miles___Ç",
  "kilometers": "ã_Kilometers____Ç",
  "feet": "ã_Feet__Ç",
  "meters": "ã_Meters___Ç",
  "yards": "ã_Yards___Ç",
  "nautical-miles": "ã_Nautical Miles_____Ç",
  "gridOriginDropDown": "ã_Grid Origin____Ç",
  "lowerLeft": "ã_Lower-Left____Ç",
  "lowerRight": "ã_Lower-Right____Ç",
  "upperLeft": "ã_Upper-Left____Ç",
  "upperRight": "ã_Upper-Right____Ç",
  "center": "ã_Center___Ç",
  "labelTabDescription": "ã_Set the appearance and behavior of the grid labels________________Ç.",
  "labelSettings": "ã_Label Style____Ç",
  "font": "ã_Font__Ç",
  "textSize": "ã_Text Size____Ç",
  "textColor": "ã_Text Color____Ç",
  "halo": "ã_Halo__Ç",
  "show": "ã_Show__Ç",
  "labelTypeDropDown": "ã_Label Type____Ç",
  "alphaNumeric": "ã_Alpha-Numeric_____Ç",
  "alphaAlpha": "ã_Alpha-Alpha____Ç",
  "numeric": "ã_Numeric___Ç",
  "labelDirectionDropDown": "ã_Label Direction______Ç",
  "horizontal": "ã_Horizontal____Ç",
  "vertical": "ã_Vertical___Ç",
  "labelOriginDropDown": "ã_Label Origin_____Ç",
  "referenceSystemlTabDescription": "ã_Set the default reference system___________Ç.",
  "MGRS": "ã_MGRS__Ç",
  "USNG": "ã_USNG__Ç",
  "lockSettings": "ã_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________Ç"
});