define({
  "gridTabLabel": "ng_Grid__ny",
  "labelTabLabel": "ng_Labels___ny",
  "referenceSystemTabLabel": "ng_Reference System______ny",
  "gridTabDescription": "ng_Set the appearance and behavior of the grid cells________________ny.",
  "cellOutlineColor": "ng_Cell Outine color______ny",
  "cellFillColor": "ng_Cell Fill color______ny",
  "transparency": "ng_Transparency_____ny",
  "cellShapeDropDown": "ng_Cell Shape____ny",
  "default": "ng_Rectangle____ny",
  "hexagon": "ng_Hexagon___ny",
  "cellUnitsDropDown": "ng_Cell Units____ny",
  "miles": "ng_Miles___ny",
  "kilometers": "ng_Kilometers____ny",
  "feet": "ng_Feet__ny",
  "meters": "ng_Meters___ny",
  "yards": "ng_Yards___ny",
  "nautical-miles": "ng_Nautical Miles_____ny",
  "gridOriginDropDown": "ng_Grid Origin____ny",
  "lowerLeft": "ng_Lower-Left____ny",
  "lowerRight": "ng_Lower-Right____ny",
  "upperLeft": "ng_Upper-Left____ny",
  "upperRight": "ng_Upper-Right____ny",
  "center": "ng_Center___ny",
  "labelTabDescription": "ng_Set the appearance and behavior of the grid labels________________ny.",
  "labelSettings": "ng_Label Style____ny",
  "font": "ng_Font__ny",
  "textSize": "ng_Text Size____ny",
  "textColor": "ng_Text Color____ny",
  "halo": "ng_Halo__ny",
  "show": "ng_Show__ny",
  "labelTypeDropDown": "ng_Label Type____ny",
  "alphaNumeric": "ng_Alpha-Numeric_____ny",
  "alphaAlpha": "ng_Alpha-Alpha____ny",
  "numeric": "ng_Numeric___ny",
  "labelDirectionDropDown": "ng_Label Direction______ny",
  "horizontal": "ng_Horizontal____ny",
  "vertical": "ng_Vertical___ny",
  "labelOriginDropDown": "ng_Label Origin_____ny",
  "referenceSystemlTabDescription": "ng_Set the default reference system___________ny.",
  "MGRS": "ng_MGRS__ny",
  "USNG": "ng_USNG__ny",
  "lockSettings": "ng_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________ny"
});