define({
  "_widgetLabel": "Š_Gridded Reference Graphic_________č",
  "newGRGFromAreaButtonLabel": "Š_Define a Grid from an Area_________č",
  "newGRGFromPointButtonLabel": "Š_Define a Grid from a Point_________č",
  "newGRGFromAreaTitle": "Š_Define a Grid from an Area_________č",
  "newGRGFromPointTitle": "Š_Define a Grid from a Point_________č",
  "newGRGBySizeButtonLabel": "Š_By Dimension_____č",
  "newGRGFromRefSystemButtonLabel": "Š_By Reference System_______č",
  "newGRGByTimeLabel": "Š_By Time and Speed______č",
  "newGRGFromNonStandardButtonLabel": "Š_Define Non-Standard Grid________č",
  "newGRGAreaBySizeTitle": "Š_GRG from an Area by Dimension__________č",
  "newGRGAreaBySizeDefineAreaLabel": "Š_GRG Area___č",
  "addGRGAreaPolygonToolTip": "Š_Draw GRG Area using polygon_________č",
  "addGRGAreaExtentToolTip": "Š_Draw GRG Area using extent_________č",
  "rotation": "Š_Grid Rotation_____č",
  "numberRowsColumnsLabel": "Š_Define number of rows and columns___________č",
  "newGRGAreaByRefSystemTitle": "Š_GRG from an Area by Reference System____________č",
  "gridSize": "Š_Grid Size____č",
  "UTMZoneandBand": "Š_Grid Zone____č",
  "100000m": "Š_100000 meter_____č",
  "10000m": "Š_10000 meter____č",
  "1000m": "Š_1000 meter____č",
  "100m": "Š_100 meter____č",
  "10m": "Š_10 meter___č",
  "clipGrid": "Š_Clip Grid to GRG Area_______č",
  "newGRGAreaFromNonStandardTitle": "Š_New NRG___č",
  "newGRGPointBySizeTitle": "Š_GRG from Point by Dimension_________č",
  "newGRGPointByRefSystemTitle": "Š_GRG from Point by Reference System___________č",
  "newGRGPointByTimeTitle": "Š_GRG from Point using Time and Speed____________č",
  "time": "Š_Time__č",
  "rate": "Š_Speed___č",
  "hours": "Š_Hours___č",
  "minutes": "Š_Minutes___č",
  "seconds": "Š_Seconds___č",
  "ftPerSec": "Š_Feet / second_____č",
  "ftPerHour": "Š_Feet / hour____č",
  "kmPerSec": "Š_Kilometers / second_______č",
  "kmPerHour": "Š_Kilometers / hour______č",
  "mPerSec": "Š_Meters / second______č",
  "mPerHour": "Š_Meters / hour_____č",
  "miPerSec": "Š_Miles / second_____č",
  "miPerHour": "Š_Miles / hour_____č",
  "nMPerSec": "Š_Nautical Miles / second________č",
  "nMPerHour": "Š_Nautical Miles / hour_______č",
  "settingsTitle": "Š_Settings___č",
  "labelSettingsLabel": "Š_Label Settings_____č",
  "labelSettingsButtonLabel": "Š_Configure Label Settings________č",
  "gridSettingsLabel": "Š_Grid Settings_____č",
  "gridSettingsButtonLabel": "Š_Configure Grid Settings________č",
  "transparency": "Š_Transparency_____č",
  "labelStyle": "Š_Label Style____č",
  "font": "Š_Font__č",
  "textSize": "Š_Text Size____č",
  "textColor": "Š_Text Color____č",
  "halo": "Š_Halo__č",
  "show": "Š_Show__č",
  "lockSettings": "Š_Settings have been locked by the application owner________________č",
  "gridSettings": {
    "cellShape": "Š_Cell Shape____č",
    "cellUnits": "Š_Cell Units____č",
    "cellOutline": "Š_Cell Outline Settings_______č",
    "cellFill": "Š_Cell Fill Settings______č",
    "gridReferenceSystem": "Š_Reference System______č",
    "gridDatum": "Š_Datum: WGS84_____č",
    "labelStartPosition": "Š_Label Origin_____č",
    "labelType": "Š_Label Type____č",
    "labelDirection": "Š_Label Direction______č",
    "gridOrigin": "Š_Grid Origin____č",
    "default": "Š_Rectangle____č",
    "hexagon": "Š_Hexagon___č",
    "miles": "Š_Miles___č",
    "kilometers": "Š_Kilometers____č",
    "feet": "Š_Feet__č",
    "meters": "Š_Meters___č",
    "yards": "Š_Yards___č",
    "nautical-miles": "Š_Nautical Miles_____č",
    "lowerLeft": "Š_Lower-Left____č",
    "lowerRight": "Š_Lower-Right____č",
    "upperLeft": "Š_Upper-Left____č",
    "upperRight": "Š_Upper-Right____č",
    "center": "Š_Center___č",
    "alphaNumeric": "Š_Alpha-Numeric_____č",
    "alphaAlpha": "Š_Alpha-Alpha____č",
    "numeric": "Š_Numeric___č",
    "horizontal": "Š_Horizontal____č",
    "vertical": "Š_Vertical___č",
    "MGRS": "Š_MGRS__č",
    "USNG": "Š_USNG__č",
    "showLabels": "Š_Show Labels____č"
  },
  "publishTitle": "Š_Publish GRG to Portal_______č",
  "publishGRGBtn": "Š_Publish___č",
  "GRGLayerName": "Š_Published GRG Layer Name________č",
  "invalidGRGLayerName": "Š_Layer name must only contain alpha-numeric characters and underscores______________________č",
  "missingGRGLayerName": "Š_You must enter a name for the GRG___________č",
  "publishingFailedLayerExists": "Š_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________č.",
  "checkService": "Š_Check Service: {0}______č",
  "createService": "Š_Create Service: {0}_______č",
  "unableToCreate": "Š_Unable to create: {0}_______č",
  "addToDefinition": "Š_Add to definition: {0}________č",
  "successfullyPublished": "Š_Successfully published web layer{0}Manage the web layer__________________č",
  "userRole": "Š_Unable to create service because user does not have permissions____________________č",
  "createGRGBtn": "Š_Create GRG____č",
  "clearGRGBtn": "Š_Clear___č",
  "labelFormat": "Š_Label Format_____č",
  "helpIconTooltip": "Š_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________č",
  "addPointToolTip": "Š_Add GRG Origin_____č",
  "cellWidth": "Š_Cell Width (x)_____č",
  "cellHeight": "Š_Cell Height (y)______č",
  "invalidNumberMessage": "Š_The value entered is not valid__________č",
  "invalidRangeMessage": "Š_Value must be greater than 0_________č",
  "gridAngleInvalidRangeMessage": "Š_Value must be between -89.9 and 89.9____________č",
  "formatIconTooltip": "Š_Format Input_____č",
  "coordInputLabel": "Š_GRG Origin (DD)______č",
  "setCoordFormat": "Š_Set Coordinate Format String_________č",
  "prefixNumbers": "Š_Add '+/-' prefix to positive and negative numbers________________č",
  "cancelBtn": "Š_Cancel___č",
  "applyBtn": "Š_Apply___č",
  "comfirmInputNotation": "Š_Confirm Input Notation________č",
  "notationsMatch": "Š_notations match your input please confirm which you would like to use______________________č:",
  "numberOfCellsHorizontal": "Š_# Horizontal Cells______č",
  "numberOfCellsVertical": "Š_# Vertical Cells______č",
  "gridAngle": "Š_Grid Rotation_____č",
  "tooManyCellsErrorMessage": "Š_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________č.",
  "missingParametersMessage": "Š_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________č",
  "missingOriginParametersMessage": "Š_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________č",
  "invalidWidthHeightParametersMessage": "Š_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________č",
  "invalidHorizontalVerticalParametersMessage": "Š_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________č",
  "drawPointToolTip": "Š_Click to add GRG origin point__________č",
  "missingLayerNameMessage": "Š_You must enter a valid layer name before you can publish__________________č",
  "parseCoordinatesError": "Š_Unable to parse coordinates. Please check your input_________________č.",
  "grgPolarRegionError": "Š_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________č.",
  "grgPolarOriginError": "Š_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________č.",
  "DD": "Š_DD__č",
  "DDM": "Š_DDM__č",
  "DMS": "Š_DMS__č",
  "DDRev": "Š_DDRev___č",
  "DDMRev": "Š_DDMRev___č",
  "DMSRev": "Š_DMSRev___č",
  "USNG": "Š_USNG__č",
  "MGRS": "Š_MGRS__č",
  "UTM_H": "Š_UTM (H)___č",
  "UTM": "Š_UTM__č",
  "GARS": "Š_GARS__č",
  "GEOREF": "Š_GEOREF___č",
  "DDLatLongNotation": "Š_Decimal Degrees - Latitude/Longitude____________č",
  "DDLongLatNotation": "Š_Decimal Degrees  - Longitude/Latitude____________č",
  "DDMLatLongNotation": "Š_Degrees Decimal Minutes - Latitude/Longitude______________č",
  "DDMLongLatNotation": "Š_Degrees Decimal Minutes - Longitude/Latitude______________č",
  "DMSLatLongNotation": "Š_Degrees Minutes Seconds - Latitude/Longitude______________č",
  "DMSLongLatNotation": "Š_Degrees Minutes Seconds - Longitude/Latitude______________č",
  "GARSNotation": "Š_GARS__č",
  "GEOREFNotation": "Š_GEOREF___č",
  "MGRSNotation": "Š_MGRS__č",
  "USNGNotation": "Š_USNG__č",
  "UTMBandNotation": "Š_UTM - Band Letter______č",
  "UTMHemNotation": "Š_UTM - Hemisphere (N/S)________č"
});