define({
  "gridTabLabel": "Ă_Grid__ș",
  "labelTabLabel": "Ă_Labels___ș",
  "referenceSystemTabLabel": "Ă_Reference System______ș",
  "gridTabDescription": "Ă_Set the appearance and behavior of the grid cells________________ș.",
  "cellOutlineColor": "Ă_Cell Outine color______ș",
  "cellFillColor": "Ă_Cell Fill color______ș",
  "transparency": "Ă_Transparency_____ș",
  "cellShapeDropDown": "Ă_Cell Shape____ș",
  "default": "Ă_Rectangle____ș",
  "hexagon": "Ă_Hexagon___ș",
  "cellUnitsDropDown": "Ă_Cell Units____ș",
  "miles": "Ă_Miles___ș",
  "kilometers": "Ă_Kilometers____ș",
  "feet": "Ă_Feet__ș",
  "meters": "Ă_Meters___ș",
  "yards": "Ă_Yards___ș",
  "nautical-miles": "Ă_Nautical Miles_____ș",
  "gridOriginDropDown": "Ă_Grid Origin____ș",
  "lowerLeft": "Ă_Lower-Left____ș",
  "lowerRight": "Ă_Lower-Right____ș",
  "upperLeft": "Ă_Upper-Left____ș",
  "upperRight": "Ă_Upper-Right____ș",
  "center": "Ă_Center___ș",
  "labelTabDescription": "Ă_Set the appearance and behavior of the grid labels________________ș.",
  "labelSettings": "Ă_Label Style____ș",
  "font": "Ă_Font__ș",
  "textSize": "Ă_Text Size____ș",
  "textColor": "Ă_Text Color____ș",
  "halo": "Ă_Halo__ș",
  "show": "Ă_Show__ș",
  "labelTypeDropDown": "Ă_Label Type____ș",
  "alphaNumeric": "Ă_Alpha-Numeric_____ș",
  "alphaAlpha": "Ă_Alpha-Alpha____ș",
  "numeric": "Ă_Numeric___ș",
  "labelDirectionDropDown": "Ă_Label Direction______ș",
  "horizontal": "Ă_Horizontal____ș",
  "vertical": "Ă_Vertical___ș",
  "labelOriginDropDown": "Ă_Label Origin_____ș",
  "referenceSystemlTabDescription": "Ă_Set the default reference system___________ș.",
  "MGRS": "Ă_MGRS__ș",
  "USNG": "Ă_USNG__ș",
  "lockSettings": "Ă_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________ș"
});