define({
  "gridTabLabel": "כן_Grid__ש",
  "labelTabLabel": "כן_Labels___ש",
  "referenceSystemTabLabel": "כן_Reference System______ש",
  "gridTabDescription": "כן_Set the appearance and behavior of the grid cells________________ש.",
  "cellOutlineColor": "כן_Cell Outine color______ש",
  "cellFillColor": "כן_Cell Fill color______ש",
  "transparency": "כן_Transparency_____ש",
  "cellShapeDropDown": "כן_Cell Shape____ש",
  "default": "כן_Rectangle____ש",
  "hexagon": "כן_Hexagon___ש",
  "cellUnitsDropDown": "כן_Cell Units____ש",
  "miles": "כן_Miles___ש",
  "kilometers": "כן_Kilometers____ש",
  "feet": "כן_Feet__ש",
  "meters": "כן_Meters___ש",
  "yards": "כן_Yards___ש",
  "nautical-miles": "כן_Nautical Miles_____ש",
  "gridOriginDropDown": "כן_Grid Origin____ש",
  "lowerLeft": "כן_Lower-Left____ש",
  "lowerRight": "כן_Lower-Right____ש",
  "upperLeft": "כן_Upper-Left____ש",
  "upperRight": "כן_Upper-Right____ש",
  "center": "כן_Center___ש",
  "labelTabDescription": "כן_Set the appearance and behavior of the grid labels________________ש.",
  "labelSettings": "כן_Label Style____ש",
  "font": "כן_Font__ש",
  "textSize": "כן_Text Size____ש",
  "textColor": "כן_Text Color____ש",
  "halo": "כן_Halo__ש",
  "show": "כן_Show__ש",
  "labelTypeDropDown": "כן_Label Type____ש",
  "alphaNumeric": "כן_Alpha-Numeric_____ש",
  "alphaAlpha": "כן_Alpha-Alpha____ש",
  "numeric": "כן_Numeric___ש",
  "labelDirectionDropDown": "כן_Label Direction______ש",
  "horizontal": "כן_Horizontal____ש",
  "vertical": "כן_Vertical___ש",
  "labelOriginDropDown": "כן_Label Origin_____ש",
  "referenceSystemlTabDescription": "כן_Set the default reference system___________ש.",
  "MGRS": "כן_MGRS__ש",
  "USNG": "כן_USNG__ש",
  "lockSettings": "כן_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________ש"
});