define({
  "_widgetLabel": "ı_Gridded Reference Graphic_________İ",
  "newGRGFromAreaButtonLabel": "ı_Define a Grid from an Area_________İ",
  "newGRGFromPointButtonLabel": "ı_Define a Grid from a Point_________İ",
  "newGRGFromAreaTitle": "ı_Define a Grid from an Area_________İ",
  "newGRGFromPointTitle": "ı_Define a Grid from a Point_________İ",
  "newGRGBySizeButtonLabel": "ı_By Dimension_____İ",
  "newGRGFromRefSystemButtonLabel": "ı_By Reference System_______İ",
  "newGRGByTimeLabel": "ı_By Time and Speed______İ",
  "newGRGFromNonStandardButtonLabel": "ı_Define Non-Standard Grid________İ",
  "newGRGAreaBySizeTitle": "ı_GRG from an Area by Dimension__________İ",
  "newGRGAreaBySizeDefineAreaLabel": "ı_GRG Area___İ",
  "addGRGAreaPolygonToolTip": "ı_Draw GRG Area using polygon_________İ",
  "addGRGAreaExtentToolTip": "ı_Draw GRG Area using extent_________İ",
  "rotation": "ı_Grid Rotation_____İ",
  "numberRowsColumnsLabel": "ı_Define number of rows and columns___________İ",
  "newGRGAreaByRefSystemTitle": "ı_GRG from an Area by Reference System____________İ",
  "gridSize": "ı_Grid Size____İ",
  "UTMZoneandBand": "ı_Grid Zone____İ",
  "100000m": "ı_100000 meter_____İ",
  "10000m": "ı_10000 meter____İ",
  "1000m": "ı_1000 meter____İ",
  "100m": "ı_100 meter____İ",
  "10m": "ı_10 meter___İ",
  "clipGrid": "ı_Clip Grid to GRG Area_______İ",
  "newGRGAreaFromNonStandardTitle": "ı_New NRG___İ",
  "newGRGPointBySizeTitle": "ı_GRG from Point by Dimension_________İ",
  "newGRGPointByRefSystemTitle": "ı_GRG from Point by Reference System___________İ",
  "newGRGPointByTimeTitle": "ı_GRG from Point using Time and Speed____________İ",
  "time": "ı_Time__İ",
  "rate": "ı_Speed___İ",
  "hours": "ı_Hours___İ",
  "minutes": "ı_Minutes___İ",
  "seconds": "ı_Seconds___İ",
  "ftPerSec": "ı_Feet / second_____İ",
  "ftPerHour": "ı_Feet / hour____İ",
  "kmPerSec": "ı_Kilometers / second_______İ",
  "kmPerHour": "ı_Kilometers / hour______İ",
  "mPerSec": "ı_Meters / second______İ",
  "mPerHour": "ı_Meters / hour_____İ",
  "miPerSec": "ı_Miles / second_____İ",
  "miPerHour": "ı_Miles / hour_____İ",
  "nMPerSec": "ı_Nautical Miles / second________İ",
  "nMPerHour": "ı_Nautical Miles / hour_______İ",
  "settingsTitle": "ı_Settings___İ",
  "labelSettingsLabel": "ı_Label Settings_____İ",
  "labelSettingsButtonLabel": "ı_Configure Label Settings________İ",
  "gridSettingsLabel": "ı_Grid Settings_____İ",
  "gridSettingsButtonLabel": "ı_Configure Grid Settings________İ",
  "transparency": "ı_Transparency_____İ",
  "labelStyle": "ı_Label Style____İ",
  "font": "ı_Font__İ",
  "textSize": "ı_Text Size____İ",
  "textColor": "ı_Text Color____İ",
  "halo": "ı_Halo__İ",
  "show": "ı_Show__İ",
  "lockSettings": "ı_Settings have been locked by the application owner________________İ",
  "gridSettings": {
    "cellShape": "ı_Cell Shape____İ",
    "cellUnits": "ı_Cell Units____İ",
    "cellOutline": "ı_Cell Outline Settings_______İ",
    "cellFill": "ı_Cell Fill Settings______İ",
    "gridReferenceSystem": "ı_Reference System______İ",
    "gridDatum": "ı_Datum: WGS84_____İ",
    "labelStartPosition": "ı_Label Origin_____İ",
    "labelType": "ı_Label Type____İ",
    "labelDirection": "ı_Label Direction______İ",
    "gridOrigin": "ı_Grid Origin____İ",
    "default": "ı_Rectangle____İ",
    "hexagon": "ı_Hexagon___İ",
    "miles": "ı_Miles___İ",
    "kilometers": "ı_Kilometers____İ",
    "feet": "ı_Feet__İ",
    "meters": "ı_Meters___İ",
    "yards": "ı_Yards___İ",
    "nautical-miles": "ı_Nautical Miles_____İ",
    "lowerLeft": "ı_Lower-Left____İ",
    "lowerRight": "ı_Lower-Right____İ",
    "upperLeft": "ı_Upper-Left____İ",
    "upperRight": "ı_Upper-Right____İ",
    "center": "ı_Center___İ",
    "alphaNumeric": "ı_Alpha-Numeric_____İ",
    "alphaAlpha": "ı_Alpha-Alpha____İ",
    "numeric": "ı_Numeric___İ",
    "horizontal": "ı_Horizontal____İ",
    "vertical": "ı_Vertical___İ",
    "MGRS": "ı_MGRS__İ",
    "USNG": "ı_USNG__İ",
    "showLabels": "ı_Show Labels____İ"
  },
  "publishTitle": "ı_Publish GRG to Portal_______İ",
  "publishGRGBtn": "ı_Publish___İ",
  "GRGLayerName": "ı_Published GRG Layer Name________İ",
  "invalidGRGLayerName": "ı_Layer name must only contain alpha-numeric characters and underscores______________________İ",
  "missingGRGLayerName": "ı_You must enter a name for the GRG___________İ",
  "publishingFailedLayerExists": "ı_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________İ.",
  "checkService": "ı_Check Service: {0}______İ",
  "createService": "ı_Create Service: {0}_______İ",
  "unableToCreate": "ı_Unable to create: {0}_______İ",
  "addToDefinition": "ı_Add to definition: {0}________İ",
  "successfullyPublished": "ı_Successfully published web layer{0}Manage the web layer__________________İ",
  "userRole": "ı_Unable to create service because user does not have permissions____________________İ",
  "createGRGBtn": "ı_Create GRG____İ",
  "clearGRGBtn": "ı_Clear___İ",
  "labelFormat": "ı_Label Format_____İ",
  "helpIconTooltip": "ı_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________İ",
  "addPointToolTip": "ı_Add GRG Origin_____İ",
  "cellWidth": "ı_Cell Width (x)_____İ",
  "cellHeight": "ı_Cell Height (y)______İ",
  "invalidNumberMessage": "ı_The value entered is not valid__________İ",
  "invalidRangeMessage": "ı_Value must be greater than 0_________İ",
  "gridAngleInvalidRangeMessage": "ı_Value must be between -89.9 and 89.9____________İ",
  "formatIconTooltip": "ı_Format Input_____İ",
  "coordInputLabel": "ı_GRG Origin (DD)______İ",
  "setCoordFormat": "ı_Set Coordinate Format String_________İ",
  "prefixNumbers": "ı_Add '+/-' prefix to positive and negative numbers________________İ",
  "cancelBtn": "ı_Cancel___İ",
  "applyBtn": "ı_Apply___İ",
  "comfirmInputNotation": "ı_Confirm Input Notation________İ",
  "notationsMatch": "ı_notations match your input please confirm which you would like to use______________________İ:",
  "numberOfCellsHorizontal": "ı_# Horizontal Cells______İ",
  "numberOfCellsVertical": "ı_# Vertical Cells______İ",
  "gridAngle": "ı_Grid Rotation_____İ",
  "tooManyCellsErrorMessage": "ı_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________İ.",
  "missingParametersMessage": "ı_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________İ",
  "missingOriginParametersMessage": "ı_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________İ",
  "invalidWidthHeightParametersMessage": "ı_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________İ",
  "invalidHorizontalVerticalParametersMessage": "ı_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________İ",
  "drawPointToolTip": "ı_Click to add GRG origin point__________İ",
  "missingLayerNameMessage": "ı_You must enter a valid layer name before you can publish__________________İ",
  "parseCoordinatesError": "ı_Unable to parse coordinates. Please check your input_________________İ.",
  "grgPolarRegionError": "ı_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________İ.",
  "grgPolarOriginError": "ı_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________İ.",
  "DD": "ı_DD__İ",
  "DDM": "ı_DDM__İ",
  "DMS": "ı_DMS__İ",
  "DDRev": "ı_DDRev___İ",
  "DDMRev": "ı_DDMRev___İ",
  "DMSRev": "ı_DMSRev___İ",
  "USNG": "ı_USNG__İ",
  "MGRS": "ı_MGRS__İ",
  "UTM_H": "ı_UTM (H)___İ",
  "UTM": "ı_UTM__İ",
  "GARS": "ı_GARS__İ",
  "GEOREF": "ı_GEOREF___İ",
  "DDLatLongNotation": "ı_Decimal Degrees - Latitude/Longitude____________İ",
  "DDLongLatNotation": "ı_Decimal Degrees  - Longitude/Latitude____________İ",
  "DDMLatLongNotation": "ı_Degrees Decimal Minutes - Latitude/Longitude______________İ",
  "DDMLongLatNotation": "ı_Degrees Decimal Minutes - Longitude/Latitude______________İ",
  "DMSLatLongNotation": "ı_Degrees Minutes Seconds - Latitude/Longitude______________İ",
  "DMSLongLatNotation": "ı_Degrees Minutes Seconds - Longitude/Latitude______________İ",
  "GARSNotation": "ı_GARS__İ",
  "GEOREFNotation": "ı_GEOREF___İ",
  "MGRSNotation": "ı_MGRS__İ",
  "USNGNotation": "ı_USNG__İ",
  "UTMBandNotation": "ı_UTM - Band Letter______İ",
  "UTMHemNotation": "ı_UTM - Hemisphere (N/S)________İ"
});