define({
  "_widgetLabel": "आ_Gridded Reference Graphic_________ज",
  "newGRGFromAreaButtonLabel": "आ_Define a Grid from an Area_________ज",
  "newGRGFromPointButtonLabel": "आ_Define a Grid from a Point_________ज",
  "newGRGFromAreaTitle": "आ_Define a Grid from an Area_________ज",
  "newGRGFromPointTitle": "आ_Define a Grid from a Point_________ज",
  "newGRGBySizeButtonLabel": "आ_By Dimension_____ज",
  "newGRGFromRefSystemButtonLabel": "आ_By Reference System_______ज",
  "newGRGByTimeLabel": "आ_By Time and Speed______ज",
  "newGRGFromNonStandardButtonLabel": "आ_Define Non-Standard Grid________ज",
  "newGRGAreaBySizeTitle": "आ_GRG from an Area by Dimension__________ज",
  "newGRGAreaBySizeDefineAreaLabel": "आ_GRG Area___ज",
  "addGRGAreaPolygonToolTip": "आ_Draw GRG Area using polygon_________ज",
  "addGRGAreaExtentToolTip": "आ_Draw GRG Area using extent_________ज",
  "rotation": "आ_Grid Rotation_____ज",
  "numberRowsColumnsLabel": "आ_Define number of rows and columns___________ज",
  "newGRGAreaByRefSystemTitle": "आ_GRG from an Area by Reference System____________ज",
  "gridSize": "आ_Grid Size____ज",
  "UTMZoneandBand": "आ_Grid Zone____ज",
  "100000m": "आ_100000 meter_____ज",
  "10000m": "आ_10000 meter____ज",
  "1000m": "आ_1000 meter____ज",
  "100m": "आ_100 meter____ज",
  "10m": "आ_10 meter___ज",
  "clipGrid": "आ_Clip Grid to GRG Area_______ज",
  "newGRGAreaFromNonStandardTitle": "आ_New NRG___ज",
  "newGRGPointBySizeTitle": "आ_GRG from Point by Dimension_________ज",
  "newGRGPointByRefSystemTitle": "आ_GRG from Point by Reference System___________ज",
  "newGRGPointByTimeTitle": "आ_GRG from Point using Time and Speed____________ज",
  "time": "आ_Time__ज",
  "rate": "आ_Speed___ज",
  "hours": "आ_Hours___ज",
  "minutes": "आ_Minutes___ज",
  "seconds": "आ_Seconds___ज",
  "ftPerSec": "आ_Feet / second_____ज",
  "ftPerHour": "आ_Feet / hour____ज",
  "kmPerSec": "आ_Kilometers / second_______ज",
  "kmPerHour": "आ_Kilometers / hour______ज",
  "mPerSec": "आ_Meters / second______ज",
  "mPerHour": "आ_Meters / hour_____ज",
  "miPerSec": "आ_Miles / second_____ज",
  "miPerHour": "आ_Miles / hour_____ज",
  "nMPerSec": "आ_Nautical Miles / second________ज",
  "nMPerHour": "आ_Nautical Miles / hour_______ज",
  "settingsTitle": "आ_Settings___ज",
  "labelSettingsLabel": "आ_Label Settings_____ज",
  "labelSettingsButtonLabel": "आ_Configure Label Settings________ज",
  "gridSettingsLabel": "आ_Grid Settings_____ज",
  "gridSettingsButtonLabel": "आ_Configure Grid Settings________ज",
  "transparency": "आ_Transparency_____ज",
  "labelStyle": "आ_Label Style____ज",
  "font": "आ_Font__ज",
  "textSize": "आ_Text Size____ज",
  "textColor": "आ_Text Color____ज",
  "halo": "आ_Halo__ज",
  "show": "आ_Show__ज",
  "lockSettings": "आ_Settings have been locked by the application owner________________ज",
  "gridSettings": {
    "cellShape": "आ_Cell Shape____ज",
    "cellUnits": "आ_Cell Units____ज",
    "cellOutline": "आ_Cell Outline Settings_______ज",
    "cellFill": "आ_Cell Fill Settings______ज",
    "gridReferenceSystem": "आ_Reference System______ज",
    "gridDatum": "आ_Datum: WGS84_____ज",
    "labelStartPosition": "आ_Label Origin_____ज",
    "labelType": "आ_Label Type____ज",
    "labelDirection": "आ_Label Direction______ज",
    "gridOrigin": "आ_Grid Origin____ज",
    "default": "आ_Rectangle____ज",
    "hexagon": "आ_Hexagon___ज",
    "miles": "आ_Miles___ज",
    "kilometers": "आ_Kilometers____ज",
    "feet": "आ_Feet__ज",
    "meters": "आ_Meters___ज",
    "yards": "आ_Yards___ज",
    "nautical-miles": "आ_Nautical Miles_____ज",
    "lowerLeft": "आ_Lower-Left____ज",
    "lowerRight": "आ_Lower-Right____ज",
    "upperLeft": "आ_Upper-Left____ज",
    "upperRight": "आ_Upper-Right____ज",
    "center": "आ_Center___ज",
    "alphaNumeric": "आ_Alpha-Numeric_____ज",
    "alphaAlpha": "आ_Alpha-Alpha____ज",
    "numeric": "आ_Numeric___ज",
    "horizontal": "आ_Horizontal____ज",
    "vertical": "आ_Vertical___ज",
    "MGRS": "आ_MGRS__ज",
    "USNG": "आ_USNG__ज",
    "showLabels": "आ_Show Labels____ज"
  },
  "publishTitle": "आ_Publish GRG to Portal_______ज",
  "publishGRGBtn": "आ_Publish___ज",
  "GRGLayerName": "आ_Published GRG Layer Name________ज",
  "invalidGRGLayerName": "आ_Layer name must only contain alpha-numeric characters and underscores______________________ज",
  "missingGRGLayerName": "आ_You must enter a name for the GRG___________ज",
  "publishingFailedLayerExists": "आ_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ज.",
  "checkService": "आ_Check Service: {0}______ज",
  "createService": "आ_Create Service: {0}_______ज",
  "unableToCreate": "आ_Unable to create: {0}_______ज",
  "addToDefinition": "आ_Add to definition: {0}________ज",
  "successfullyPublished": "आ_Successfully published web layer{0}Manage the web layer__________________ज",
  "userRole": "आ_Unable to create service because user does not have permissions____________________ज",
  "createGRGBtn": "आ_Create GRG____ज",
  "clearGRGBtn": "आ_Clear___ज",
  "labelFormat": "आ_Label Format_____ज",
  "helpIconTooltip": "आ_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________ज",
  "addPointToolTip": "आ_Add GRG Origin_____ज",
  "cellWidth": "आ_Cell Width (x)_____ज",
  "cellHeight": "आ_Cell Height (y)______ज",
  "invalidNumberMessage": "आ_The value entered is not valid__________ज",
  "invalidRangeMessage": "आ_Value must be greater than 0_________ज",
  "gridAngleInvalidRangeMessage": "आ_Value must be between -89.9 and 89.9____________ज",
  "formatIconTooltip": "आ_Format Input_____ज",
  "coordInputLabel": "आ_GRG Origin (DD)______ज",
  "setCoordFormat": "आ_Set Coordinate Format String_________ज",
  "prefixNumbers": "आ_Add '+/-' prefix to positive and negative numbers________________ज",
  "cancelBtn": "आ_Cancel___ज",
  "applyBtn": "आ_Apply___ज",
  "comfirmInputNotation": "आ_Confirm Input Notation________ज",
  "notationsMatch": "आ_notations match your input please confirm which you would like to use______________________ज:",
  "numberOfCellsHorizontal": "आ_# Horizontal Cells______ज",
  "numberOfCellsVertical": "आ_# Vertical Cells______ज",
  "gridAngle": "आ_Grid Rotation_____ज",
  "tooManyCellsErrorMessage": "आ_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________ज.",
  "missingParametersMessage": "आ_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________ज",
  "missingOriginParametersMessage": "आ_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________ज",
  "invalidWidthHeightParametersMessage": "आ_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________ज",
  "invalidHorizontalVerticalParametersMessage": "आ_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________ज",
  "drawPointToolTip": "आ_Click to add GRG origin point__________ज",
  "missingLayerNameMessage": "आ_You must enter a valid layer name before you can publish__________________ज",
  "parseCoordinatesError": "आ_Unable to parse coordinates. Please check your input_________________ज.",
  "grgPolarRegionError": "आ_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________ज.",
  "grgPolarOriginError": "आ_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________ज.",
  "DD": "आ_DD__ज",
  "DDM": "आ_DDM__ज",
  "DMS": "आ_DMS__ज",
  "DDRev": "आ_DDRev___ज",
  "DDMRev": "आ_DDMRev___ज",
  "DMSRev": "आ_DMSRev___ज",
  "USNG": "आ_USNG__ज",
  "MGRS": "आ_MGRS__ज",
  "UTM_H": "आ_UTM (H)___ज",
  "UTM": "आ_UTM__ज",
  "GARS": "आ_GARS__ज",
  "GEOREF": "आ_GEOREF___ज",
  "DDLatLongNotation": "आ_Decimal Degrees - Latitude/Longitude____________ज",
  "DDLongLatNotation": "आ_Decimal Degrees  - Longitude/Latitude____________ज",
  "DDMLatLongNotation": "आ_Degrees Decimal Minutes - Latitude/Longitude______________ज",
  "DDMLongLatNotation": "आ_Degrees Decimal Minutes - Longitude/Latitude______________ज",
  "DMSLatLongNotation": "आ_Degrees Minutes Seconds - Latitude/Longitude______________ज",
  "DMSLongLatNotation": "आ_Degrees Minutes Seconds - Longitude/Latitude______________ज",
  "GARSNotation": "आ_GARS__ज",
  "GEOREFNotation": "आ_GEOREF___ज",
  "MGRSNotation": "आ_MGRS__ज",
  "USNGNotation": "आ_USNG__ज",
  "UTMBandNotation": "आ_UTM - Band Letter______ज",
  "UTMHemNotation": "आ_UTM - Hemisphere (N/S)________ज"
});