define({
  "_widgetLabel": "å_Gridded Reference Graphic_________ø",
  "newGRGFromAreaButtonLabel": "å_Define a Grid from an Area_________ø",
  "newGRGFromPointButtonLabel": "å_Define a Grid from a Point_________ø",
  "newGRGFromAreaTitle": "å_Define a Grid from an Area_________ø",
  "newGRGFromPointTitle": "å_Define a Grid from a Point_________ø",
  "newGRGBySizeButtonLabel": "å_By Dimension_____ø",
  "newGRGFromRefSystemButtonLabel": "å_By Reference System_______ø",
  "newGRGByTimeLabel": "å_By Time and Speed______ø",
  "newGRGFromNonStandardButtonLabel": "å_Define Non-Standard Grid________ø",
  "newGRGAreaBySizeTitle": "å_GRG from an Area by Dimension__________ø",
  "newGRGAreaBySizeDefineAreaLabel": "å_GRG Area___ø",
  "addGRGAreaPolygonToolTip": "å_Draw GRG Area using polygon_________ø",
  "addGRGAreaExtentToolTip": "å_Draw GRG Area using extent_________ø",
  "rotation": "å_Grid Rotation_____ø",
  "numberRowsColumnsLabel": "å_Define number of rows and columns___________ø",
  "newGRGAreaByRefSystemTitle": "å_GRG from an Area by Reference System____________ø",
  "gridSize": "å_Grid Size____ø",
  "UTMZoneandBand": "å_Grid Zone____ø",
  "100000m": "å_100000 meter_____ø",
  "10000m": "å_10000 meter____ø",
  "1000m": "å_1000 meter____ø",
  "100m": "å_100 meter____ø",
  "10m": "å_10 meter___ø",
  "clipGrid": "å_Clip Grid to GRG Area_______ø",
  "newGRGAreaFromNonStandardTitle": "å_New NRG___ø",
  "newGRGPointBySizeTitle": "å_GRG from Point by Dimension_________ø",
  "newGRGPointByRefSystemTitle": "å_GRG from Point by Reference System___________ø",
  "newGRGPointByTimeTitle": "å_GRG from Point using Time and Speed____________ø",
  "time": "å_Time__ø",
  "rate": "å_Speed___ø",
  "hours": "å_Hours___ø",
  "minutes": "å_Minutes___ø",
  "seconds": "å_Seconds___ø",
  "ftPerSec": "å_Feet / second_____ø",
  "ftPerHour": "å_Feet / hour____ø",
  "kmPerSec": "å_Kilometers / second_______ø",
  "kmPerHour": "å_Kilometers / hour______ø",
  "mPerSec": "å_Meters / second______ø",
  "mPerHour": "å_Meters / hour_____ø",
  "miPerSec": "å_Miles / second_____ø",
  "miPerHour": "å_Miles / hour_____ø",
  "nMPerSec": "å_Nautical Miles / second________ø",
  "nMPerHour": "å_Nautical Miles / hour_______ø",
  "settingsTitle": "å_Settings___ø",
  "labelSettingsLabel": "å_Label Settings_____ø",
  "labelSettingsButtonLabel": "å_Configure Label Settings________ø",
  "gridSettingsLabel": "å_Grid Settings_____ø",
  "gridSettingsButtonLabel": "å_Configure Grid Settings________ø",
  "transparency": "å_Transparency_____ø",
  "labelStyle": "å_Label Style____ø",
  "font": "å_Font__ø",
  "textSize": "å_Text Size____ø",
  "textColor": "å_Text Color____ø",
  "halo": "å_Halo__ø",
  "show": "å_Show__ø",
  "lockSettings": "å_Settings have been locked by the application owner________________ø",
  "gridSettings": {
    "cellShape": "å_Cell Shape____ø",
    "cellUnits": "å_Cell Units____ø",
    "cellOutline": "å_Cell Outline Settings_______ø",
    "cellFill": "å_Cell Fill Settings______ø",
    "gridReferenceSystem": "å_Reference System______ø",
    "gridDatum": "å_Datum: WGS84_____ø",
    "labelStartPosition": "å_Label Origin_____ø",
    "labelType": "å_Label Type____ø",
    "labelDirection": "å_Label Direction______ø",
    "gridOrigin": "å_Grid Origin____ø",
    "default": "å_Rectangle____ø",
    "hexagon": "å_Hexagon___ø",
    "miles": "å_Miles___ø",
    "kilometers": "å_Kilometers____ø",
    "feet": "å_Feet__ø",
    "meters": "å_Meters___ø",
    "yards": "å_Yards___ø",
    "nautical-miles": "å_Nautical Miles_____ø",
    "lowerLeft": "å_Lower-Left____ø",
    "lowerRight": "å_Lower-Right____ø",
    "upperLeft": "å_Upper-Left____ø",
    "upperRight": "å_Upper-Right____ø",
    "center": "å_Center___ø",
    "alphaNumeric": "å_Alpha-Numeric_____ø",
    "alphaAlpha": "å_Alpha-Alpha____ø",
    "numeric": "å_Numeric___ø",
    "horizontal": "å_Horizontal____ø",
    "vertical": "å_Vertical___ø",
    "MGRS": "å_MGRS__ø",
    "USNG": "å_USNG__ø",
    "showLabels": "å_Show Labels____ø"
  },
  "publishTitle": "å_Publish GRG to Portal_______ø",
  "publishGRGBtn": "å_Publish___ø",
  "GRGLayerName": "å_Published GRG Layer Name________ø",
  "invalidGRGLayerName": "å_Layer name must only contain alpha-numeric characters and underscores______________________ø",
  "missingGRGLayerName": "å_You must enter a name for the GRG___________ø",
  "publishingFailedLayerExists": "å_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ø.",
  "checkService": "å_Check Service: {0}______ø",
  "createService": "å_Create Service: {0}_______ø",
  "unableToCreate": "å_Unable to create: {0}_______ø",
  "addToDefinition": "å_Add to definition: {0}________ø",
  "successfullyPublished": "å_Successfully published web layer{0}Manage the web layer__________________ø",
  "userRole": "å_Unable to create service because user does not have permissions____________________ø",
  "createGRGBtn": "å_Create GRG____ø",
  "clearGRGBtn": "å_Clear___ø",
  "labelFormat": "å_Label Format_____ø",
  "helpIconTooltip": "å_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________ø",
  "addPointToolTip": "å_Add GRG Origin_____ø",
  "cellWidth": "å_Cell Width (x)_____ø",
  "cellHeight": "å_Cell Height (y)______ø",
  "invalidNumberMessage": "å_The value entered is not valid__________ø",
  "invalidRangeMessage": "å_Value must be greater than 0_________ø",
  "gridAngleInvalidRangeMessage": "å_Value must be between -89.9 and 89.9____________ø",
  "formatIconTooltip": "å_Format Input_____ø",
  "coordInputLabel": "å_GRG Origin (DD)______ø",
  "setCoordFormat": "å_Set Coordinate Format String_________ø",
  "prefixNumbers": "å_Add '+/-' prefix to positive and negative numbers________________ø",
  "cancelBtn": "å_Cancel___ø",
  "applyBtn": "å_Apply___ø",
  "comfirmInputNotation": "å_Confirm Input Notation________ø",
  "notationsMatch": "å_notations match your input please confirm which you would like to use______________________ø:",
  "numberOfCellsHorizontal": "å_# Horizontal Cells______ø",
  "numberOfCellsVertical": "å_# Vertical Cells______ø",
  "gridAngle": "å_Grid Rotation_____ø",
  "tooManyCellsErrorMessage": "å_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________ø.",
  "missingParametersMessage": "å_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________ø",
  "missingOriginParametersMessage": "å_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________ø",
  "invalidWidthHeightParametersMessage": "å_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________ø",
  "invalidHorizontalVerticalParametersMessage": "å_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________ø",
  "drawPointToolTip": "å_Click to add GRG origin point__________ø",
  "missingLayerNameMessage": "å_You must enter a valid layer name before you can publish__________________ø",
  "parseCoordinatesError": "å_Unable to parse coordinates. Please check your input_________________ø.",
  "grgPolarRegionError": "å_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________ø.",
  "grgPolarOriginError": "å_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________ø.",
  "DD": "å_DD__ø",
  "DDM": "å_DDM__ø",
  "DMS": "å_DMS__ø",
  "DDRev": "å_DDRev___ø",
  "DDMRev": "å_DDMRev___ø",
  "DMSRev": "å_DMSRev___ø",
  "USNG": "å_USNG__ø",
  "MGRS": "å_MGRS__ø",
  "UTM_H": "å_UTM (H)___ø",
  "UTM": "å_UTM__ø",
  "GARS": "å_GARS__ø",
  "GEOREF": "å_GEOREF___ø",
  "DDLatLongNotation": "å_Decimal Degrees - Latitude/Longitude____________ø",
  "DDLongLatNotation": "å_Decimal Degrees  - Longitude/Latitude____________ø",
  "DDMLatLongNotation": "å_Degrees Decimal Minutes - Latitude/Longitude______________ø",
  "DDMLongLatNotation": "å_Degrees Decimal Minutes - Longitude/Latitude______________ø",
  "DMSLatLongNotation": "å_Degrees Minutes Seconds - Latitude/Longitude______________ø",
  "DMSLongLatNotation": "å_Degrees Minutes Seconds - Longitude/Latitude______________ø",
  "GARSNotation": "å_GARS__ø",
  "GEOREFNotation": "å_GEOREF___ø",
  "MGRSNotation": "å_MGRS__ø",
  "USNGNotation": "å_USNG__ø",
  "UTMBandNotation": "å_UTM - Band Letter______ø",
  "UTMHemNotation": "å_UTM - Hemisphere (N/S)________ø"
});