define({
  "_widgetLabel": "ķ_Gridded Reference Graphic_________ū",
  "newGRGFromAreaButtonLabel": "ķ_Define a Grid from an Area_________ū",
  "newGRGFromPointButtonLabel": "ķ_Define a Grid from a Point_________ū",
  "newGRGFromAreaTitle": "ķ_Define a Grid from an Area_________ū",
  "newGRGFromPointTitle": "ķ_Define a Grid from a Point_________ū",
  "newGRGBySizeButtonLabel": "ķ_By Dimension_____ū",
  "newGRGFromRefSystemButtonLabel": "ķ_By Reference System_______ū",
  "newGRGByTimeLabel": "ķ_By Time and Speed______ū",
  "newGRGFromNonStandardButtonLabel": "ķ_Define Non-Standard Grid________ū",
  "newGRGAreaBySizeTitle": "ķ_GRG from an Area by Dimension__________ū",
  "newGRGAreaBySizeDefineAreaLabel": "ķ_GRG Area___ū",
  "addGRGAreaPolygonToolTip": "ķ_Draw GRG Area using polygon_________ū",
  "addGRGAreaExtentToolTip": "ķ_Draw GRG Area using extent_________ū",
  "rotation": "ķ_Grid Rotation_____ū",
  "numberRowsColumnsLabel": "ķ_Define number of rows and columns___________ū",
  "newGRGAreaByRefSystemTitle": "ķ_GRG from an Area by Reference System____________ū",
  "gridSize": "ķ_Grid Size____ū",
  "UTMZoneandBand": "ķ_Grid Zone____ū",
  "100000m": "ķ_100000 meter_____ū",
  "10000m": "ķ_10000 meter____ū",
  "1000m": "ķ_1000 meter____ū",
  "100m": "ķ_100 meter____ū",
  "10m": "ķ_10 meter___ū",
  "clipGrid": "ķ_Clip Grid to GRG Area_______ū",
  "newGRGAreaFromNonStandardTitle": "ķ_New NRG___ū",
  "newGRGPointBySizeTitle": "ķ_GRG from Point by Dimension_________ū",
  "newGRGPointByRefSystemTitle": "ķ_GRG from Point by Reference System___________ū",
  "newGRGPointByTimeTitle": "ķ_GRG from Point using Time and Speed____________ū",
  "time": "ķ_Time__ū",
  "rate": "ķ_Speed___ū",
  "hours": "ķ_Hours___ū",
  "minutes": "ķ_Minutes___ū",
  "seconds": "ķ_Seconds___ū",
  "ftPerSec": "ķ_Feet / second_____ū",
  "ftPerHour": "ķ_Feet / hour____ū",
  "kmPerSec": "ķ_Kilometers / second_______ū",
  "kmPerHour": "ķ_Kilometers / hour______ū",
  "mPerSec": "ķ_Meters / second______ū",
  "mPerHour": "ķ_Meters / hour_____ū",
  "miPerSec": "ķ_Miles / second_____ū",
  "miPerHour": "ķ_Miles / hour_____ū",
  "nMPerSec": "ķ_Nautical Miles / second________ū",
  "nMPerHour": "ķ_Nautical Miles / hour_______ū",
  "settingsTitle": "ķ_Settings___ū",
  "labelSettingsLabel": "ķ_Label Settings_____ū",
  "labelSettingsButtonLabel": "ķ_Configure Label Settings________ū",
  "gridSettingsLabel": "ķ_Grid Settings_____ū",
  "gridSettingsButtonLabel": "ķ_Configure Grid Settings________ū",
  "transparency": "ķ_Transparency_____ū",
  "labelStyle": "ķ_Label Style____ū",
  "font": "ķ_Font__ū",
  "textSize": "ķ_Text Size____ū",
  "textColor": "ķ_Text Color____ū",
  "halo": "ķ_Halo__ū",
  "show": "ķ_Show__ū",
  "lockSettings": "ķ_Settings have been locked by the application owner________________ū",
  "gridSettings": {
    "cellShape": "ķ_Cell Shape____ū",
    "cellUnits": "ķ_Cell Units____ū",
    "cellOutline": "ķ_Cell Outline Settings_______ū",
    "cellFill": "ķ_Cell Fill Settings______ū",
    "gridReferenceSystem": "ķ_Reference System______ū",
    "gridDatum": "ķ_Datum: WGS84_____ū",
    "labelStartPosition": "ķ_Label Origin_____ū",
    "labelType": "ķ_Label Type____ū",
    "labelDirection": "ķ_Label Direction______ū",
    "gridOrigin": "ķ_Grid Origin____ū",
    "default": "ķ_Rectangle____ū",
    "hexagon": "ķ_Hexagon___ū",
    "miles": "ķ_Miles___ū",
    "kilometers": "ķ_Kilometers____ū",
    "feet": "ķ_Feet__ū",
    "meters": "ķ_Meters___ū",
    "yards": "ķ_Yards___ū",
    "nautical-miles": "ķ_Nautical Miles_____ū",
    "lowerLeft": "ķ_Lower-Left____ū",
    "lowerRight": "ķ_Lower-Right____ū",
    "upperLeft": "ķ_Upper-Left____ū",
    "upperRight": "ķ_Upper-Right____ū",
    "center": "ķ_Center___ū",
    "alphaNumeric": "ķ_Alpha-Numeric_____ū",
    "alphaAlpha": "ķ_Alpha-Alpha____ū",
    "numeric": "ķ_Numeric___ū",
    "horizontal": "ķ_Horizontal____ū",
    "vertical": "ķ_Vertical___ū",
    "MGRS": "ķ_MGRS__ū",
    "USNG": "ķ_USNG__ū",
    "showLabels": "ķ_Show Labels____ū"
  },
  "publishTitle": "ķ_Publish GRG to Portal_______ū",
  "publishGRGBtn": "ķ_Publish___ū",
  "GRGLayerName": "ķ_Published GRG Layer Name________ū",
  "invalidGRGLayerName": "ķ_Layer name must only contain alpha-numeric characters and underscores______________________ū",
  "missingGRGLayerName": "ķ_You must enter a name for the GRG___________ū",
  "publishingFailedLayerExists": "ķ_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________ū.",
  "checkService": "ķ_Check Service: {0}______ū",
  "createService": "ķ_Create Service: {0}_______ū",
  "unableToCreate": "ķ_Unable to create: {0}_______ū",
  "addToDefinition": "ķ_Add to definition: {0}________ū",
  "successfullyPublished": "ķ_Successfully published web layer{0}Manage the web layer__________________ū",
  "userRole": "ķ_Unable to create service because user does not have permissions____________________ū",
  "createGRGBtn": "ķ_Create GRG____ū",
  "clearGRGBtn": "ķ_Clear___ū",
  "labelFormat": "ķ_Label Format_____ū",
  "helpIconTooltip": "ķ_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________ū",
  "addPointToolTip": "ķ_Add GRG Origin_____ū",
  "cellWidth": "ķ_Cell Width (x)_____ū",
  "cellHeight": "ķ_Cell Height (y)______ū",
  "invalidNumberMessage": "ķ_The value entered is not valid__________ū",
  "invalidRangeMessage": "ķ_Value must be greater than 0_________ū",
  "gridAngleInvalidRangeMessage": "ķ_Value must be between -89.9 and 89.9____________ū",
  "formatIconTooltip": "ķ_Format Input_____ū",
  "coordInputLabel": "ķ_GRG Origin (DD)______ū",
  "setCoordFormat": "ķ_Set Coordinate Format String_________ū",
  "prefixNumbers": "ķ_Add '+/-' prefix to positive and negative numbers________________ū",
  "cancelBtn": "ķ_Cancel___ū",
  "applyBtn": "ķ_Apply___ū",
  "comfirmInputNotation": "ķ_Confirm Input Notation________ū",
  "notationsMatch": "ķ_notations match your input please confirm which you would like to use______________________ū:",
  "numberOfCellsHorizontal": "ķ_# Horizontal Cells______ū",
  "numberOfCellsVertical": "ķ_# Vertical Cells______ū",
  "gridAngle": "ķ_Grid Rotation_____ū",
  "tooManyCellsErrorMessage": "ķ_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________ū.",
  "missingParametersMessage": "ķ_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________ū",
  "missingOriginParametersMessage": "ķ_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________ū",
  "invalidWidthHeightParametersMessage": "ķ_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________ū",
  "invalidHorizontalVerticalParametersMessage": "ķ_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________ū",
  "drawPointToolTip": "ķ_Click to add GRG origin point__________ū",
  "missingLayerNameMessage": "ķ_You must enter a valid layer name before you can publish__________________ū",
  "parseCoordinatesError": "ķ_Unable to parse coordinates. Please check your input_________________ū.",
  "grgPolarRegionError": "ķ_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________ū.",
  "grgPolarOriginError": "ķ_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________ū.",
  "DD": "ķ_DD__ū",
  "DDM": "ķ_DDM__ū",
  "DMS": "ķ_DMS__ū",
  "DDRev": "ķ_DDRev___ū",
  "DDMRev": "ķ_DDMRev___ū",
  "DMSRev": "ķ_DMSRev___ū",
  "USNG": "ķ_USNG__ū",
  "MGRS": "ķ_MGRS__ū",
  "UTM_H": "ķ_UTM (H)___ū",
  "UTM": "ķ_UTM__ū",
  "GARS": "ķ_GARS__ū",
  "GEOREF": "ķ_GEOREF___ū",
  "DDLatLongNotation": "ķ_Decimal Degrees - Latitude/Longitude____________ū",
  "DDLongLatNotation": "ķ_Decimal Degrees  - Longitude/Latitude____________ū",
  "DDMLatLongNotation": "ķ_Degrees Decimal Minutes - Latitude/Longitude______________ū",
  "DDMLongLatNotation": "ķ_Degrees Decimal Minutes - Longitude/Latitude______________ū",
  "DMSLatLongNotation": "ķ_Degrees Minutes Seconds - Latitude/Longitude______________ū",
  "DMSLongLatNotation": "ķ_Degrees Minutes Seconds - Longitude/Latitude______________ū",
  "GARSNotation": "ķ_GARS__ū",
  "GEOREFNotation": "ķ_GEOREF___ū",
  "MGRSNotation": "ķ_MGRS__ū",
  "USNGNotation": "ķ_USNG__ū",
  "UTMBandNotation": "ķ_UTM - Band Letter______ū",
  "UTMHemNotation": "ķ_UTM - Hemisphere (N/S)________ū"
});