define({
  "gridTabLabel": "試_Grid__驗",
  "labelTabLabel": "試_Labels___驗",
  "referenceSystemTabLabel": "試_Reference System______驗",
  "gridTabDescription": "試_Set the appearance and behavior of the grid cells________________驗.",
  "cellOutlineColor": "試_Cell Outine color______驗",
  "cellFillColor": "試_Cell Fill color______驗",
  "transparency": "試_Transparency_____驗",
  "cellShapeDropDown": "試_Cell Shape____驗",
  "default": "試_Rectangle____驗",
  "hexagon": "試_Hexagon___驗",
  "cellUnitsDropDown": "試_Cell Units____驗",
  "miles": "試_Miles___驗",
  "kilometers": "試_Kilometers____驗",
  "feet": "試_Feet__驗",
  "meters": "試_Meters___驗",
  "yards": "試_Yards___驗",
  "nautical-miles": "試_Nautical Miles_____驗",
  "gridOriginDropDown": "試_Grid Origin____驗",
  "lowerLeft": "試_Lower-Left____驗",
  "lowerRight": "試_Lower-Right____驗",
  "upperLeft": "試_Upper-Left____驗",
  "upperRight": "試_Upper-Right____驗",
  "center": "試_Center___驗",
  "labelTabDescription": "試_Set the appearance and behavior of the grid labels________________驗.",
  "labelSettings": "試_Label Style____驗",
  "font": "試_Font__驗",
  "textSize": "試_Text Size____驗",
  "textColor": "試_Text Color____驗",
  "halo": "試_Halo__驗",
  "show": "試_Show__驗",
  "labelTypeDropDown": "試_Label Type____驗",
  "alphaNumeric": "試_Alpha-Numeric_____驗",
  "alphaAlpha": "試_Alpha-Alpha____驗",
  "numeric": "試_Numeric___驗",
  "labelDirectionDropDown": "試_Label Direction______驗",
  "horizontal": "試_Horizontal____驗",
  "vertical": "試_Vertical___驗",
  "labelOriginDropDown": "試_Label Origin_____驗",
  "referenceSystemlTabDescription": "試_Set the default reference system___________驗.",
  "MGRS": "試_MGRS__驗",
  "USNG": "試_USNG__驗",
  "lockSettings": "試_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________驗"
});