define({
  "_widgetLabel": "ä_Gridded Reference Graphic_________Ü",
  "newGRGFromAreaButtonLabel": "ä_Define a Grid from an Area_________Ü",
  "newGRGFromPointButtonLabel": "ä_Define a Grid from a Point_________Ü",
  "newGRGFromAreaTitle": "ä_Define a Grid from an Area_________Ü",
  "newGRGFromPointTitle": "ä_Define a Grid from a Point_________Ü",
  "newGRGBySizeButtonLabel": "ä_By Dimension_____Ü",
  "newGRGFromRefSystemButtonLabel": "ä_By Reference System_______Ü",
  "newGRGByTimeLabel": "ä_By Time and Speed______Ü",
  "newGRGFromNonStandardButtonLabel": "ä_Define Non-Standard Grid________Ü",
  "newGRGAreaBySizeTitle": "ä_GRG from an Area by Dimension__________Ü",
  "newGRGAreaBySizeDefineAreaLabel": "ä_GRG Area___Ü",
  "addGRGAreaPolygonToolTip": "ä_Draw GRG Area using polygon_________Ü",
  "addGRGAreaExtentToolTip": "ä_Draw GRG Area using extent_________Ü",
  "rotation": "ä_Grid Rotation_____Ü",
  "numberRowsColumnsLabel": "ä_Define number of rows and columns___________Ü",
  "newGRGAreaByRefSystemTitle": "ä_GRG from an Area by Reference System____________Ü",
  "gridSize": "ä_Grid Size____Ü",
  "UTMZoneandBand": "ä_Grid Zone____Ü",
  "100000m": "ä_100000 meter_____Ü",
  "10000m": "ä_10000 meter____Ü",
  "1000m": "ä_1000 meter____Ü",
  "100m": "ä_100 meter____Ü",
  "10m": "ä_10 meter___Ü",
  "clipGrid": "ä_Clip Grid to GRG Area_______Ü",
  "newGRGAreaFromNonStandardTitle": "ä_New NRG___Ü",
  "newGRGPointBySizeTitle": "ä_GRG from Point by Dimension_________Ü",
  "newGRGPointByRefSystemTitle": "ä_GRG from Point by Reference System___________Ü",
  "newGRGPointByTimeTitle": "ä_GRG from Point using Time and Speed____________Ü",
  "time": "ä_Time__Ü",
  "rate": "ä_Speed___Ü",
  "hours": "ä_Hours___Ü",
  "minutes": "ä_Minutes___Ü",
  "seconds": "ä_Seconds___Ü",
  "ftPerSec": "ä_Feet / second_____Ü",
  "ftPerHour": "ä_Feet / hour____Ü",
  "kmPerSec": "ä_Kilometers / second_______Ü",
  "kmPerHour": "ä_Kilometers / hour______Ü",
  "mPerSec": "ä_Meters / second______Ü",
  "mPerHour": "ä_Meters / hour_____Ü",
  "miPerSec": "ä_Miles / second_____Ü",
  "miPerHour": "ä_Miles / hour_____Ü",
  "nMPerSec": "ä_Nautical Miles / second________Ü",
  "nMPerHour": "ä_Nautical Miles / hour_______Ü",
  "settingsTitle": "ä_Settings___Ü",
  "labelSettingsLabel": "ä_Label Settings_____Ü",
  "labelSettingsButtonLabel": "ä_Configure Label Settings________Ü",
  "gridSettingsLabel": "ä_Grid Settings_____Ü",
  "gridSettingsButtonLabel": "ä_Configure Grid Settings________Ü",
  "transparency": "ä_Transparency_____Ü",
  "labelStyle": "ä_Label Style____Ü",
  "font": "ä_Font__Ü",
  "textSize": "ä_Text Size____Ü",
  "textColor": "ä_Text Color____Ü",
  "halo": "ä_Halo__Ü",
  "show": "ä_Show__Ü",
  "lockSettings": "ä_Settings have been locked by the application owner________________Ü",
  "gridSettings": {
    "cellShape": "ä_Cell Shape____Ü",
    "cellUnits": "ä_Cell Units____Ü",
    "cellOutline": "ä_Cell Outline Settings_______Ü",
    "cellFill": "ä_Cell Fill Settings______Ü",
    "gridReferenceSystem": "ä_Reference System______Ü",
    "gridDatum": "ä_Datum: WGS84_____Ü",
    "labelStartPosition": "ä_Label Origin_____Ü",
    "labelType": "ä_Label Type____Ü",
    "labelDirection": "ä_Label Direction______Ü",
    "gridOrigin": "ä_Grid Origin____Ü",
    "default": "ä_Rectangle____Ü",
    "hexagon": "ä_Hexagon___Ü",
    "miles": "ä_Miles___Ü",
    "kilometers": "ä_Kilometers____Ü",
    "feet": "ä_Feet__Ü",
    "meters": "ä_Meters___Ü",
    "yards": "ä_Yards___Ü",
    "nautical-miles": "ä_Nautical Miles_____Ü",
    "lowerLeft": "ä_Lower-Left____Ü",
    "lowerRight": "ä_Lower-Right____Ü",
    "upperLeft": "ä_Upper-Left____Ü",
    "upperRight": "ä_Upper-Right____Ü",
    "center": "ä_Center___Ü",
    "alphaNumeric": "ä_Alpha-Numeric_____Ü",
    "alphaAlpha": "ä_Alpha-Alpha____Ü",
    "numeric": "ä_Numeric___Ü",
    "horizontal": "ä_Horizontal____Ü",
    "vertical": "ä_Vertical___Ü",
    "MGRS": "ä_MGRS__Ü",
    "USNG": "ä_USNG__Ü",
    "showLabels": "ä_Show Labels____Ü"
  },
  "publishTitle": "ä_Publish GRG to Portal_______Ü",
  "publishGRGBtn": "ä_Publish___Ü",
  "GRGLayerName": "ä_Published GRG Layer Name________Ü",
  "invalidGRGLayerName": "ä_Layer name must only contain alpha-numeric characters and underscores______________________Ü",
  "missingGRGLayerName": "ä_You must enter a name for the GRG___________Ü",
  "publishingFailedLayerExists": "ä_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________Ü.",
  "checkService": "ä_Check Service: {0}______Ü",
  "createService": "ä_Create Service: {0}_______Ü",
  "unableToCreate": "ä_Unable to create: {0}_______Ü",
  "addToDefinition": "ä_Add to definition: {0}________Ü",
  "successfullyPublished": "ä_Successfully published web layer{0}Manage the web layer__________________Ü",
  "userRole": "ä_Unable to create service because user does not have permissions____________________Ü",
  "createGRGBtn": "ä_Create GRG____Ü",
  "clearGRGBtn": "ä_Clear___Ü",
  "labelFormat": "ä_Label Format_____Ü",
  "helpIconTooltip": "ä_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________Ü",
  "addPointToolTip": "ä_Add GRG Origin_____Ü",
  "cellWidth": "ä_Cell Width (x)_____Ü",
  "cellHeight": "ä_Cell Height (y)______Ü",
  "invalidNumberMessage": "ä_The value entered is not valid__________Ü",
  "invalidRangeMessage": "ä_Value must be greater than 0_________Ü",
  "gridAngleInvalidRangeMessage": "ä_Value must be between -89.9 and 89.9____________Ü",
  "formatIconTooltip": "ä_Format Input_____Ü",
  "coordInputLabel": "ä_GRG Origin (DD)______Ü",
  "setCoordFormat": "ä_Set Coordinate Format String_________Ü",
  "prefixNumbers": "ä_Add '+/-' prefix to positive and negative numbers________________Ü",
  "cancelBtn": "ä_Cancel___Ü",
  "applyBtn": "ä_Apply___Ü",
  "comfirmInputNotation": "ä_Confirm Input Notation________Ü",
  "notationsMatch": "ä_notations match your input please confirm which you would like to use______________________Ü:",
  "numberOfCellsHorizontal": "ä_# Horizontal Cells______Ü",
  "numberOfCellsVertical": "ä_# Vertical Cells______Ü",
  "gridAngle": "ä_Grid Rotation_____Ü",
  "tooManyCellsErrorMessage": "ä_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________Ü.",
  "missingParametersMessage": "ä_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________Ü",
  "missingOriginParametersMessage": "ä_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________Ü",
  "invalidWidthHeightParametersMessage": "ä_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________Ü",
  "invalidHorizontalVerticalParametersMessage": "ä_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________Ü",
  "drawPointToolTip": "ä_Click to add GRG origin point__________Ü",
  "missingLayerNameMessage": "ä_You must enter a valid layer name before you can publish__________________Ü",
  "parseCoordinatesError": "ä_Unable to parse coordinates. Please check your input_________________Ü.",
  "grgPolarRegionError": "ä_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________Ü.",
  "grgPolarOriginError": "ä_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________Ü.",
  "DD": "ä_DD__Ü",
  "DDM": "ä_DDM__Ü",
  "DMS": "ä_DMS__Ü",
  "DDRev": "ä_DDRev___Ü",
  "DDMRev": "ä_DDMRev___Ü",
  "DMSRev": "ä_DMSRev___Ü",
  "USNG": "ä_USNG__Ü",
  "MGRS": "ä_MGRS__Ü",
  "UTM_H": "ä_UTM (H)___Ü",
  "UTM": "ä_UTM__Ü",
  "GARS": "ä_GARS__Ü",
  "GEOREF": "ä_GEOREF___Ü",
  "DDLatLongNotation": "ä_Decimal Degrees - Latitude/Longitude____________Ü",
  "DDLongLatNotation": "ä_Decimal Degrees  - Longitude/Latitude____________Ü",
  "DDMLatLongNotation": "ä_Degrees Decimal Minutes - Latitude/Longitude______________Ü",
  "DDMLongLatNotation": "ä_Degrees Decimal Minutes - Longitude/Latitude______________Ü",
  "DMSLatLongNotation": "ä_Degrees Minutes Seconds - Latitude/Longitude______________Ü",
  "DMSLongLatNotation": "ä_Degrees Minutes Seconds - Longitude/Latitude______________Ü",
  "GARSNotation": "ä_GARS__Ü",
  "GEOREFNotation": "ä_GEOREF___Ü",
  "MGRSNotation": "ä_MGRS__Ü",
  "USNGNotation": "ä_USNG__Ü",
  "UTMBandNotation": "ä_UTM - Band Letter______Ü",
  "UTMHemNotation": "ä_UTM - Hemisphere (N/S)________Ü"
});