define({
  "gridTabLabel": "Š_Grid__ä",
  "labelTabLabel": "Š_Labels___ä",
  "referenceSystemTabLabel": "Š_Reference System______ä",
  "gridTabDescription": "Š_Set the appearance and behavior of the grid cells________________ä.",
  "cellOutlineColor": "Š_Cell Outine color______ä",
  "cellFillColor": "Š_Cell Fill color______ä",
  "transparency": "Š_Transparency_____ä",
  "cellShapeDropDown": "Š_Cell Shape____ä",
  "default": "Š_Rectangle____ä",
  "hexagon": "Š_Hexagon___ä",
  "cellUnitsDropDown": "Š_Cell Units____ä",
  "miles": "Š_Miles___ä",
  "kilometers": "Š_Kilometers____ä",
  "feet": "Š_Feet__ä",
  "meters": "Š_Meters___ä",
  "yards": "Š_Yards___ä",
  "nautical-miles": "Š_Nautical Miles_____ä",
  "gridOriginDropDown": "Š_Grid Origin____ä",
  "lowerLeft": "Š_Lower-Left____ä",
  "lowerRight": "Š_Lower-Right____ä",
  "upperLeft": "Š_Upper-Left____ä",
  "upperRight": "Š_Upper-Right____ä",
  "center": "Š_Center___ä",
  "labelTabDescription": "Š_Set the appearance and behavior of the grid labels________________ä.",
  "labelSettings": "Š_Label Style____ä",
  "font": "Š_Font__ä",
  "textSize": "Š_Text Size____ä",
  "textColor": "Š_Text Color____ä",
  "halo": "Š_Halo__ä",
  "show": "Š_Show__ä",
  "labelTypeDropDown": "Š_Label Type____ä",
  "alphaNumeric": "Š_Alpha-Numeric_____ä",
  "alphaAlpha": "Š_Alpha-Alpha____ä",
  "numeric": "Š_Numeric___ä",
  "labelDirectionDropDown": "Š_Label Direction______ä",
  "horizontal": "Š_Horizontal____ä",
  "vertical": "Š_Vertical___ä",
  "labelOriginDropDown": "Š_Label Origin_____ä",
  "referenceSystemlTabDescription": "Š_Set the default reference system___________ä.",
  "MGRS": "Š_MGRS__ä",
  "USNG": "Š_USNG__ä",
  "lockSettings": "Š_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________ä"
});