define({
  "gridTabLabel": "Į_Grid__š",
  "labelTabLabel": "Į_Labels___š",
  "referenceSystemTabLabel": "Į_Reference System______š",
  "gridTabDescription": "Į_Set the appearance and behavior of the grid cells________________š.",
  "cellOutlineColor": "Į_Cell Outine color______š",
  "cellFillColor": "Į_Cell Fill color______š",
  "transparency": "Į_Transparency_____š",
  "cellShapeDropDown": "Į_Cell Shape____š",
  "default": "Į_Rectangle____š",
  "hexagon": "Į_Hexagon___š",
  "cellUnitsDropDown": "Į_Cell Units____š",
  "miles": "Į_Miles___š",
  "kilometers": "Į_Kilometers____š",
  "feet": "Į_Feet__š",
  "meters": "Į_Meters___š",
  "yards": "Į_Yards___š",
  "nautical-miles": "Į_Nautical Miles_____š",
  "gridOriginDropDown": "Į_Grid Origin____š",
  "lowerLeft": "Į_Lower-Left____š",
  "lowerRight": "Į_Lower-Right____š",
  "upperLeft": "Į_Upper-Left____š",
  "upperRight": "Į_Upper-Right____š",
  "center": "Į_Center___š",
  "labelTabDescription": "Į_Set the appearance and behavior of the grid labels________________š.",
  "labelSettings": "Į_Label Style____š",
  "font": "Į_Font__š",
  "textSize": "Į_Text Size____š",
  "textColor": "Į_Text Color____š",
  "halo": "Į_Halo__š",
  "show": "Į_Show__š",
  "labelTypeDropDown": "Į_Label Type____š",
  "alphaNumeric": "Į_Alpha-Numeric_____š",
  "alphaAlpha": "Į_Alpha-Alpha____š",
  "numeric": "Į_Numeric___š",
  "labelDirectionDropDown": "Į_Label Direction______š",
  "horizontal": "Į_Horizontal____š",
  "vertical": "Į_Vertical___š",
  "labelOriginDropDown": "Į_Label Origin_____š",
  "referenceSystemlTabDescription": "Į_Set the default reference system___________š.",
  "MGRS": "Į_MGRS__š",
  "USNG": "Į_USNG__š",
  "lockSettings": "Į_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________š"
});