define({
  "_widgetLabel": "é_Gridded Reference Graphic_________È",
  "newGRGFromAreaButtonLabel": "é_Define a Grid from an Area_________È",
  "newGRGFromPointButtonLabel": "é_Define a Grid from a Point_________È",
  "newGRGFromAreaTitle": "é_Define a Grid from an Area_________È",
  "newGRGFromPointTitle": "é_Define a Grid from a Point_________È",
  "newGRGBySizeButtonLabel": "é_By Dimension_____È",
  "newGRGFromRefSystemButtonLabel": "é_By Reference System_______È",
  "newGRGByTimeLabel": "é_By Time and Speed______È",
  "newGRGFromNonStandardButtonLabel": "é_Define Non-Standard Grid________È",
  "newGRGAreaBySizeTitle": "é_GRG from an Area by Dimension__________È",
  "newGRGAreaBySizeDefineAreaLabel": "é_GRG Area___È",
  "addGRGAreaPolygonToolTip": "é_Draw GRG Area using polygon_________È",
  "addGRGAreaExtentToolTip": "é_Draw GRG Area using extent_________È",
  "rotation": "é_Grid Rotation_____È",
  "numberRowsColumnsLabel": "é_Define number of rows and columns___________È",
  "newGRGAreaByRefSystemTitle": "é_GRG from an Area by Reference System____________È",
  "gridSize": "é_Grid Size____È",
  "UTMZoneandBand": "é_Grid Zone____È",
  "100000m": "é_100000 meter_____È",
  "10000m": "é_10000 meter____È",
  "1000m": "é_1000 meter____È",
  "100m": "é_100 meter____È",
  "10m": "é_10 meter___È",
  "clipGrid": "é_Clip Grid to GRG Area_______È",
  "newGRGAreaFromNonStandardTitle": "é_New NRG___È",
  "newGRGPointBySizeTitle": "é_GRG from Point by Dimension_________È",
  "newGRGPointByRefSystemTitle": "é_GRG from Point by Reference System___________È",
  "newGRGPointByTimeTitle": "é_GRG from Point using Time and Speed____________È",
  "time": "é_Time__È",
  "rate": "é_Speed___È",
  "hours": "é_Hours___È",
  "minutes": "é_Minutes___È",
  "seconds": "é_Seconds___È",
  "ftPerSec": "é_Feet / second_____È",
  "ftPerHour": "é_Feet / hour____È",
  "kmPerSec": "é_Kilometers / second_______È",
  "kmPerHour": "é_Kilometers / hour______È",
  "mPerSec": "é_Meters / second______È",
  "mPerHour": "é_Meters / hour_____È",
  "miPerSec": "é_Miles / second_____È",
  "miPerHour": "é_Miles / hour_____È",
  "nMPerSec": "é_Nautical Miles / second________È",
  "nMPerHour": "é_Nautical Miles / hour_______È",
  "settingsTitle": "é_Settings___È",
  "labelSettingsLabel": "é_Label Settings_____È",
  "labelSettingsButtonLabel": "é_Configure Label Settings________È",
  "gridSettingsLabel": "é_Grid Settings_____È",
  "gridSettingsButtonLabel": "é_Configure Grid Settings________È",
  "transparency": "é_Transparency_____È",
  "labelStyle": "é_Label Style____È",
  "font": "é_Font__È",
  "textSize": "é_Text Size____È",
  "textColor": "é_Text Color____È",
  "halo": "é_Halo__È",
  "show": "é_Show__È",
  "lockSettings": "é_Settings have been locked by the application owner________________È",
  "gridSettings": {
    "cellShape": "é_Cell Shape____È",
    "cellUnits": "é_Cell Units____È",
    "cellOutline": "é_Cell Outline Settings_______È",
    "cellFill": "é_Cell Fill Settings______È",
    "gridReferenceSystem": "é_Reference System______È",
    "gridDatum": "é_Datum: WGS84_____È",
    "labelStartPosition": "é_Label Origin_____È",
    "labelType": "é_Label Type____È",
    "labelDirection": "é_Label Direction______È",
    "gridOrigin": "é_Grid Origin____È",
    "default": "é_Rectangle____È",
    "hexagon": "é_Hexagon___È",
    "miles": "é_Miles___È",
    "kilometers": "é_Kilometers____È",
    "feet": "é_Feet__È",
    "meters": "é_Meters___È",
    "yards": "é_Yards___È",
    "nautical-miles": "é_Nautical Miles_____È",
    "lowerLeft": "é_Lower-Left____È",
    "lowerRight": "é_Lower-Right____È",
    "upperLeft": "é_Upper-Left____È",
    "upperRight": "é_Upper-Right____È",
    "center": "é_Center___È",
    "alphaNumeric": "é_Alpha-Numeric_____È",
    "alphaAlpha": "é_Alpha-Alpha____È",
    "numeric": "é_Numeric___È",
    "horizontal": "é_Horizontal____È",
    "vertical": "é_Vertical___È",
    "MGRS": "é_MGRS__È",
    "USNG": "é_USNG__È",
    "showLabels": "é_Show Labels____È"
  },
  "publishTitle": "é_Publish GRG to Portal_______È",
  "publishGRGBtn": "é_Publish___È",
  "GRGLayerName": "é_Published GRG Layer Name________È",
  "invalidGRGLayerName": "é_Layer name must only contain alpha-numeric characters and underscores______________________È",
  "missingGRGLayerName": "é_You must enter a name for the GRG___________È",
  "publishingFailedLayerExists": "é_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________È.",
  "checkService": "é_Check Service: {0}______È",
  "createService": "é_Create Service: {0}_______È",
  "unableToCreate": "é_Unable to create: {0}_______È",
  "addToDefinition": "é_Add to definition: {0}________È",
  "successfullyPublished": "é_Successfully published web layer{0}Manage the web layer__________________È",
  "userRole": "é_Unable to create service because user does not have permissions____________________È",
  "createGRGBtn": "é_Create GRG____È",
  "clearGRGBtn": "é_Clear___È",
  "labelFormat": "é_Label Format_____È",
  "helpIconTooltip": "é_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________È",
  "addPointToolTip": "é_Add GRG Origin_____È",
  "cellWidth": "é_Cell Width (x)_____È",
  "cellHeight": "é_Cell Height (y)______È",
  "invalidNumberMessage": "é_The value entered is not valid__________È",
  "invalidRangeMessage": "é_Value must be greater than 0_________È",
  "gridAngleInvalidRangeMessage": "é_Value must be between -89.9 and 89.9____________È",
  "formatIconTooltip": "é_Format Input_____È",
  "coordInputLabel": "é_GRG Origin (DD)______È",
  "setCoordFormat": "é_Set Coordinate Format String_________È",
  "prefixNumbers": "é_Add '+/-' prefix to positive and negative numbers________________È",
  "cancelBtn": "é_Cancel___È",
  "applyBtn": "é_Apply___È",
  "comfirmInputNotation": "é_Confirm Input Notation________È",
  "notationsMatch": "é_notations match your input please confirm which you would like to use______________________È:",
  "numberOfCellsHorizontal": "é_# Horizontal Cells______È",
  "numberOfCellsVertical": "é_# Vertical Cells______È",
  "gridAngle": "é_Grid Rotation_____È",
  "tooManyCellsErrorMessage": "é_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________È.",
  "missingParametersMessage": "é_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________È",
  "missingOriginParametersMessage": "é_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________È",
  "invalidWidthHeightParametersMessage": "é_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________È",
  "invalidHorizontalVerticalParametersMessage": "é_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________È",
  "drawPointToolTip": "é_Click to add GRG origin point__________È",
  "missingLayerNameMessage": "é_You must enter a valid layer name before you can publish__________________È",
  "parseCoordinatesError": "é_Unable to parse coordinates. Please check your input_________________È.",
  "grgPolarRegionError": "é_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________È.",
  "grgPolarOriginError": "é_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________È.",
  "DD": "é_DD__È",
  "DDM": "é_DDM__È",
  "DMS": "é_DMS__È",
  "DDRev": "é_DDRev___È",
  "DDMRev": "é_DDMRev___È",
  "DMSRev": "é_DMSRev___È",
  "USNG": "é_USNG__È",
  "MGRS": "é_MGRS__È",
  "UTM_H": "é_UTM (H)___È",
  "UTM": "é_UTM__È",
  "GARS": "é_GARS__È",
  "GEOREF": "é_GEOREF___È",
  "DDLatLongNotation": "é_Decimal Degrees - Latitude/Longitude____________È",
  "DDLongLatNotation": "é_Decimal Degrees  - Longitude/Latitude____________È",
  "DDMLatLongNotation": "é_Degrees Decimal Minutes - Latitude/Longitude______________È",
  "DDMLongLatNotation": "é_Degrees Decimal Minutes - Longitude/Latitude______________È",
  "DMSLatLongNotation": "é_Degrees Minutes Seconds - Latitude/Longitude______________È",
  "DMSLongLatNotation": "é_Degrees Minutes Seconds - Longitude/Latitude______________È",
  "GARSNotation": "é_GARS__È",
  "GEOREFNotation": "é_GEOREF___È",
  "MGRSNotation": "é_MGRS__È",
  "USNGNotation": "é_USNG__È",
  "UTMBandNotation": "é_UTM - Band Letter______È",
  "UTMHemNotation": "é_UTM - Hemisphere (N/S)________È"
});