define({
  "gridTabLabel": "ä_Grid__Ü",
  "labelTabLabel": "ä_Labels___Ü",
  "referenceSystemTabLabel": "ä_Reference System______Ü",
  "gridTabDescription": "ä_Set the appearance and behavior of the grid cells________________Ü.",
  "cellOutlineColor": "ä_Cell Outine color______Ü",
  "cellFillColor": "ä_Cell Fill color______Ü",
  "transparency": "ä_Transparency_____Ü",
  "cellShapeDropDown": "ä_Cell Shape____Ü",
  "default": "ä_Rectangle____Ü",
  "hexagon": "ä_Hexagon___Ü",
  "cellUnitsDropDown": "ä_Cell Units____Ü",
  "miles": "ä_Miles___Ü",
  "kilometers": "ä_Kilometers____Ü",
  "feet": "ä_Feet__Ü",
  "meters": "ä_Meters___Ü",
  "yards": "ä_Yards___Ü",
  "nautical-miles": "ä_Nautical Miles_____Ü",
  "gridOriginDropDown": "ä_Grid Origin____Ü",
  "lowerLeft": "ä_Lower-Left____Ü",
  "lowerRight": "ä_Lower-Right____Ü",
  "upperLeft": "ä_Upper-Left____Ü",
  "upperRight": "ä_Upper-Right____Ü",
  "center": "ä_Center___Ü",
  "labelTabDescription": "ä_Set the appearance and behavior of the grid labels________________Ü.",
  "labelSettings": "ä_Label Style____Ü",
  "font": "ä_Font__Ü",
  "textSize": "ä_Text Size____Ü",
  "textColor": "ä_Text Color____Ü",
  "halo": "ä_Halo__Ü",
  "show": "ä_Show__Ü",
  "labelTypeDropDown": "ä_Label Type____Ü",
  "alphaNumeric": "ä_Alpha-Numeric_____Ü",
  "alphaAlpha": "ä_Alpha-Alpha____Ü",
  "numeric": "ä_Numeric___Ü",
  "labelDirectionDropDown": "ä_Label Direction______Ü",
  "horizontal": "ä_Horizontal____Ü",
  "vertical": "ä_Vertical___Ü",
  "labelOriginDropDown": "ä_Label Origin_____Ü",
  "referenceSystemlTabDescription": "ä_Set the default reference system___________Ü.",
  "MGRS": "ä_MGRS__Ü",
  "USNG": "ä_USNG__Ü",
  "lockSettings": "ä_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________Ü"
});