define({
  "gridTabLabel": "ı_Grid__İ",
  "labelTabLabel": "ı_Labels___İ",
  "referenceSystemTabLabel": "ı_Reference System______İ",
  "gridTabDescription": "ı_Set the appearance and behavior of the grid cells________________İ.",
  "cellOutlineColor": "ı_Cell Outine color______İ",
  "cellFillColor": "ı_Cell Fill color______İ",
  "transparency": "ı_Transparency_____İ",
  "cellShapeDropDown": "ı_Cell Shape____İ",
  "default": "ı_Rectangle____İ",
  "hexagon": "ı_Hexagon___İ",
  "cellUnitsDropDown": "ı_Cell Units____İ",
  "miles": "ı_Miles___İ",
  "kilometers": "ı_Kilometers____İ",
  "feet": "ı_Feet__İ",
  "meters": "ı_Meters___İ",
  "yards": "ı_Yards___İ",
  "nautical-miles": "ı_Nautical Miles_____İ",
  "gridOriginDropDown": "ı_Grid Origin____İ",
  "lowerLeft": "ı_Lower-Left____İ",
  "lowerRight": "ı_Lower-Right____İ",
  "upperLeft": "ı_Upper-Left____İ",
  "upperRight": "ı_Upper-Right____İ",
  "center": "ı_Center___İ",
  "labelTabDescription": "ı_Set the appearance and behavior of the grid labels________________İ.",
  "labelSettings": "ı_Label Style____İ",
  "font": "ı_Font__İ",
  "textSize": "ı_Text Size____İ",
  "textColor": "ı_Text Color____İ",
  "halo": "ı_Halo__İ",
  "show": "ı_Show__İ",
  "labelTypeDropDown": "ı_Label Type____İ",
  "alphaNumeric": "ı_Alpha-Numeric_____İ",
  "alphaAlpha": "ı_Alpha-Alpha____İ",
  "numeric": "ı_Numeric___İ",
  "labelDirectionDropDown": "ı_Label Direction______İ",
  "horizontal": "ı_Horizontal____İ",
  "vertical": "ı_Vertical___İ",
  "labelOriginDropDown": "ı_Label Origin_____İ",
  "referenceSystemlTabDescription": "ı_Set the default reference system___________İ.",
  "MGRS": "ı_MGRS__İ",
  "USNG": "ı_USNG__İ",
  "lockSettings": "ı_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________İ"
});