define({
  "_widgetLabel": "한_Gridded Reference Graphic_________빠",
  "newGRGFromAreaButtonLabel": "한_Define a Grid from an Area_________빠",
  "newGRGFromPointButtonLabel": "한_Define a Grid from a Point_________빠",
  "newGRGFromAreaTitle": "한_Define a Grid from an Area_________빠",
  "newGRGFromPointTitle": "한_Define a Grid from a Point_________빠",
  "newGRGBySizeButtonLabel": "한_By Dimension_____빠",
  "newGRGFromRefSystemButtonLabel": "한_By Reference System_______빠",
  "newGRGByTimeLabel": "한_By Time and Speed______빠",
  "newGRGFromNonStandardButtonLabel": "한_Define Non-Standard Grid________빠",
  "newGRGAreaBySizeTitle": "한_GRG from an Area by Dimension__________빠",
  "newGRGAreaBySizeDefineAreaLabel": "한_GRG Area___빠",
  "addGRGAreaPolygonToolTip": "한_Draw GRG Area using polygon_________빠",
  "addGRGAreaExtentToolTip": "한_Draw GRG Area using extent_________빠",
  "rotation": "한_Grid Rotation_____빠",
  "numberRowsColumnsLabel": "한_Define number of rows and columns___________빠",
  "newGRGAreaByRefSystemTitle": "한_GRG from an Area by Reference System____________빠",
  "gridSize": "한_Grid Size____빠",
  "UTMZoneandBand": "한_Grid Zone____빠",
  "100000m": "한_100000 meter_____빠",
  "10000m": "한_10000 meter____빠",
  "1000m": "한_1000 meter____빠",
  "100m": "한_100 meter____빠",
  "10m": "한_10 meter___빠",
  "clipGrid": "한_Clip Grid to GRG Area_______빠",
  "newGRGAreaFromNonStandardTitle": "한_New NRG___빠",
  "newGRGPointBySizeTitle": "한_GRG from Point by Dimension_________빠",
  "newGRGPointByRefSystemTitle": "한_GRG from Point by Reference System___________빠",
  "newGRGPointByTimeTitle": "한_GRG from Point using Time and Speed____________빠",
  "time": "한_Time__빠",
  "rate": "한_Speed___빠",
  "hours": "한_Hours___빠",
  "minutes": "한_Minutes___빠",
  "seconds": "한_Seconds___빠",
  "ftPerSec": "한_Feet / second_____빠",
  "ftPerHour": "한_Feet / hour____빠",
  "kmPerSec": "한_Kilometers / second_______빠",
  "kmPerHour": "한_Kilometers / hour______빠",
  "mPerSec": "한_Meters / second______빠",
  "mPerHour": "한_Meters / hour_____빠",
  "miPerSec": "한_Miles / second_____빠",
  "miPerHour": "한_Miles / hour_____빠",
  "nMPerSec": "한_Nautical Miles / second________빠",
  "nMPerHour": "한_Nautical Miles / hour_______빠",
  "settingsTitle": "한_Settings___빠",
  "labelSettingsLabel": "한_Label Settings_____빠",
  "labelSettingsButtonLabel": "한_Configure Label Settings________빠",
  "gridSettingsLabel": "한_Grid Settings_____빠",
  "gridSettingsButtonLabel": "한_Configure Grid Settings________빠",
  "transparency": "한_Transparency_____빠",
  "labelStyle": "한_Label Style____빠",
  "font": "한_Font__빠",
  "textSize": "한_Text Size____빠",
  "textColor": "한_Text Color____빠",
  "halo": "한_Halo__빠",
  "show": "한_Show__빠",
  "lockSettings": "한_Settings have been locked by the application owner________________빠",
  "gridSettings": {
    "cellShape": "한_Cell Shape____빠",
    "cellUnits": "한_Cell Units____빠",
    "cellOutline": "한_Cell Outline Settings_______빠",
    "cellFill": "한_Cell Fill Settings______빠",
    "gridReferenceSystem": "한_Reference System______빠",
    "gridDatum": "한_Datum: WGS84_____빠",
    "labelStartPosition": "한_Label Origin_____빠",
    "labelType": "한_Label Type____빠",
    "labelDirection": "한_Label Direction______빠",
    "gridOrigin": "한_Grid Origin____빠",
    "default": "한_Rectangle____빠",
    "hexagon": "한_Hexagon___빠",
    "miles": "한_Miles___빠",
    "kilometers": "한_Kilometers____빠",
    "feet": "한_Feet__빠",
    "meters": "한_Meters___빠",
    "yards": "한_Yards___빠",
    "nautical-miles": "한_Nautical Miles_____빠",
    "lowerLeft": "한_Lower-Left____빠",
    "lowerRight": "한_Lower-Right____빠",
    "upperLeft": "한_Upper-Left____빠",
    "upperRight": "한_Upper-Right____빠",
    "center": "한_Center___빠",
    "alphaNumeric": "한_Alpha-Numeric_____빠",
    "alphaAlpha": "한_Alpha-Alpha____빠",
    "numeric": "한_Numeric___빠",
    "horizontal": "한_Horizontal____빠",
    "vertical": "한_Vertical___빠",
    "MGRS": "한_MGRS__빠",
    "USNG": "한_USNG__빠",
    "showLabels": "한_Show Labels____빠"
  },
  "publishTitle": "한_Publish GRG to Portal_______빠",
  "publishGRGBtn": "한_Publish___빠",
  "GRGLayerName": "한_Published GRG Layer Name________빠",
  "invalidGRGLayerName": "한_Layer name must only contain alpha-numeric characters and underscores______________________빠",
  "missingGRGLayerName": "한_You must enter a name for the GRG___________빠",
  "publishingFailedLayerExists": "한_Publishing Failed: You already have a feature service named {0}. Please choose another name_____________________________빠.",
  "checkService": "한_Check Service: {0}______빠",
  "createService": "한_Create Service: {0}_______빠",
  "unableToCreate": "한_Unable to create: {0}_______빠",
  "addToDefinition": "한_Add to definition: {0}________빠",
  "successfullyPublished": "한_Successfully published web layer{0}Manage the web layer__________________빠",
  "userRole": "한_Unable to create service because user does not have permissions____________________빠",
  "createGRGBtn": "한_Create GRG____빠",
  "clearGRGBtn": "한_Clear___빠",
  "labelFormat": "한_Label Format_____빠",
  "helpIconTooltip": "한_Z: Grid Zone Designator (GZD)\nS: 100,000-meter Grid Square Identification (GSID)\nX: Easting (X Coordinate)\nY: Northing (Y Coordinate)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205______________________________________________________________빠",
  "addPointToolTip": "한_Add GRG Origin_____빠",
  "cellWidth": "한_Cell Width (x)_____빠",
  "cellHeight": "한_Cell Height (y)______빠",
  "invalidNumberMessage": "한_The value entered is not valid__________빠",
  "invalidRangeMessage": "한_Value must be greater than 0_________빠",
  "gridAngleInvalidRangeMessage": "한_Value must be between -89.9 and 89.9____________빠",
  "formatIconTooltip": "한_Format Input_____빠",
  "coordInputLabel": "한_GRG Origin (DD)______빠",
  "setCoordFormat": "한_Set Coordinate Format String_________빠",
  "prefixNumbers": "한_Add '+/-' prefix to positive and negative numbers________________빠",
  "cancelBtn": "한_Cancel___빠",
  "applyBtn": "한_Apply___빠",
  "comfirmInputNotation": "한_Confirm Input Notation________빠",
  "notationsMatch": "한_notations match your input please confirm which you would like to use______________________빠:",
  "numberOfCellsHorizontal": "한_# Horizontal Cells______빠",
  "numberOfCellsVertical": "한_# Vertical Cells______빠",
  "gridAngle": "한_Grid Rotation_____빠",
  "tooManyCellsErrorMessage": "한_You are attempting to create a grid comprising of more than 2000 cells. It is advisable to reduce the number of cells being created by changing the grid size or grid area____________________________________________________빠.",
  "missingParametersMessage": "한_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>______________________________________________________빠",
  "missingOriginParametersMessage": "한_<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>A GRG origin has been set.</li><li>The time, speed and angle inputs contain valid values.</li></ul>_________________________________________________________빠",
  "invalidWidthHeightParametersMessage": "한_<p>The GRG creation form has missing or invalid parameters. Please ensure the cell width and height inputs contain valid values.</p>_________________________________________빠",
  "invalidHorizontalVerticalParametersMessage": "한_<p>The GRG creation form has missing or invalid parameters. Please ensure the number of cells horizontal and vertical inputs contain valid values.</p>______________________________________________빠",
  "drawPointToolTip": "한_Click to add GRG origin point__________빠",
  "missingLayerNameMessage": "한_You must enter a valid layer name before you can publish__________________빠",
  "parseCoordinatesError": "한_Unable to parse coordinates. Please check your input_________________빠.",
  "grgPolarRegionError": "한_The GRG extent is within a polar region. Cells that fall within the polar region will not be created_______________________________빠.",
  "grgPolarOriginError": "한_The GRG origin point cannot be within a polar region when creating a GRG by Reference System_____________________________빠.",
  "DD": "한_DD__빠",
  "DDM": "한_DDM__빠",
  "DMS": "한_DMS__빠",
  "DDRev": "한_DDRev___빠",
  "DDMRev": "한_DDMRev___빠",
  "DMSRev": "한_DMSRev___빠",
  "USNG": "한_USNG__빠",
  "MGRS": "한_MGRS__빠",
  "UTM_H": "한_UTM (H)___빠",
  "UTM": "한_UTM__빠",
  "GARS": "한_GARS__빠",
  "GEOREF": "한_GEOREF___빠",
  "DDLatLongNotation": "한_Decimal Degrees - Latitude/Longitude____________빠",
  "DDLongLatNotation": "한_Decimal Degrees  - Longitude/Latitude____________빠",
  "DDMLatLongNotation": "한_Degrees Decimal Minutes - Latitude/Longitude______________빠",
  "DDMLongLatNotation": "한_Degrees Decimal Minutes - Longitude/Latitude______________빠",
  "DMSLatLongNotation": "한_Degrees Minutes Seconds - Latitude/Longitude______________빠",
  "DMSLongLatNotation": "한_Degrees Minutes Seconds - Longitude/Latitude______________빠",
  "GARSNotation": "한_GARS__빠",
  "GEOREFNotation": "한_GEOREF___빠",
  "MGRSNotation": "한_MGRS__빠",
  "USNGNotation": "한_USNG__빠",
  "UTMBandNotation": "한_UTM - Band Letter______빠",
  "UTMHemNotation": "한_UTM - Hemisphere (N/S)________빠"
});