define({
  root: ({
    tabAreaTitle: 'Create GRG By Area',
    tabPointTitle: 'Create GRG By Point',
    GRGLayerName: 'Published GRG Layer Name',
    invalidGRGLayerName: 'Layer name must only contain alpha-numeric characters and underscores',
    missingGRGLayerName: 'You must enter a name for the GRG',
    polygonDrawLabel: 'Use the draw tool to specify GRG Area',
    removeGRGLabel: 'Remove GRG Area',
    cellWidth: 'Cell Width',
    cellHeight: 'Cell Height',
    invalidNumberMessage: 'The value entered is not valid',
    invalidRangeMessage: 'Value must be greater than 0',
    cellShape: 'Cell Shape',
    cellUnits: 'Cell Units',
    labeling: 'Labeling',
    lowerLeft: 'Lower-Left',
    lowerRight: 'Lower-Right',
    upperLeft: 'Upper-Left',
    upperRight: 'Upper-Right',
    alphaNumeric: 'Alpha-Numeric',
    alphaAlpha: 'Alpha-Alpha',
    numeric: 'Numeric',
    miles: 'Miles',
    kilometers: 'Kilometers',
    feet: 'Feet',
    meters: 'Meters',
    yards: 'Yards',
    nauticalMiles: 'Nautical Miles',
    createGRGBtn: 'Create GRG',
    publishGRGBtn: 'Publish GRG to Portal',
    cancelBtn: 'Cancel',
    applyBtn: 'Apply',
    coordInputLabel: 'GRG Center Point',
    numberOfCells: 'Number of Cells (Horizontal x Vertical)',
    gridAngle: 'Grid Angle',
    choiceDefault: 'Default',
    choiceHexagon: 'Hexagon',
    missingParametersMessage: '<p>The GRG creation form has missing or invalid parameters, Please ensure:</p><ul><li>The GRG Name is not blank.</li><li>A GRG area has been drawn.</li><li>The cell width and height contain valid values.</li></ul>',
    coordInputError: 'Unable to determine input coordinate type please check your input',
    formatIconTooltip: 'Format Input',
    addPointToolTip: 'Add GRG Center Point',
    setCoordFormat: 'Set Coordinate Format String',
    prefixNumbers: 'Add "+/-" prefix to positive and negative numbers',
    confirmNotationTitle: 'Confirm Input Notation',
    notationsMatch: 'notations match your input please confirm which you would like to use:',
    prefixSuffixError: 'The input coordinate has been detected as having both a prefix and suffix for the latitude or longitude value, returned coordinate is based on the prefix',
    drawToolTip1: 'Click to set GRG base angle',
    drawToolTip2: 'Click to finish GRG Area',
 }),
});
