define({
  "gridTabLabel": "Ĳ_Grid__ä",
  "labelTabLabel": "Ĳ_Labels___ä",
  "referenceSystemTabLabel": "Ĳ_Reference System______ä",
  "gridTabDescription": "Ĳ_Set the appearance and behavior of the grid cells________________ä.",
  "cellOutlineColor": "Ĳ_Cell Outine color______ä",
  "cellFillColor": "Ĳ_Cell Fill color______ä",
  "transparency": "Ĳ_Transparency_____ä",
  "cellShapeDropDown": "Ĳ_Cell Shape____ä",
  "default": "Ĳ_Rectangle____ä",
  "hexagon": "Ĳ_Hexagon___ä",
  "cellUnitsDropDown": "Ĳ_Cell Units____ä",
  "miles": "Ĳ_Miles___ä",
  "kilometers": "Ĳ_Kilometers____ä",
  "feet": "Ĳ_Feet__ä",
  "meters": "Ĳ_Meters___ä",
  "yards": "Ĳ_Yards___ä",
  "nautical-miles": "Ĳ_Nautical Miles_____ä",
  "gridOriginDropDown": "Ĳ_Grid Origin____ä",
  "lowerLeft": "Ĳ_Lower-Left____ä",
  "lowerRight": "Ĳ_Lower-Right____ä",
  "upperLeft": "Ĳ_Upper-Left____ä",
  "upperRight": "Ĳ_Upper-Right____ä",
  "center": "Ĳ_Center___ä",
  "labelTabDescription": "Ĳ_Set the appearance and behavior of the grid labels________________ä.",
  "labelSettings": "Ĳ_Label Style____ä",
  "font": "Ĳ_Font__ä",
  "textSize": "Ĳ_Text Size____ä",
  "textColor": "Ĳ_Text Color____ä",
  "halo": "Ĳ_Halo__ä",
  "show": "Ĳ_Show__ä",
  "labelTypeDropDown": "Ĳ_Label Type____ä",
  "alphaNumeric": "Ĳ_Alpha-Numeric_____ä",
  "alphaAlpha": "Ĳ_Alpha-Alpha____ä",
  "numeric": "Ĳ_Numeric___ä",
  "labelDirectionDropDown": "Ĳ_Label Direction______ä",
  "horizontal": "Ĳ_Horizontal____ä",
  "vertical": "Ĳ_Vertical___ä",
  "labelOriginDropDown": "Ĳ_Label Origin_____ä",
  "referenceSystemlTabDescription": "Ĳ_Set the default reference system___________ä.",
  "MGRS": "Ĳ_MGRS__ä",
  "USNG": "Ĳ_USNG__ä",
  "lockSettings": "Ĳ_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________ä"
});