define({
  "gridTabLabel": "á_Grid__Ó",
  "labelTabLabel": "á_Labels___Ó",
  "referenceSystemTabLabel": "á_Reference System______Ó",
  "gridTabDescription": "á_Set the appearance and behavior of the grid cells________________Ó.",
  "cellOutlineColor": "á_Cell Outine color______Ó",
  "cellFillColor": "á_Cell Fill color______Ó",
  "transparency": "á_Transparency_____Ó",
  "cellShapeDropDown": "á_Cell Shape____Ó",
  "default": "á_Rectangle____Ó",
  "hexagon": "á_Hexagon___Ó",
  "cellUnitsDropDown": "á_Cell Units____Ó",
  "miles": "á_Miles___Ó",
  "kilometers": "á_Kilometers____Ó",
  "feet": "á_Feet__Ó",
  "meters": "á_Meters___Ó",
  "yards": "á_Yards___Ó",
  "nautical-miles": "á_Nautical Miles_____Ó",
  "gridOriginDropDown": "á_Grid Origin____Ó",
  "lowerLeft": "á_Lower-Left____Ó",
  "lowerRight": "á_Lower-Right____Ó",
  "upperLeft": "á_Upper-Left____Ó",
  "upperRight": "á_Upper-Right____Ó",
  "center": "á_Center___Ó",
  "labelTabDescription": "á_Set the appearance and behavior of the grid labels________________Ó.",
  "labelSettings": "á_Label Style____Ó",
  "font": "á_Font__Ó",
  "textSize": "á_Text Size____Ó",
  "textColor": "á_Text Color____Ó",
  "halo": "á_Halo__Ó",
  "show": "á_Show__Ó",
  "labelTypeDropDown": "á_Label Type____Ó",
  "alphaNumeric": "á_Alpha-Numeric_____Ó",
  "alphaAlpha": "á_Alpha-Alpha____Ó",
  "numeric": "á_Numeric___Ó",
  "labelDirectionDropDown": "á_Label Direction______Ó",
  "horizontal": "á_Horizontal____Ó",
  "vertical": "á_Vertical___Ó",
  "labelOriginDropDown": "á_Label Origin_____Ó",
  "referenceSystemlTabDescription": "á_Set the default reference system___________Ó.",
  "MGRS": "á_MGRS__Ó",
  "USNG": "á_USNG__Ó",
  "lockSettings": "á_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________Ó"
});