define({
  "gridTabLabel": "å_Grid__ø",
  "labelTabLabel": "å_Labels___ø",
  "referenceSystemTabLabel": "å_Reference System______ø",
  "gridTabDescription": "å_Set the appearance and behavior of the grid cells________________ø.",
  "cellOutlineColor": "å_Cell Outine color______ø",
  "cellFillColor": "å_Cell Fill color______ø",
  "transparency": "å_Transparency_____ø",
  "cellShapeDropDown": "å_Cell Shape____ø",
  "default": "å_Rectangle____ø",
  "hexagon": "å_Hexagon___ø",
  "cellUnitsDropDown": "å_Cell Units____ø",
  "miles": "å_Miles___ø",
  "kilometers": "å_Kilometers____ø",
  "feet": "å_Feet__ø",
  "meters": "å_Meters___ø",
  "yards": "å_Yards___ø",
  "nautical-miles": "å_Nautical Miles_____ø",
  "gridOriginDropDown": "å_Grid Origin____ø",
  "lowerLeft": "å_Lower-Left____ø",
  "lowerRight": "å_Lower-Right____ø",
  "upperLeft": "å_Upper-Left____ø",
  "upperRight": "å_Upper-Right____ø",
  "center": "å_Center___ø",
  "labelTabDescription": "å_Set the appearance and behavior of the grid labels________________ø.",
  "labelSettings": "å_Label Style____ø",
  "font": "å_Font__ø",
  "textSize": "å_Text Size____ø",
  "textColor": "å_Text Color____ø",
  "halo": "å_Halo__ø",
  "show": "å_Show__ø",
  "labelTypeDropDown": "å_Label Type____ø",
  "alphaNumeric": "å_Alpha-Numeric_____ø",
  "alphaAlpha": "å_Alpha-Alpha____ø",
  "numeric": "å_Numeric___ø",
  "labelDirectionDropDown": "å_Label Direction______ø",
  "horizontal": "å_Horizontal____ø",
  "vertical": "å_Vertical___ø",
  "labelOriginDropDown": "å_Label Origin_____ø",
  "referenceSystemlTabDescription": "å_Set the default reference system___________ø.",
  "MGRS": "å_MGRS__ø",
  "USNG": "å_USNG__ø",
  "lockSettings": "å_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________ø"
});