define({
  "gridTabLabel": "Š_Grid__č",
  "labelTabLabel": "Š_Labels___č",
  "referenceSystemTabLabel": "Š_Reference System______č",
  "gridTabDescription": "Š_Set the appearance and behavior of the grid cells________________č.",
  "cellOutlineColor": "Š_Cell Outine color______č",
  "cellFillColor": "Š_Cell Fill color______č",
  "transparency": "Š_Transparency_____č",
  "cellShapeDropDown": "Š_Cell Shape____č",
  "default": "Š_Rectangle____č",
  "hexagon": "Š_Hexagon___č",
  "cellUnitsDropDown": "Š_Cell Units____č",
  "miles": "Š_Miles___č",
  "kilometers": "Š_Kilometers____č",
  "feet": "Š_Feet__č",
  "meters": "Š_Meters___č",
  "yards": "Š_Yards___č",
  "nautical-miles": "Š_Nautical Miles_____č",
  "gridOriginDropDown": "Š_Grid Origin____č",
  "lowerLeft": "Š_Lower-Left____č",
  "lowerRight": "Š_Lower-Right____č",
  "upperLeft": "Š_Upper-Left____č",
  "upperRight": "Š_Upper-Right____č",
  "center": "Š_Center___č",
  "labelTabDescription": "Š_Set the appearance and behavior of the grid labels________________č.",
  "labelSettings": "Š_Label Style____č",
  "font": "Š_Font__č",
  "textSize": "Š_Text Size____č",
  "textColor": "Š_Text Color____č",
  "halo": "Š_Halo__č",
  "show": "Š_Show__č",
  "labelTypeDropDown": "Š_Label Type____č",
  "alphaNumeric": "Š_Alpha-Numeric_____č",
  "alphaAlpha": "Š_Alpha-Alpha____č",
  "numeric": "Š_Numeric___č",
  "labelDirectionDropDown": "Š_Label Direction______č",
  "horizontal": "Š_Horizontal____č",
  "vertical": "Š_Vertical___č",
  "labelOriginDropDown": "Š_Label Origin_____č",
  "referenceSystemlTabDescription": "Š_Set the default reference system___________č.",
  "MGRS": "Š_MGRS__č",
  "USNG": "Š_USNG__č",
  "lockSettings": "Š_Lock Settings - This will prevent the user from being able to change any of the configured settings within the widget____________________________________č"
});